// My Bhagavad Gita
// fullGita.js
// This file holds the entire dictionary representation of the Bhagavad Gita
// @author Vivek Bhookya
// @author
//
// –––
//
// Format: A dictionary of dictionaries of lists
// BHAGAVAD_GITA = {
//   "1" : {"1" : "blah blah", "2" : "blah blah", "3" : "blah blah", "4" : "blah blah"},
//   "2" : {},
//   "3" : {}
// }
//
// The format of the following structure is as follows:
// BHAGAVAD_GITA[CHAPTER NUMBER][VERSE PAIR][VERSE OR TRANSLATION OF VERSE]
//
// How we retreieve information depends on how we format our query:
// BHAGAVAD_GITA => The Gita
// BHAGAVAD_GITA[1] => Chapter 1 of the Gita
// BHAGAVAD_GITA[1][3] => Array of verse 3 and the meaning of verse 3 (the verse pair) from chapter 1 of the Gita

// BHAGAVAD_GITA[1][3][0] => Verse 3 from chapter 1 of the Gita
// BHAGAVAD_GITA[1][3][1] => English translation of verse 3 from chapter 1 of the Gita

// It will help to use predefined constants: VERSE = 0, CONSTANT = 1; when collecting the respective items from each verse pair

// Presenting the Bhagavad Gita in JavaScript glory
BHAGAVAD_GITA = {
  "1" : {
    "1" : ["dhrtarastra uvaca\ndharma-ksetre kuru-ksetre samaveta yuyutsavah\nmamakah pandavas caiva kim akurvata sanjaya (1.1)","Dhrtarastra said:\nO Sanjaya, what did the sons of Pandu and mine do when they gathered on\nthe sacred plain of Kuruksetra, eager for battle?"],
    "2" : ["sanjaya uvaca\ndrstva tu pandavanikam vyudham duryodhanas tada\nacaryam upasangamya raja vacanam abravit (1.2)", "Sanjaya said: Having seen the army of the Pandavas ranged for battle,\nPrince Duryodhana went up to his acarya (teacher), Drona, and said:"],
    "3" : ["pasyaitam pandu-putranam acarya mahatim camum\nvyudham drupada-putrena tava sisyena dhimata (1.3)", "Look, O Teacher, at this mighty army of the sons of Pandu, which has been\npositioned by your talented pupil, the son of Drupada."],
    "4" : ["atra sura mahesv-asa bhimarjuna-sama yudhi\nyuyudhano viratas ca drupadas ca maha-rathah (1.4)", "There are in it heroes, mighty archers, equal in battle to Bhima and\nArjuna: Yuyudhana, Virata, and the great warrior (mahdratha) Drupada,"],
    "5" : ["dhrstaketus cekitanah kasirajas ca viryavan\npurujit kuntibhojas ca saibyas ca nara-pungavah (1.5)", "Dhrishtaketu, Cekitana, and the valiant king of Kasi, Purujit, Kuntibhoja,\nand the prominent man Saibya,"],
    "6" : ["yudhamanyus ca vikranta uttamaujas ca viryavan\nsaubhadro draupadeyas ca sarva eva maha-rathah (1.6)", "The heroic Yudhamanyu, and the valiant Uttamauja; the son of Subhadra\nand the son of Draupadi, all proficient charioteers."],
    "7" : ["asmakam tu visista ye tan nibodha dvijottama\nnayaka mama sainyasya samjnartham tan bravimi te (1.7)", "I now mention, O best of the twice-born, who are the most distinguished\namong us, the commanders of my army, naming to you by way of example."],
    "8" : ["bhavan bhismas ca karnas ca krpas ca samitim-jayah\nasvatthama vikarnas ca saumadattis tathaiva ca (1.8)", "Yourself and Bhisma, Kama, the victorious Krpa, Asvatthama and\nVikarna, also Jayadratta, the son of Somadatta;"],
    "9" : ["anye ca bahavah sura mad-arthe tyakta-jivitah\nnana-sastra-praharanah sarve yuddha-visaradah (1.9)", "And, many other heroes giving up their lives for me, fighting with various\nweapons, and all well skilled in the art of warfare."],
    "10" : ["aparyaptam tad asmakam balam bhismabhiraksitam\nparyaptam tv idam etesam balam bhimabhiraksitam (1.10)", "This army of ours, commanded by Bhisma is unbeatable, whereas that\narmy of theirs which is under the protection of Bhima is inadequate."],
    "11" : ["ayanesu ca sarvesu yatha-bhagam avasthitah\nbhismam evabhiraksantu bhavantah sarva eva hi (1.11)", "Therefore, now, do all of you, occupying your respective positions in the\nvarious divisions of the army, defend Bhisma only."],
    "12" : ["tasya sanjanayan harsam kuru-vrddhah pitamahah\nsimha-nadam vinadyoccaih sankham dadhmau pratapavan (1.12)", "The powerful grandsire Bhisma, the eldest of the Kuru reign, in order to\ncheer him (Duryodhana), roared as a lion and blew his conch."],
    "13" : ["tatah sankhas ca bheryas ca panavanaka-gomukhah\nsahasaivabhyahanyanta sa sabdas tumulo \'bhavat (1.13)", "At this, and all at once, conches, kettledrums, cymbals, drums and horns\nwere heard, and the sound of that was uncontrolled."],
    "14" : ["tatah svetair hay air yukta mahati syandane sthitau\nmadhavah pandavas caiva divyau sankhau pradadhmatuh (1.14)", "Then, Madhava (Krsna) and the son of Pandu (Arjuna), who were seated in\ntheir grand chariot yoked to white horses, blew their divine conches."],
    "15" : ["pancajanyam hrsikeso devadattam dhananjayah\npaundram dadhmau maha-sankham bhima-karma vrkodarah (1.15)", "Hrsikesa (Krsna) blew the conch Pancajanya; and Dhananjaya (Arjuna, the\nwinner of wealth) blew his conch Devadatta. Bhima, the performer of\nterrible deeds, blew his great conch Paundra."],
    "16" : ["anantavijayam raja kunti-putro yudhisthirah\nnakulah sahadevas ca sughosa-manipuspakau (1.16)", "King Yudhisthira, the son of Kunti (Arjuna), blew his Anantavyaya, while\nNakula and Sahadeva blew the Sughosa and the Manipuspaka conches."],
    "17" : ["kasyas ca paramesv-asah sikhandi ca maha-rathah\ndhrstadyumno viratas ca satyakis caparajitah (1.17)", "The king of Kasi, an excellent archer; Sikhandi, the great chariot-warrior,\nDhrstadyumna, Virata, and the unconquerable Satyaki;"],
    "18" : ["drupado draupadeyas ca sarvasah prthivi-pate\nsaubhadras ca maha-bahuh sankhan dadhmuh prthak prthak (1.18)", "Drupada and the sons of Draupadi, O Lord of the Earth, and the mighty-\narmed son of Subhadra, all individually in one accord blew their respective\nconches."],
    "19" : ["sa ghoso dhartarastranam hrdayani vyadarayat\nnabhas caprthivim caiva tumulo bh/vyanunadayan (1.19)","The tumultuous uproar tore the hearts of the sons (people) of\nDhrtarashtra's assembly, filling the earth and sky with sound."],
    "20" : ["atha vyavasthitan drstva dhartarastran kapi dvajah\npravrtte sastra-sampate dhanur udyamya pandavah\nhrsikesam tada vakyam idam aha mahi-pate (1.20)","Then, looking at the sons of Dhritarashtra standing ranged for battle, while\nthe discharge of missiles began, Arjuna, the son of Pandu, whose emblem\ndepicts Maruki (a monkey) , took up his bow and spoke these words to\nHrslkesa (Krsna), O Lord of Earth:"],
    "21" : ["arjuna uvaca\nsenayor ubhayor madhye ratham sthapaya me \'cyuta\nyavad etan nirikse \'ham yod dhu-kaman avasthitan\nkair may a saha yoddhavyam asmin rana-samudyame (1.21, 1.22)","Arjuna said: O Acyuta (Immortal, Krsna), position my chariot between the\ntwo armies, that I may just see those who stand here desirous to fight, to\nknow with whom I must combat in this act of war."],
    "22" : ["arjuna uvaca\nsenayor ubhayor madhye ratham sthapaya me \'cyuta\nyavad etan nirikse \'ham yod dhu-kaman avasthitan\nkair may a saha yoddhavyam asmin rana-samudyame (1.21, 1.22)","Arjuna said: O Acyuta (Immortal, Krsna), position my chariot between the\ntwo armies, that I may just see those who stand here desirous to fight, to\nknow with whom I must combat in this act of war."],
    "23" : ["yotsyamanan avekse \'ham ya ete \'tra samagatah\ndhartarastrasya durbuddher yuddhe priya-cikirsavah (1.23)","I wish to look upon those who are assembled here, and are about to engage\nin battle eager to service in conflict the evil-minded son of Dhritarashtra,\nachieving what he regards as best."],
    "24" : ["sanjaya uvaca\nevam ukto hrsikeso gudakesena bharata\nsenayor ubhayor madhye sthapayitva rathottamam (1.24)","Sanjaya said: In response to Gudakesa's (Arjuna) request, O Bharata\n(Dhrtardshtra), Hrslkesa stationed that finest among chariots between the\ntwo armies."],
    "25" : ["bhisma-drona-pramukhatah sarvesam ca mahi-ksitam\nuvaca partha pasyaitan samavetan kurun iti (1.25)","Confronting Bhisma and Drona and all the rulers of earth, he said: O\nPartha (Arjuna), look at these assembled Kurus."],
    "26" : ["tatrapasyat sthitan parthah pitrn atha pitamahan\nacaryan matulan bhratrn putran pautran sakhims tatha\nsvasuran suhrdas caiva nayor ubhayor api (1.26)","Then, the son of Partha (Arjuna) saw ranged there in both the armies\nfathers (paternal uncles), grandfathers, teachers, maternal uncles, brothers,\nsons, grandsons and comrades, father-in-laws and friends."],
    "27" : ["tan samiksya sa kaunteyah sarvan bandhun avasthitan\nkrpaya parayavisto visidann idam abravit (1.27)","When the son of Kunti (Arjuna) saw that all those standing there in the\nranks of the two armies were his kinsmen, he was overwhelmed with\ndeepest pity and consequently said in sorrow:"],
    "28" : ["arjuna uvaca\ndrstvemam sva janam krsna yuyutsum samupasthitam\nsidanti mama gatrani mukham ca parisusyati (1.28)","Arjuna said: Seeing these kinsmen, O Krsna, ranged, eager for combat, my\nlimbs fail, and my mouth is dried up,"],
    "29" : ["vepathus ca sarire me roma harsas ca jayate\ngandivam sramsate hastat tvak caiva paridahyate (1.29)","My body quivers and my hair stands on end.\nThe Gandlva (bow) slips from my hand, and my skin is terribly burning."],
    "30" : ["na ca saknomy avasthatum bhramativa ca me manah\nnimittani ca pasyami viparitani kesava (1.30)","I am not able to stand, and my mind is spiralling as it were.\nI see opposing omens, O Kesava (Krsna),"],
    "31" : ["na ca sreyo \'nupasyami hatva sva-janam ahave\nna kankse vijayam krsna na ca rajyam sukhani ca (1.31)","and do not see any good from\nkilling my kinsmen in battle. I do not wish victory, O Krsna, nor kingdoms or pleasures. What is the use\nto us in having a kingdom, O Govinda (Krsna), or amusement and even life."],
    "32" : ["kim no rajyena govinda kim bhogair jivitena va\nyesam arthe kanksitam no rajyam bhogah sukhani ca (1.32)","Those for whose sake we desire kingdom, enjoyments and pleasures stand\nhere for battle, having abandoned life and wealth;"],
    "33" : ["ta ime \'vasthita yuddhe pranams tyaktva dhanani ca\nacaryah pitarah putras tathaiva ca pitamahah (1.33)","Teachers, fathers (paternal uncles), sons and grandfathers, maternal uncles,\nfathers-in-law, grandsons, brothers-in-law and also (other) relatives."],
    "34" : ["matulah svasurah pautrah syalah sambandhinas tatha\netan na hantum icchami ghnato \'pi madhusudana (1.34)","These, I do not want to kill, O Slayer of Madhusudana (Krsna), though they\nwant to kill us, even for the sake to obtain the primacy over the three\nworlds; and much less for the sake of the earth!"],
    "35" : ["api trailokya-rajyasya hetoh kim nu mahi-krte\nnihatya dhartarastran nah ka pritih syaj janardana (1.35)","Killing these sons of Dhrtarashtra, what satisfaction can be ours,\nO Janardana (Maintainer of the people, Krsna)? On killing these offenders only\nsin will take hold of us."],
    "36" : ["papam evasrayed asman hatvaitan atatayinah\ntasman narha vayam hantum dhartarastran sa bandhavan\nsva janam hi katham hatva sukhinah syama madhava (1.36)","It is not correct to kill our own kinsmen, the sons of Dhrtarashtra, indeed,\nby killing our own people, how can we be happy, O Madhava (Krsna)?"],
    "37" : ["yady apy ete na pasyanti lobhopahata-cetasah\nkula-ksaya-krtam dosam mitra-drohe ca patakam (1.37)","Although these, their minds overpowered by greediness, perceive no guilt in\nthe extinction of the family and no sin in treachery to friends,"],
    "38" : ["katham na jneyam asmabhih papad asman nivartitum\nkula ksaya krtam dosam prapasyadbhir janardana (1.38)","Yet, O\nJanardana (Krsna); why should we not learn to retreat from this sin,\nperceiving the guilt in the destruction of the family?"],
    "39" : ["kula-ksaye pranasyanti kula-dharmah sanatanah\ndharme naste kulam krtsnam adharmo \'bhibhavaty uta (1.39)","In the annihilation of a family, the immemorial family traditions (dharmas) are destroyed, and when these disappear,\nlawlessness overtakes the whole family."],
    "40" : ["adharmabhibhavat krsna pradusyanti kula striyah\nsttisu dustasu varsneya jayate varna-sankarah (1.40)","When lawlessness prevails, O Krsna, the women of the family become corrupted;\nand when women grow corrupt, O descendant of Varsneya (Krsna), there will be caste -confusion;"],
    "41" : ["sankaro narakayaiva kula-ghnanam kulasya ca\npatanti pitaro hy esam lupta-pindodaka-kriyah (1.41)","And, the confusion of castes leads the family and those who have destroyed the families to hell.\nTheir forefathers fall as well (to hell),\ndeprived of their ritual offerings of rice-balls and water."],
    "42" : ["dosair etaih kula-ghnanam varna-sankara-karakaih\nutsadyante jati-dharmah kula-dharmas ca sasvatah (1.42)","By these evil deeds of those destroying the family, causing the fusion of castes (varna-samkara),\nthe eternal family traditions are devastated. "],
    "43" : ["utsanna-kula-dharmanam manusyanam janardana\nnarake niyatam vaso bhavatity anususruma (1.43)","We have heard, O Janardana (Krsna), that those whose family traditions\nhave been ruined dwell necessarily in hell."],
    "44" : ["aho bata mahat papam kartum vyavasita vayam\nyad rajya-sukha-lobhena hantum sva-janam udyatah (1.44)","Alas! We have determined to commit a great sin,\ninasmuch as we are attempting to kill our own kinsmen\nthrough greediness for the pleasures of supremacy."],
    "45" : ["yadi mam apratikaram asastram sastra-panayah\ndhartarastra rane hanyus tan me ksemataram bhavet (1.45)","It would be better for me, if the sons of Dhrtarashtra, weapons in hand,\nwere to slay me in combat, while being unarmed and unable to resist."],
    "46" : ["sanjaya uvaca\nevam uktvarjunah sankhye rathopastha upavisat\nvisrjya sa-saram capam soka-samvigna-manasah (1.46)","Having spoken as such, Arjuna sank down on the seat of his chariot,\ncasting away his bow and arrow, his mind distracted with grief."]
  },
  "2" : {
    "1" : ["sanjaya uvaca\ntarn tatha krpayavistam asru-purnakuleksanam\nvisidantam idam vakyam uvaca madhusudanah (2.1)", "Sanjaya said: To him who was in this way overwhelmed with compassion\nand affliction, whose eyes were distraught and filled with tears,\nMadhava (Krsna, the destroyer of Madhu), spoke these words: "],
    "2" : ["sri-bhagavan uvaca\nkutas tva kasmalam idam visame samupasthitam\nanarya-justam asvargyam akirti-karam Arjuna (2.2)", "The Supreme Lord said: From where has this dejection come into your mind in this perilous hour?\nThis is unknown to an Aryan, not leading to heaven but causing disgrace, O Arjuna."],
    "3" : ["klaibyam ma sma gamah Partha naitat tvayy upapadyate\nksudram hrdaya-daurbalyam tyaktvottistha Parantapa (2.3)", "O Partha (Arjuna), yield not to weakness: it does not befit you.\nCast off this vile faintheartedness and arise, Parantapa (Arjuna - Conqueror of foes)."],
    "4" : ["arjuna uvaca\nkatham bhismam aham sankhye dronam ca madhusudana\nisubhih pratiyotsyami pujarhav ari-sudana (2.4)", "Arjuna said: O Madhava (Krsna), how shall I attack with arrows in combat Bhisma and Drona,\nfor they are worthy of respect, O Arisudana (O slayer of foes, Krsna)!"],
    "5" : ["gurun ahatva hi mahanubhavan sreyo bhoktum bhaiksyam apiha loke\nhatvartha-kamams tu gurun ihaiva bhunjiya bhogan rudhira-pradigdhan (2.5)", "For better were it here in this world to eat a beggar's food rather than\nby killing these teachers of high honour. However, were I to kill them,\nI should only enjoy wealth and worldly pleasures tainted with blood."],
    "6" : ["na caitad vidmah kataran no gariyo yad va jayema yadi va no jayeyuh\nyan eva hatva na jijivisamas te 'vasthitah pramukhe dhartarastrah (2.6)", "We do not know which is the better alternative for us, to conquer them or\nthey conquer us. There facing us stand Dhrtarustra's sons,\nwhom having killed, we should not even care to live."],
    "7" : ["karpanya-dosopahata-svabhavah prcchami tvam dharma-sammudha-\ncetah yac chreyah syan niscitam bruhi tan\nme sisyaste 'ham sadhi mam tvam prapannam (2.7)", "My very being (svathdva) is stained by the harmful taint of feeble pity, and\nmy mind confounded about right and wrong (Dharma, Brahman who supports all).\nI ask you; tell me what is absolutely good. I am Your disciple,\nhaving surrendered myself to You, teach me for all my trust is in You."],
    "8" : ["na hi prapasyami mamapanudyad yac chokam ucchosanam indriyanam\navapya bhumav asapatnam rddham rajyam suranam api cadhipatyam (2.8)", "I see no means to dispel the sorrow which parches my senses,\neven after attaining unrivalled and prosperous kingdom on earth\nor even lordship over the gods themselves."],
    "9" : ["sanjaya uvaca\nevam uktva hrsikesam gudakesah parantapah\nna yotsya iti govindam uktva tusnim babhuva ha (2.9)", "Sanjaya said: Having spoken like this to Hrsikesa (Krsna),\nthe powerful Gudakesa, scorcher of the foe (Arjuna),\nfall silent, saying to Govinda (Krsna): 'I will not fight' and he held his peace."],
    "10" : ["tarn uvaca hrsikesah prahasann iva bharata\nsenayor ubhayor madhye visidantam idam vacah (2.10)", "To him who was grieving, sitting amidst of the two armies, O Bharata (Arjuna),\n Hrsikesa (Krsna) smiling as it were, spoke these words:"],
    "11" : ["sri-bhagavan uvaca\nasocyan anvasocas tvam prajna-vadams ca bhasase\ngatasun agatasums ca nanusocanti panditah (2.11)", "The Supreme Lord said: You mourn for those who deserve no grief, and yet\nyou speak words of wisdom. For the living or the dead wise men know no grief."],
    "12" : ["na tv evaham jatu nasam na tvam neme janadhipah\nna caiva na bhavisyamah sarve vayam atah param (2.12)", "Never did I not exist, nor you, nor these rulers of men;\nnor will there be a time in the future when we shall cease to exist."],
    "13" : ["dehino 'smin yatha dehe kaumaram yauvanam jara\ntatha dehantara-praptir dhiras tatra na muhyati (2.13)", "Just as in this bodily form the Self (Soul) experiences childhood, youth and old age,\nso does it pass into another body (after death). In this, a thoughtful person has no doubts."],
    "14" : ["matra-sparsas tu Kaunteya sitosna-sukha-duhkha-dah\nagamapayino 'nityas tams titiksasva Bharata (2.14)", "The sense-contacts, O son of Kunti (Arjuna), which give rise to heat and cold, pleasure and pain,\ncome and go, they are impermanent. Learn to endure them, O Bharata (Arjuna)."],
    "15" : ["yam hi na vyathayanty ete purusam purusarsabha\nsama-duhkha-sukham dhiram so 'mrtatvaya kalpate (2.15)", "It is the wise person who is not afflicted by them, who remains undaunted in pain and pleasure\n, who becomes fit to attain immortality, O chief among men (Arjuna)."],
    "16" : ["nasato vidyate bhavo nabhavo vidyate satah\nubhayor api drsto \'ntas tv anayos tattva-darsibhih (2.16)", "That which is real has no becoming, while the real never\nceases to be. Both of these have been perceived by the\nseers of the essence of things (Tattva)."],
    "17" : ["avinasi tu tad viddhi yena sarvam idam tatam\nvinasam avyayasyasya na kascit kartum arhati (2.17)", "But know \"That\" (Brahman - Tat tvam asi) is indestructible by which the whole (universe) is pervaded.\nNone can bring destruction of That, the Immutable."],
    "18" : ["antavanta ime deha nityasyoktah saririnah\nanasino prameyasya tasmad yudhyasva Bharata (2.18)", "It is said, that these (our) bodies, indwelt by the Eternal embodied (Soul, the Self) who is eternal, indestructible and unknowable, are finite. Therefore, fight, O Bharata (Arjuna)."],
    "19" : ["ya enam vetti hantaram yas cainam manyate hatam\nubhau tau na vijanito nayam hanti na hanyate (2.19)", "He who regards that He (the embodied soul) can be a slayer and he who\nthinks he is slain, both of them are ignorant. She slays not, nor is she slain."],
    "20" : ["na jay ate mriyate va kadacin nayam bhutva bhavita va na bhuyah\najo nityah sasvato 'yam purano na hanyate hanyamane sarire (2.20)", "He is not born, nor does He ever die. Never did He come to be, nor will he\never come to be again. Unborn, eternal, immutable and primeval, He is not\nslain when the body is slain."],
    "21" : ["vedavinasinam nityam ya enam ajam avyayam\nkatham sa purusah Partha kam ghatayati hanti kam (2.21)", "The one who knows Him to be indestructible, eternal, unborn and\nimmutable, how can that man slay, or cause to be slain, O Partha (Arjuna)!"],
    "22" : ["vasamsi jirnani yatha vihaya navani grhnati naro 'parani\ntatha sarirani vihaya jirnany anyani samyati navani dehi (2.22)", "Just as a man casts off his worn-out clothes, and puts on other new ones, so\nthe embodied (Soul, Self) casts off his worn-out bodies and enters others,\nnew ones."],
    "23" : ["nainam chindanti sastrani nainam dahati pavakah\nna cainam kledayanty apo na sosayati marutah (2.23)", "He (the embodied soul) cannot be cut by weapons, nor burnt by fire, nor\nwaters wet him, nor the wind dry him up."],
    "24" : ["acchedyo 'yam adahyo 'yam akledyo 'sosya eva ca\nnityah sarva-gatah sthanur acalo 'yam sanatanah (2.24)", "He is uncleavable, unburnable, unwettable, and undryable. He is\neverlasting, all-pervading, stable, firm, and everlasting."],
    "25" : ["avyakto 'yam acintyo 'yam avikaryo 'yam ucyate\ntasmad evam viditvainam nanusocitum arhasi (2.25)", "It is said, that He is unmanifest, unthinkable and unchanging. Therefore,\nknowing He to be so, put away your useless sadness."],
    "26" : ["atha cainam nitya-jatam nityam va manyase mrtam\ntathapi tvam maha-baho nainam socitum arhasi (2.26)", "Even if you believe He is constantly born and constantly dies, even so, O\nmighty-armed (Arjuna), you should not mourn."],
    "27" : ["jatasya hi dhruvo mrtyur dhruvam janma mrtasya ca\ntasmad apariharye 'rthe na tvam socitum arhasi (2.27)", "To that which is born, death is certain; and to one that dies, birth is certain.\nTherefore, this being unavoidable, you have no cause to mourn."],
    "28" : ["avyaktadini bhutani vyakta-madhyani bharata\navyakta-nidhanany eva tatra ka paridevana (2.28)", "O Bharata (Arjuna), unseen are the beginnings of beings, their middle\ncourse seen, and their end unseen again. So, what is there to mourn over?"],
    "29" : ["ascarya-vat pasyati kascid enam ascarya-vad vadati tathaiva canyah\nascarya-vac cainam anyah srnoti srutvapy enam veda na caiva kascit (2.29)", "As a rare privilege may someone see Him, and also by rare privilege may\nanother speak of Him, and as a rare privilege may still another hear Him.\nBut even after all this, none understands Him at all."],
    "30" : ["dehi nityam avadhyo 'yam dehe sarvasya bharata\ntasmat sarvani bhutani na tvam socitum arhasi (2.30)", "He, the embodied (Soul, Self) in every one's body can never be slain,\nO Bharata (Arjuna). Therefore, it is not proper for you to mourn about any\ncreature."],
    "31" : ["sva-dharmam api caveksya na vikampitum arhasi\ndharmyad dhi yuddhac chreyo 'nyat ksatriyasya na vidyate (2.31)", "Considering your own (caste) duty (dharma), you should not hesitate. For\nthere is nothing more meritorious for a Ksatriya that a dutiful war."],
    "32" : ["yadrcchaya copapannam svarga-dvaram apavrtam\nsukhinah ksatriyah Partha labhante yuddham idrsam (2.32)", "Providential for those Ksatriyas, O Partha, becoming involved in a war like\nthis, presented by pure chance, like an open door to heaven."],
    "33" : ["atha cet tvam imam dharmyam sangramam na karisyasi\ntatah sva-dharmam kirtim ca hitva papam avapsyasi (2.33)", "But if you will not fight this righteous battle, then, abandoning your own\nduty (dharma) and honour, you will incur sin."],
    "34" : ["akirtim capi bhutani kathayisyanti te 'vyayam\nsambhavitasya cakirtir maranad atiricyate (2.34)", "People also will always relate your dishonour; and, to one who has been\nhighly honoured, dishonour is more than death."],
    "35" : ["bhayad ranad uparatam mamsyante tvam maha-rathah\nyesam ca tvam bahu-mato bhutva yasyasi laghavam (2.35)", "The great chariot-warriors will think that fear withdrew you from the\nbattle; and, though greatly honoured by them before, you will incur their\ncontempt."],
    "36" : ["avacya-vadams ca bahun vadisyanti tavahitah\nnindantas tava samarthyam tato duhkhataram nu kim (2.36)", "Your enemies, also, scorning your strength, will talk many abusive words.\nCan there be anything more painful than that?"],
    "37" : ["hato va prapsyasi svargam jitva va bhoksyase mahim\ntasmad uttistha Kaunteya yuddhaya krta-niscayah (2.37)", "Killed, you will attain heaven; victorious, you will enjoy the earth.\nTherefore, O son of Kunti (O Kaunteya, Arjuna), arise, determined to fight."],
    "38" : ["sukha-duhkhe same krtva labhalabhau jayajayau\ntato yuddhaya yujyasva naivam papam avapsyasi (2.38)", "Take as equal pleasure and pain, gain and loss, victory and defeat; prepare\nyourself for battle {your duty). In so doing you will bring no evil to yourself."],
    "39" : ["esa te 'bhihita sankhye buddhir yoge tv imam srnu\nbuddhya yukto yaya Partha karma-bandham prahasyasi (2.39)", "This, the wisdom that has been taught to you is Sankhya (knowledge). Now\nlisten to the wisdom of Karma-yoga, which possessing, O Partha (Arjuna),\nyou shall cast off the bondage of action."],
    "40" : ["nehabhikrama-naso 'sti pratyavayo na vidyate\nsv-alpam apy asya dharmasya trayate mahato bhayat (2.40)", "In this there is no loss of effort, or even harm. Even a little of this discipline\n(dharma) protects one from great fear."],
    "41" : ["vyavasayatmika buddhir ekeha kuru-nandana\nbahu-sakha hy anantas ca buddhayo 'vyavasayinam (2.41)", "Here, O Son of Kuru (Arjuna), the essence of the soul (buddhi) is will\n(vyavasdya). Many-branched and endless are the indecisive devoid of will."],
    "42" : ["yam imam puspitam vacam pravadanty avipascitah\nveda-vada-ratah Partha nanyad astiti vadinah (2.42)", "There are those who have no vision, whose minds are seduced by ornate\nwords, rejoicing in the letter of the Vedas, O Partha (Arjuna), and they say:\n'There is nothing but this.'"],
    "43" : ["kamatmanah svarga-para janma-karma-phala-pradam\nkriya-visesa-bahulam bhogaisvarya-gatim prati (2.43)", "They are wrapped with selfish desires, and regard the attainment of heaven\nas their highest goal. They hold to specific rites whose fruit is rebirth, and\nthe attainment of pleasure and power."],
    "44" : ["bhogaisvarya-prasaktanam ta yapahrta-cetasam\nvyavasayatmika buddhih samadhau na vidhiyate (2.44)", "For them who are attached to pleasure and power, and whose minds are\ncarried away by such teaching, they have not the determination ever to\nattain Samadhi (the third state of consciousness in meditation)."],
    "45" : ["trai-gunya-visaya veda nistrai-gunyo bhavarjuna\nnirdvandvo nitya-sattva-stho niryoga-ksema atmavan (2.45)", "The Vedas cover the three Gunas of Nature. Be, O Arjuna, above the three\nGunas, free from pairs of opposites {dualities), unconcerned with\nacquisition and preservation, always firm in goodness, and centered in the Self."],
    "46" : ["yavan artha udapane sarvatah samplutodake\ntavan sarvesu vedesu brahmanasya vijanatah (2.46)", "Just as a reservoir is of little use by the side of an all -spreading flood of\nwater, the same there is in all Vedas for an enlightened Brahmana."],
    "47" : ["karmany evadhikaras te ma phalesu kadacana\nma karma-phala-hetur bhur ma te sango 'stv akarmani (2.47)", "Your concern is with the respective action alone; its fruits are never within\nyour control. So, let not the fruit of action be your motive, nor let your\nattachment be the non-performance of action."],
    "48" : ["yoga-sthah kuru karmani sangam tyaktva dhananjaya\nsiddhy-asiddhyoh samo bhutva samatvam yoga ucyate (2.48)", "O Dhannanjaya (Arjuna), steadfast in devotion perform your action, casting\noff attachment, remaining the same in success and failure. Equilibrium is\ncalled yoga (Karma-yoga)."],
    "49" : ["durena hy avaram karma buddhi-yogad dhananjaya\nbuddhau saranam anviccha krpanah phala-hetavah (2.49)", "Truly, mere action is far inferior to devotion in wisdom (buddhi-yoga). O\nDhananjaya (Arjuna), take refuge in wisdom (buddhi). Piteous are they\nwhose motive is in the fruit (of action)."],
    "50" : ["buddhi-yukto jahatiha ubhe sukrta-duskrte\ntasmad yogaya yujyasva yogah karmasu kausalam (2.50)", "He, who is fixed in wisdom, discards both good and evil works. Therefore,\ntake refuge in yoga (spiritual discipline on the way of oneness with the\nSupreme Being). Yoga is skill in action."],
    "51" : ["karma-jam buddhi-yukta hi phalam tyaktva manisinah\njanma-bandha-vinirmuktah padam gacchanty anamayam (2.51)", "For those wise men united in wisdom, having renounced the fruit of action,\nliberated from the bonds of birth, they go to that region that knows no ill."],
    "52" : ["yada te moha-kalilam buddhir vyatitarisyati\ntada gantasi nirvedam srotavyasya srutasya ca (2.52)", "When your mind shall pass beyond the veil of delusion, then you will rise to\nindifference to what has been heard, and what is yet to be heard."],
    "53" : ["sruti-vipratipanna te yada sthasyati niscala\nsamadhav acala buddhis tada yogam avapsyasi (2.53)", "When the mind, bewildered by the Scriptures (sruti), stands motionless and\nstill, fixed in contemplation (Samddhi), then you will attain Yoga (union\nwith the divine will)."],
    "54" : ["arjuna uvaca\nsthita-prajnasya ka bhasa samadhi-sthasya kesava\nsthita-dhih kim prabhaseta kim asita vrajeta kim (2.54)", "Arjuna said: O Kesava (Krsna), what is the mark of the man of steady\nwisdom (knowledge), who is constant in contemplation? How does the man\nof steady knowledge speak, sit and walk?"],
    "55" : ["sri-bhagavan uvaca\nprajahati yada Kaman sarvan partha mano-gatan\natmany evatmana tustah. sthita-prajnas tadocyate (2.55)", "The Supreme Lord said: O Partha (Arjuna), when a man has abandoned all\nthe desires of the mind, contented in the Self alone, then is he called a man\nof steady knowledge."],
    "56" : ["duhkhesv anudvigna-manah sukhesu vigata-sprhah\nvita-raga-bhaya-krodhah sthita-dhir munir ucyate (2.56)", "He whose mind is undismayed in calamities, free from longing for\npleasures, from whom passion (rdga), fear and anger have fled, such a man\nis called a sage of steady mind."],
    "57" : ["yah sarvatranabhisnehas tat tat prapya subhasubham\nnabhinandati na dvesti tasya prajna pratisthita (2.57)", "Who has no attachment for any thing, who rejoices not at whatever good is\nhappening to him, nor hates the bad coming his way, such a one is firmly\nestablished in knowledge."],
    "58" : ["yada samharate cayam kurmo 'nganiva sarvasah\nindriyanindriyarthebhyas tasya prajna pratisthita (2.58)", "When a person completely withdraws his senses from the objects of sense,\nas the tortoise withdraws its limbs from all sides, such a one is firmly\nestablished in knowledge."],
    "59" : ["visaya vinivartante niraharasya dehinah\nrasa-varjam raso 'py asya param drstva nivartate (2.59)", "The objects of sense abandon the abstinent man, but not the longing for\nthem. But this relish vanishes at the vision of the Supreme Being."],
    "60" : ["yatato hy api Kaunteya purusasya vipascitah\nindriyani pramathini haranti prasabham manah (2.60)", "O son of Kunti (Kaunteya, Arjuna), the turbulent senses of even a wise man,\nthough he be striving, seduce forcibly his mind."],
    "61" : ["tani sarvani samyamya yukta asita mat-parah\nvase hi yasyendriyani tasya prajna pratisthita (2.61)", "Having restrained them all, a man should remain steadfast, with intent on\nMe alone. He whose senses are so controlled is steady in knowledge."],
    "62" : ["dhyayato visayan pumsah sangas tesupajayate\nsangat sanjayate kamah kamat krodho 'bhijayate (2.62)", "When a man thinks of objects of sense develops attachment to them. From\nattachment arises desire, and desire results in anger."],
    "63" : ["krodhad bhavati sammohah sammohat smrti-vibhramah\nsmrti-bhramsad buddhi-naso buddhi-nasat pranasyati (2.63)", "From anger comes bewilderment; from bewilderment confused memory.\nConfused memory destroys the conscience, and once his conscience is\ndestroyed, he perishes."],
    "64" : ["raga-dvesa-vimuktais tu visayan indriyais caran\natma-vasyair vidheyatma prasadam adhigacchati (2.64)", "He attains peace, who, disciplined, approaches objects with the senses\ndevoid of attraction and repulsion, and brought under his self-control."],
    "65" : ["prasade sarva-duhkhanam hanir asyopajayate\nprasanna-cetaso hy asu buddhih paryavatisthate (2.65)", "In peace, all misery has come to an end, for of him whose heart is tranquil,\nthe mind soon becomes steady."],
    "66" : ["nasti buddhir ayuktasya na cayuktasya bhavana\nna cabhavayatah santir asantasya kutah sukham (2.66)", "There is no pure knowledge for the unsteady, nor for the unsteady\nconcentration, and for him without concentration there is no peace, and for\nthe peaceless how can there be happiness?"],
    "67" : ["indriyanam hi caratam yan mano 'nuvidhiyate\ntad asya harati prajnam vayur navam ivambhasi (2.67)", "Hither and thither the senses rove, and when the mind is attuned to them,\nsweeps away his knowledge, just as the wind carries away a ship upon the\nwaters."],
    "68" : ["tasmad yasya maha-baho nigrhitani sarvasah\nindriyanindriyarthebhyas tasya prajna pratisthita (2.68)", "Therefore, O Mighty-armed (Arjuna), he whose senses are restrained from\nthe objects of sense, of him his knowledge is steady."],
    "69" : ["ya nisa sarva-bhutanam tasyam jagarti samyami\nyasyam jagrati bhutani sa nisa pasyato muneh (2.69)", "In what for other beings is night, for the disciplined man is the time of\nwaking. When all beings are awake, then it is night for the Sage who sees."],
    "70" : ["apuryamanam acala-pratistham samudram apah pravisanti yadvat\ntadvat kama yam pravisanti sarve sa santim apnoti na kama-kami (2.70)", "He attains peace, into whom all desires flow as waters flow into the ocean,\nwhich, filled from all sides, remains unmoving in its depths, but not the\ndesirer of desires."],
    "71" : ["vihaya kaman yah sarvan pumams carati nihsprhah\nnirmamo nirahankarah sa santim adhigacchati (2.71)", "That man attains peace who puts off all desires and goes about without\nattachment, selfishness and self-importance."],
    "72" : ["esa brahmi sthitih Partha nainam prapya vimuhyati\nsthitvasyam anta-kale 'pi brahma-nirvanam rcchati (2.72)", "O Partha (Arjuna), this is the Brahmic state. Having attained to this, none is\nbewildered. Remaining in this state even at the time of death, one attains\nBrahma-nirvana."]
  },
  "3" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""],
    "43" : ["", ""]
  },
  "4" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""]
  },
  "5" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""]
  },
  "6" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""],
    "43" : ["", ""],
    "44" : ["", ""],
    "45" : ["", ""],
    "46" : ["", ""],
    "47" : ["", ""]
  },
  "7" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""]
  },
  "8" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""]
  },
  "9" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""]
  },
  "10" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""]
  },
  "11" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""],
    "43" : ["", ""],
    "44" : ["", ""],
    "45" : ["", ""],
    "46" : ["", ""],
    "47" : ["", ""],
    "48" : ["", ""],
    "49" : ["", ""],
    "50" : ["", ""],
    "51" : ["", ""],
    "52" : ["", ""],
    "53" : ["", ""],
    "54" : ["", ""],
    "55" : ["", ""]
  },
  "12" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""]
  },
  "13" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""]
  },
  "14" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""]
  },
  "15" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""]
  },
  "16" : {
    "1" : ["sri-bhagavan uvaca\nabhayam sattva-samsuddhir jnana-yoga-vyavasthitih\ndanam damas ca yajnas ca svadhyayas tapa arjavam (16.01)", "The Supreme Lord said: Fearlessness and purity of heart, steadfastness in\nthe yoga of knowledge, open-handed and sense-restraint, performing of\nsacrifice (Yajna), intent on the study of scriptures, austerity and integrity."],
    "2" : ["ahimsa satyam akrodhas tyagah santir apaisunam\ndaya bhutesv aloluptvam mardavam hrir acapalam (16.02)", "Non-violence, truthfulness, absence of anger, renunciation, peacefulness,\naverse to calumny, compassion to living beings, freedom from greed,\nmildness, modesty, absence of fickleness."],
    "3" : ["tejah ksama dhrtih saucam adroho nati-manita\nbhavanti sampadam daivim abhijatasya bharata (16.03)", "Vigour, mercy, fortitude, purity, absence of hatred and arrogance - these\nare his who is born to the godlike portion, O Bharata (Arjuna)."],
    "4" : ["dambho darpo 'bhimanas ca krodhah parusyam eva ca\najnanam cabhijatasya partha sampadam asurim (16.04)", "Hypocrisy, arrogance, excessive pride, anger and also cruelty and ignorance\nare his who is born to the demoniac portion (Asuric; the Asuras were the\nenemies of the Suras or Deities), O Partha {Arjuna)"],
    "5" : ["daivi sampad vimoksaya nibandhayasuri mata\nma sucah sampadam daivim abhijato 'si Pandava (16.05)", "The godlike portion is deemed for deliverance, and the demoniac for\nbondage. But grieve not, O Pandava (Arjuna)\ You are born to a godlike\ndestiny."],
    "6" : ["dvau bhuta-sargau loke 'smin daiva asura eva ca\ndaivo vistarasah prokta asuram partha me srnu (16.06)", "Basically, there are two orders of contingent beings in this world, the godly\nand the demoniac. Of the godly I have discoursed at length, now hear from\nMe, O Partha {Arjuna), about the demoniac."],
    "7" : ["pravrttim ca nivrttim ca jana na vidur asurah\nna saucam napi cacaro na satyam tesu vidyate (16.07)", "Those of demoniac nature know not of creative action (pravrtti) or of right\nabstinence (cessation, nivritti); nor purity, nor good conduct, nor truth are\nfound in them."],
    "8" : ["asatyam apratistham te jagad ahur anisvaram\naparaspara-sambhutam kim anyat kama-haitukam (16.08)", "The world, they say, is without truth, without firm foundation, without a\nGod, not ruled by mutual law, driven only by lust (desire), and nothing else."],
    "9" : ["etam drstim avastabhya nastatmano 'lpa-buddhayah\nprabhavanty ugra-karmanah ksayaya jagato 'hitah (16.09)", "Holding fast to these views, these lost souls (atman) with small intellects they\nembark on cruel and violent deeds, come forth as enemies for the\ndestruction of the world."],
    "10" : ["kamam asritya duspuram dambha-mana-madanvitah\nmohad grhitvasad-grahan pravartante 'suci-vratah (16.10)", "Surrendering themselves in insatiable sensual desire, full of hypocrisy,\npride and arrogance, holding evil thoughts through delusion, they act with\nimpure resolves."],
    "11" : ["cintam aparimeyam ca pralayantam upasritah\nkamopabhoga-parama etavad iti niscitah (16.11)", "Preoccupied with limitless imaginings right up to the time of death, they\nyield themselves at nothing but to satisfy their lusts, convinced that this is\nall."],
    "12" : ["asa-pasa-satair baddhah kama-krodha-parayanah\nihante kama-bhogartham anyayenartha-sancayan (16.12)", "Bound by a hundred ties of hope, obsessed by anger and desire, they aspire\nunjustly to accumulate hoards of wealth, to satisfy their sensual\nenjoyments."],
    "13" : ["idam adya maya labdham imam prapsye manoratham\nidam astidam api me bhavisyati punar dhanam (16.13)", "'This I have gained today; this desire I shall gratify; this wealth is mine,\nand much more too will be mine as time goes on.'"],
    "14" : ["asau maya hatah satrur hanisye caparan api\nisvaro 'ham aham bhogi siddho 'ham balavan sukhi (16.14)", "'I have killed this enemy and many another too I will kill. I am a lord, I\ntake my pleasure; I am powerful, happy and successful.'"],
    "15" : ["adhyo 'bhijanavan asmi ko 'nyo 'ti sadrso maya\nyaksye dasyami modisya ity ajnana-vimohitah (16.15)", "'I am rich and of a good family. Who else can equal himself with me? I will\nsacrifice, I will give alms, I will rejoice.' So speaks the deluded in his\nignorance."],
    "16" : ["aneka-citta-vibhranta moha-jala-samavrtah\nprasaktah kama-bhogesu patanti narake 'sucau (16.16)", "Bewildered by all kinds of thoughts, caught up in delusion's web, obsessed\nin satisfying sensual enjoyment, they fall into the foul hell."],
    "17" : ["atma-sambhavitah stabdha dhana-mana-madanvitah\nyajante nama-yajnais te dambhenavidhi-purvakam (16.17)", "Puffed up with self-conceit, stubborn, maddened by their pride of wealth\n(or, filled with madness and intoxication of wealth), they make a show of\nperforming, lip -sacrifices only for pretension, and not in the prescribed\nway."],
    "18" : ["ahankaram balam darpam kamam krodham ca samsritah\nmam atma-para-dehesu pradvisanto 'bhyasuyakah (16.18)", "Given over to selfishness, force and pride, lust and anger, these malicious\nones hate Me who dwell in their bodies as I dwell in all."],
    "19" : ["tan aham dvisatah kruran samsaresu naradhaman\nksioamy ajashram asubhan asurisv eva yonisu (16.19)", "These barbarous haters, cruel, evil, the vilest among men in the world, I\never cast them down into demoniac wombs."],
    "20" : ["asurim yonim apanna mudha janmani janmani\nmam aprapyaiva Kaunteya tato yanty adhamam gatim (16.20)", "Caught up in demoniac wombs, birth after birth deluded, they never reach\nMe, O son of Kunti {Kaunteya, Arjuna), and so they tread the lowest path."],
    "21" : ["tri-vidham narakasyedam dvaram nasanam atmanah\nkamah krodhas tatha lobhas tasmad etat trayam tyajet (16.21)", "Triple is the gate of this hell, destructive of the self: lust, anger, and greed.\nTherefore, avoid these three."],
    "22" : ["etair vimuktah Kaunteya tamo-dvarais tribhir narah\nacaraty atmanah sreyas tato yati param gatim (16.22)", "Once a man is freed from these three gates of darkness, O son of Kunti\n(Kaunteya, Arjuna), then can he work for self s salvation (sreyas), and\nthereby treading the Supreme Goal."],
    "23" : ["yah sastra-vidhim utsrjya vartate kama-karatah\nna sa siddhim avapnoti na sukham na param gatim (16.23)", "He, who forsakes the ordinances of scripture, and lives in the promptings of\nhis own desires, attains not perfection, finding no comfort (sukha), nor the\nSupreme Goal."],
    "24" : ["tasmac chastram pramanam te karyakarya-vyavasthitau\njnatva sastra-vidhanoktam karma kartum iharhasi (16.24)", "Therefore, let the scripture be your authority, determining what is right\nand wrong. Once you know what the ordinance of scripture bids you to do,\nyou should act accordingly in this world."]
  },
  "17" : {
    "1" : ["arjuna uvaca\nye sastra-vidhim utsrjya yajante sraddhayanvitah\ntesam nistha tu ka Krsna sattvam aho rajas tamah (17.01)", "Arjuna said: Those who forsake the ordinances of the Sastras (scriptures),\nand offer sacrifices full of faith (Sraddha), where do they stand, O Krsna? Is\nit one of goodness (Sattva, Sdttvika), passion (Rajas, Rdjasika), ignorance\n(Tamas, Tdmasika, darkness)? (The three qualities or attributes, Sattva,\nRajas, Tamas are used here in their moral correspondences.)"],
    "2" : ["sri-bhagavan uvaca\ntri-vidha bhavati Sraddha dehinam sa svabhava-ja\nsattviki rajasi caiva tamasi ceti tarn srnu (17.02)", "The Supreme Lord said: Threefold is the faith (Sraddha) of embodied souls,\nalong one's own inner character, either of goodness (Sdttvic), of passion\n(Rdjasic), and of ignorance (Tdmasic). Hear now to this."],
    "3" : ["sattvanurupa sarvasya sraddha bhavati bharata\nsraddha-mayo 'yam puruso yo yac-chraddhah sa eva sah (17.03)", "(Arjuna). Man is instinct with faith (Sraddha) (that is, the man 's faith shows\nwhat his character is): as his faith is, so is he."],
    "4" : ["yajante sattvika devan yaksa-raksamsi rajasah\npretan bhuta-ganams canye yajante tamasa janah (17.04)", "The Sattvika ones (those of goodness) offer sacrifice (worship) to the Gods;\nthe Rajasika (those of passion) to the gnomes and giants (the Yakshas and the\nRakshasas, the minor gods and demons)', while the others, the Tamasika ones\n(the ignorant, or those of darkness) sacrifice to the ghosts (Pretas) and the\nassembled spirits of the dead (Bhutas). (Pretas, ghosts, are departed beings,\nwhile Bhutas, nature -spirits)"],
    "5" : ["asastra-vihitam ghoram tapyante ye tapo janah\ndambhahankara-samyuktah kama-raga-balanvitah (17.05)", "They who perform fierce austerities without regard to scripture's words,\ngiven to hypocrisy and egotism, yielding to the violence of their passion and\ndesire."],
    "6" : ["karsayantah sarira-stham bhuta-gramam acetasah\nmam caivantah sarira-stham tan viddhy asura-niscayan (17.06)", "Foolishly tormenting their bodily organs, and Me also, who dwell within the\nbody, know these to be of demoniac resolve."],
    "7" : ["aharas tv api sarvasya tri-vidho bhavati priyah\nyajnas tapas tatha danam tesam bhedam imam srnu (17.07)", "The food also which is dear to all is threefold, as also Yajna (sacrifice),\npenance (ascetic practice, austerities) and the gift of alms. Listen to the\ndifference between them."],
    "8" : ["ayuh-sattva-balarogya- sukha-priti vivardhanah\nrasyah snigdhah sthira hrdya aharah sattvika-priyah (17.08)", "The foods that augment a fuller life, strength, health, vitality (Sattva),\npleasure and good feeling, foods that are savoury, mild, strengthening,\nvigorous, are dear to the Sattivika (those in the mode of goodness)."],
    "9" : ["katv-amla-lavanaty-usna- tiksna-ruksa-vidahinah\nahara rajasasyesta duhkha-sokamaya-pradah (17.09)", "The food that are bitter, sour, salty, over-hot, pungent, dry and burning,\nare the victuals dear to the Rajasika {those in the mode of passion), and bring\npain, sorrow and sickness."],
    "10" : ["yata-yamam gata-rasam puti paryusitam ca yat\nucchistam api camedhyam bhojanam tamasa-priyam (17.10)", "Whatever foods are stale and tasteless, rotten and decayed, things that are\nleavings and unclean are the choice of the Tamasika {those in the mode of\nignorance, darkness)."],
    "11" : ["aphalakanksibhir yajno vidhi-disto ya ijyate\nyastavyam eveti manah samadhaya sa sattvikah (17.11)", "The Yajna (sacrifice, service, seva, meritorious deeds, a Vedic rite) approved\nby holy ordinance, and offered by those who would not taste its fruits, who\nconcentrate their minds on the next alone: the firm belief that Yajna\n(sacrifice, etc..) is duty, that is Sattvic (in the mode of goodness). "],
    "12" : ["abhisandhaya tu phalam dambhartham api caiva yat\nijyate bharata-srestha tarn yajnam viddhi rajas am (17.12)", "The sacrifice that is offered up by those who bear its fruits in mind, and for\nmere pretension, O best of the Bharatas (Arjuna), know them to be the\nRajasic (in the mode of passion)."],
    "13" : ["vidhi-hinam asrstannam mantra-hinam adaksinam\nsraddha-virahitam yajnam tamasam paricaksate (17.13)", "Yajna (sacrifice, etc..) contrary to proper ritual ordinances, in which no\nfood is distributed (prasadam), no sacred words recited (mantras chanted or\nrecited), no Brahman's fees paid up (covering gifts to the officiating priests),\nno faith (Sraddha) enshrined, is said to be Tamasic (in the mode of ignorance,\ndarkness). "],
    "14" : ["deva-dvija-guru-prajna- pujanam saucam ariavam\nbrahmacaryam ahimsa ca sariram tapa ucyate (17.14)", "Worship given to the Gods, to the twice-born, gurus (spiritual teachers), and\nthe wise (the learned), purity, integrity, continence (celibacy even in\nmarriage, chastity), non-violence (harmlessness), are described as bodily\npenance."],
    "15" : ["anudvega-karam vakyam satyam priya-hitam ca yat\nsvadhyayabhyasanam caiva van-mayam tapa ucyate (17.15)", "Words that do not cause offence, that are truthful, pleasant and beneficial,\nand also the practice of sacred recitation, are termed the penance of the\ntongue (or, the word)."],
    "16" : ["manah-prasadah saumyatvam maunam atma-vinigrahah\nbhava-samsuddhir ity etat tapo manasam ucyate (17.16)", "Serenity of mind and friendliness, silence and self-control, and purity of\nfeelings (bldva), this is called the penance of the mind."],
    "17" : ["sraddhaya paraya taptam tapas tat tri-vidham naraih\naphalakanksibhir yuktaih sattvikam paricaksate (17.17)", "These threefold forms of penance, practised by men with utmost faith\n(Sraddha), desiring no fruit, with a mind in total control, are described as\nSattvika (in the mode of goodness)."],
    "18" : ["satkara-mana-pujartham tapo dambhena caiva yat\nkriyate tad iha proktam rajasam calam adhruvam (17.18)", "These penances which is practised with the view of obtaining respect,\nhonour and reverence, or from sheer hypocrisy, are here said to be Rajasic\n(in the mode of passion), unstable and transient."],
    "19" : ["mudha-grahenatmano yat pidaya kriyate tapah\nparasyotsadanartham va tat tamasam udahrtam (17.19)", "These penances performed out of perverted theories, through self-torture,\nor with the object of hurting others, is declared to be Tamasic (in the mode\nof ignorance)."],
    "20" : ["data vy am iti yad danam diyate 'nupakarine\ndese kale ca patre ca tad danam sattvikam smrtam (17.20)", "Alms given to one from whom no favour is expected in return, in the belief\nthat it is one's sacred duty to give, at the right place and time, to a worthy\nperson, is called alms given in a Sattvic way (in the mode of goodness)."],
    "21" : ["yat tu Pratyupakarartham phalam uddisya va punah\ndiyate ca pariklistam tad danam rajasam smrtam (17.21)", "But alms given in expectation of receiving favours in return, or for the sake\nof reaping some fruit afterwards, or again reluctantly, that giving is held to\nbe Rajasic (in the mode of passion)."],
    "22" : ["adesa-kale yad danam apatrebhyas ca diyate\nasat-krtam avajnatam- tat tamasam udahrtam (17.22)", "Alms given at the wrong place and time, to unworthy persons, without\nrespect or with insult that is declared to be Tamasic (in the mode of\nignorance)."],
    "23" : ["om tat sad iti nirdeso brahmanas tri-vidhah smrtah\nbrahmanas tena vedas ca yajnas ca vihitah pura (17.23)", "'Om, Tat, Sat': This has been considered as a threefold pointer to\nBrahman {Eternal Being). Through this, were created, in the beginning, the\nBrahmanas {the knowers of Brahman, or the priests, or intellectual class of\nIndia), and Vedas and Yajnas {sacrificial rites) ordained."],
    "24" : ["tasmad om ity udahrtya yajna-dana-tapah-kriyah\npravartante vidhanoktah satatam brahma-vadinam (17.24)", "Therefore, by uttering 'Om', are the acts of sacrifice, the giving of alms\nand penance accomplished, in conformity to ordinances {Vedic scriptures),\never again enacted by Brahman's devotees."],
    "25" : ["tad ity anabhisandhaya phalam yajna-tapah-kriyah\ndana-kriyas ca vividhah kriyante moksa-kanksibhih (17.25)", "With the utterance of 'Tat' (That), do those who seek liberation (Moksa,\nNirvana, Mukti), perform the various acts of sacrifice, penance and the gift\nof alms, having no thought for the fruits they produce."],
    "26" : ["sad-bhave sadhu-bhave ca sad ity etat prayujyate\nprasaste karmani tatha sac-chabdah partha yujyate (17.26)", "'Sat' (It Is) is used to indicate the Real and the Good; the word 'Sat' is\nlikewise used, O Partha (Arjuna), for works that call forth praise."],
    "27" : ["yajne tapasi dane ca sthitih sad iti co' cyate\nkarma caiva tad-arthiyam sad ity evabhidhiyate (17.27)", "Steadfastness in sacrifice, penance, the giving of alms, is also called 'Sat',\nand any action for the sake of the Supreme (Tat) is equally known as 'Sat'."],
    "28" : ["asraddhaya hutam dattam tapas taptam krtam ca yat\nasad ity ucyate Partha na ca tat pretya no iha (17.28)", "Whatever is sacrificed, any giving, any penance, or any other deed,\npractised without faith (Sraddhd), it is called 'Asat', O Partha (Arjuna); of\nno benefit in this world and the next (both in this life and the next)."]
  },
  "18" : {
    "1" : ["", ""],
    "2" : ["", ""],
    "3" : ["", ""],
    "4" : ["", ""],
    "5" : ["", ""],
    "6" : ["", ""],
    "7" : ["", ""],
    "8" : ["", ""],
    "9" : ["", ""],
    "10" : ["", ""],
    "11" : ["", ""],
    "12" : ["", ""],
    "13" : ["", ""],
    "14" : ["", ""],
    "15" : ["", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""],
    "43" : ["", ""],
    "44" : ["", ""],
    "45" : ["", ""],
    "46" : ["", ""],
    "47" : ["", ""],
    "48" : ["", ""],
    "49" : ["", ""],
    "50" : ["", ""],
    "51" : ["", ""],
    "52" : ["", ""],
    "53" : ["", ""],
    "54" : ["", ""],
    "55" : ["", ""],
    "56" : ["", ""],
    "57" : ["", ""],
    "58" : ["", ""],
    "59" : ["", ""],
    "60" : ["", ""],
    "61" : ["", ""],
    "62" : ["", ""],
    "63" : ["", ""],
    "64" : ["", ""],
    "65" : ["", ""],
    "66" : ["", ""],
    "67" : ["", ""],
    "68" : ["", ""],
    "69" : ["", ""],
    "70" : ["", ""],
    "71" : ["", ""],
    "72" : ["", ""],
    "73" : ["", ""],
    "74" : ["", ""],
    "75" : ["", ""],
    "76" : ["", ""],
    "77" : ["", ""],
    "78" : ["", ""]
  }
}
