// fullGita.js
// This file holds the entire dictionary representation of the Bhagavad Gita
// @author Hindu YUVA UIUC:
// @author Vivek Bhookya
// @author
//
// Format: A dictionary of dictionaries
// BHAGAVAD_GITA = {
//   "1" : {"1" : "blah blah", "2" : "blah blah", "3" : "blah blah", "4" : "blah blah"},
//   "2" : {},
//   "3" : {}
// }
//
// BHAGAVAD_GITA => The Gita
// BHAGAVAD_GITA[1] => Chapter 1 of the Gita
// BHAGAVAD_GITA[1][3] => Array of verse 3 and the meaning of verse 3 from chapter 1 of the Gita
// BHAGAVAD_GITA[1][3][0] => Array of verse 3 and the meaning of verse 3 from chapter 1 of the Gita

// BHAGAVAD_GITA[1][3][0] => Verse 3 from chapter 1 of the Gita
// BHAGAVAD_GITA[1][3][1] => English translation of verse 3 from chapter 1 of the Gita

// It will help to use predefined constants: VERSE = 0, CONSTANT = 1; when collecting the respective items from each verse pair


// Use this command in the Chrome console for easier dict creation!
// var v = <Copy paste the verses from the textfile as a list>
// str = ""
// for (let i = 1; i <= v.length; i++) {
//  var s = "\t\t\"" + i + "\" : " + JSON.stringify(v[i-1]) +  ",\n";
//  str += s;
// }
// console.log(str)

BHAGAVAD_GITA = {
  "1" : {
    "1" : ["dhrtarastra uvaca\ndharma-ksetre kuru-ksetre samaveta yuyutsavah\nmamakah pandavas caiva kim akurvata sanjaya (1.1)","Dhrtarastra said:\nO Sanjaya, what did the sons of Pandu and mine do when they gathered on\nthe sacred plain of Kuruksetra, eager for battle?"],
    "2" : ["sanjaya uvaca\ndrstva tu pandavanikam vyudham duryodhanas tada\nacaryam upasangamya raja vacanam abravit (1.2)", "Sanjaya said: Having seen the army of the Pandavas ranged for battle,\nPrince Duryodhana went up to his acarya (teacher), Drona, and said:"],
    "3" : ["pasyaitam pandu-putranam acarya mahatim camum\nvyudham drupada-putrena tava sisyena dhimata (1.3)", "Look, O Teacher, at this mighty army of the sons of Pandu, which has been\npositioned by your talented pupil, the son of Drupada."],
    "4" : ["atra sura mahesv-asa bhimarjuna-sama yudhi\nyuyudhano viratas ca drupadas ca maha-rathah (1.4)", "There are in it heroes, mighty archers, equal in battle to Bhima and\nArjuna: Yuyudhana, Virata, and the great warrior (mahdratha) Drupada,"],
    "5" : ["dhrstaketus cekitanah kasirajas ca viryavan\npurujit kuntibhojas ca saibyas ca nara-pungavah (1.5)", "Dhrishtaketu, Cekitana, and the valiant king of Kasi, Purujit, Kuntibhoja,\nand the prominent man Saibya,"],
    "6" : ["yudhamanyus ca vikranta uttamaujas ca viryavan\nsaubhadro draupadeyas ca sarva eva maha-rathah (1.6)", "The heroic Yudhamanyu, and the valiant Uttamauja; the son of Subhadra\nand the son of Draupadi, all proficient charioteers."],
    "7" : ["asmakam tu visista ye tan nibodha dvijottama\nnayaka mama sainyasya samjnartham tan bravimi te (1.7)", "I now mention, O best of the twice-born, who are the most distinguished\namong us, the commanders of my army, naming to you by way of example."],
    "8" : ["bhavan bhismas ca karnas ca krpas ca samitim-jayah\nasvatthama vikarnas ca saumadattis tathaiva ca (1.8)", "Yourself and Bhisma, Kama, the victorious Krpa, Asvatthama and\nVikarna, also Jayadratta, the son of Somadatta;"],
    "9" : ["anye ca bahavah sura mad-arthe tyakta-jivitah\nnana-sastra-praharanah sarve yuddha-visaradah (1.9)", "And, many other heroes giving up their lives for me, fighting with various\nweapons, and all well skilled in the art of warfare."],
    "10" : ["aparyaptam tad asmakam balam bhismabhiraksitam\nparyaptam tv idam etesam balam bhimabhiraksitam (1.10)", "This army of ours, commanded by Bhisma is unbeatable, whereas that\narmy of theirs which is under the protection of Bhima is inadequate."],
    "11" : ["ayanesu ca sarvesu yatha-bhagam avasthitah\nbhismam evabhiraksantu bhavantah sarva eva hi (1.11)", "Therefore, now, do all of you, occupying your respective positions in the\nvarious divisions of the army, defend Bhisma only."],
    "12" : ["tasya sanjanayan harsam kuru-vrddhah pitamahah\nsimha-nadam vinadyoccaih sankham dadhmau pratapavan (1.12)", "The powerful grandsire Bhisma, the eldest of the Kuru reign, in order to\ncheer him (Duryodhana), roared as a lion and blew his conch."],
    "13" : ["tatah sankhas ca bheryas ca panavanaka-gomukhah\nsahasaivabhyahanyanta sa sabdas tumulo \'bhavat (1.13)", "At this, and all at once, conches, kettledrums, cymbals, drums and horns\nwere heard, and the sound of that was uncontrolled."],
    "14" : ["tatah svetair hay air yukta mahati syandane sthitau\nmadhavah pandavas caiva divyau sankhau pradadhmatuh (1.14)", "Then, Madhava (Krsna) and the son of Pandu (Arjuna), who were seated in\ntheir grand chariot yoked to white horses, blew their divine conches."],
    "15" : ["pancajanyam hrsikeso devadattam dhananjayah\npaundram dadhmau maha-sankham bhima-karma vrkodarah (1.15)", "Hrsikesa (Krsna) blew the conch Pancajanya; and Dhananjaya (Arjuna, the\nwinner of wealth) blew his conch Devadatta. Bhima, the performer of\nterrible deeds, blew his great conch Paundra."],
    "16" : ["anantavijayam raja kunti-putro yudhisthirah\nnakulah sahadevas ca sughosa-manipuspakau (1.16)", "King Yudhisthira, the son of Kunti (Arjuna), blew his Anantavyaya, while\nNakula and Sahadeva blew the Sughosa and the Manipuspaka conches."],
    "17" : ["kasyas ca paramesv-asah sikhandi ca maha-rathah\ndhrstadyumno viratas ca satyakis caparajitah (1.17)", "The king of Kasi, an excellent archer; Sikhandi, the great chariot-warrior,\nDhrstadyumna, Virata, and the unconquerable Satyaki;"],
    "18" : ["drupado draupadeyas ca sarvasah prthivi-pate\nsaubhadras ca maha-bahuh sankhan dadhmuh prthak prthak (1.18)", "Drupada and the sons of Draupadi, O Lord of the Earth, and the mighty-\narmed son of Subhadra, all individually in one accord blew their respective\nconches."],
    "19" : ["sa ghoso dhartarastranam hrdayani vyadarayat\nnabhas caprthivim caiva tumulo bh/vyanunadayan (1.19)","The tumultuous uproar tore the hearts of the sons (people) of\nDhrtarashtra's assembly, filling the earth and sky with sound."],
    "20" : ["atha vyavasthitan drstva dhartarastran kapi dvajah\npravrtte sastra-sampate dhanur udyamya pandavah\nhrsikesam tada vakyam idam aha mahi-pate (1.20)","Then, looking at the sons of Dhritarashtra standing ranged for battle, while\nthe discharge of missiles began, Arjuna, the son of Pandu, whose emblem\ndepicts Maruki (a monkey) , took up his bow and spoke these words to\nHrslkesa (Krsna), O Lord of Earth:"],
    "21" : ["arjuna uvaca\nsenayor ubhayor madhye ratham sthapaya me \'cyuta\nyavad etan nirikse \'ham yod dhu-kaman avasthitan\nkair may a saha yoddhavyam asmin rana-samudyame (1.21, 1.22)","Arjuna said: O Acyuta (Immortal, Krsna), position my chariot between the\ntwo armies, that I may just see those who stand here desirous to fight, to\nknow with whom I must combat in this act of war."],
    "22" : ["arjuna uvaca\nsenayor ubhayor madhye ratham sthapaya me \'cyuta\nyavad etan nirikse \'ham yod dhu-kaman avasthitan\nkair may a saha yoddhavyam asmin rana-samudyame (1.21, 1.22)","Arjuna said: O Acyuta (Immortal, Krsna), position my chariot between the\ntwo armies, that I may just see those who stand here desirous to fight, to\nknow with whom I must combat in this act of war."],
    "23" : ["yotsyamanan avekse \'ham ya ete \'tra samagatah\ndhartarastrasya durbuddher yuddhe priya-cikirsavah (1.23)","I wish to look upon those who are assembled here, and are about to engage\nin battle eager to service in conflict the evil-minded son of Dhritarashtra,\nachieving what he regards as best."],
    "24" : ["sanjaya uvaca\nevam ukto hrsikeso gudakesena bharata\nsenayor ubhayor madhye sthapayitva rathottamam (1.24)","Sanjaya said: In response to Gudakesa's (Arjuna) request, O Bharata\n(Dhrtardshtra), Hrslkesa stationed that finest among chariots between the\ntwo armies."],
    "25" : ["bhisma-drona-pramukhatah sarvesam ca mahi-ksitam\nuvaca partha pasyaitan samavetan kurun iti (1.25)","Confronting Bhisma and Drona and all the rulers of earth, he said: O\nPartha (Arjuna), look at these assembled Kurus."],
    "26" : ["tatrapasyat sthitan parthah pitrn atha pitamahan\nacaryan matulan bhratrn putran pautran sakhims tatha\nsvasuran suhrdas caiva nayor ubhayor api (1.26)","Then, the son of Partha (Arjuna) saw ranged there in both the armies\nfathers (paternal uncles), grandfathers, teachers, maternal uncles, brothers,\nsons, grandsons and comrades, father-in-laws and friends."],
    "27" : ["tan samiksya sa kaunteyah sarvan bandhun avasthitan\nkrpaya parayavisto visidann idam abravit (1.27)","When the son of Kunti (Arjuna) saw that all those standing there in the\nranks of the two armies were his kinsmen, he was overwhelmed with\ndeepest pity and consequently said in sorrow:"],
    "28" : ["arjuna uvaca\ndrstvemam sva janam krsna yuyutsum samupasthitam\nsidanti mama gatrani mukham ca parisusyati (1.28)","Arjuna said: Seeing these kinsmen, O Krsna, ranged, eager for combat, my\nlimbs fail, and my mouth is dried up,"],
    "29" : ["vepathus ca sarire me roma harsas ca jayate\ngandivam sramsate hastat tvak caiva paridahyate (1.29)","My body quivers and my hair stands on end.\nThe Gandlva (bow) slips from my hand, and my skin is terribly burning."],
    "30" : ["na ca saknomy avasthatum bhramativa ca me manah\nnimittani ca pasyami viparitani kesava (1.30)","I am not able to stand, and my mind is spiralling as it were.\nI see opposing omens, O Kesava (Krsna),"],
    "31" : ["na ca sreyo \'nupasyami hatva sva-janam ahave\nna kankse vijayam krsna na ca rajyam sukhani ca (1.31)","and do not see any good from\nkilling my kinsmen in battle. I do not wish victory, O Krsna, nor kingdoms or pleasures. What is the use\nto us in having a kingdom, O Govinda (Krsna), or amusement and even life."],
    "32" : ["kim no rajyena govinda kim bhogair jivitena va\nyesam arthe kanksitam no rajyam bhogah sukhani ca (1.32)","Those for whose sake we desire kingdom, enjoyments and pleasures stand\nhere for battle, having abandoned life and wealth;"],
    "33" : ["ta ime \'vasthita yuddhe pranams tyaktva dhanani ca\nacaryah pitarah putras tathaiva ca pitamahah (1.33)","Teachers, fathers (paternal uncles), sons and grandfathers, maternal uncles,\nfathers-in-law, grandsons, brothers-in-law and also (other) relatives."],
    "34" : ["matulah svasurah pautrah syalah sambandhinas tatha\netan na hantum icchami ghnato \'pi madhusudana (1.34)","These, I do not want to kill, O Slayer of Madhusudana (Krsna), though they\nwant to kill us, even for the sake to obtain the primacy over the three\nworlds; and much less for the sake of the earth!"],
    "35" : ["api trailokya-rajyasya hetoh kim nu mahi-krte\nnihatya dhartarastran nah ka pritih syaj janardana (1.35)","Killing these sons of Dhrtarashtra, what satisfaction can be ours,\nO Janardana (Maintainer of the people, Krsna)? On killing these offenders only\nsin will take hold of us."],
    "36" : ["papam evasrayed asman hatvaitan atatayinah\ntasman narha vayam hantum dhartarastran sa bandhavan\nsva janam hi katham hatva sukhinah syama madhava (1.36)","It is not correct to kill our own kinsmen, the sons of Dhrtarashtra, indeed,\nby killing our own people, how can we be happy, O Madhava (Krsna)?"],
    "37" : ["yady apy ete na pasyanti lobhopahata-cetasah\nkula-ksaya-krtam dosam mitra-drohe ca patakam (1.37)","Although these, their minds overpowered by greediness, perceive no guilt in\nthe extinction of the family and no sin in treachery to friends,"],
    "38" : ["katham na jneyam asmabhih papad asman nivartitum\nkula ksaya krtam dosam prapasyadbhir janardana (1.38)","Yet, O\nJanardana (Krsna); why should we not learn to retreat from this sin,\nperceiving the guilt in the destruction of the family?"],
    "39" : ["kula-ksaye pranasyanti kula-dharmah sanatanah\ndharme naste kulam krtsnam adharmo \'bhibhavaty uta (1.39)","In the annihilation of a family, the immemorial family traditions (dharmas) are destroyed, and when these disappear,\nlawlessness overtakes the whole family."],
    "40" : ["adharmabhibhavat krsna pradusyanti kula striyah\nsttisu dustasu varsneya jayate varna-sankarah (1.40)","When lawlessness prevails, O Krsna, the women of the family become corrupted;\nand when women grow corrupt, O descendant of Varsneya (Krsna), there will be caste -confusion;"],
    "41" : ["sankaro narakayaiva kula-ghnanam kulasya ca\npatanti pitaro hy esam lupta-pindodaka-kriyah (1.41)","And, the confusion of castes leads the family and those who have destroyed the families to hell.\nTheir forefathers fall as well (to hell),\ndeprived of their ritual offerings of rice-balls and water."],
    "42" : ["dosair etaih kula-ghnanam varna-sankara-karakaih\nutsadyante jati-dharmah kula-dharmas ca sasvatah (1.42)","By these evil deeds of those destroying the family, causing the fusion of castes (varna-samkara),\nthe eternal family traditions are devastated. "],
    "43" : ["utsanna-kula-dharmanam manusyanam janardana\nnarake niyatam vaso bhavatity anususruma (1.43)","We have heard, O Janardana (Krsna), that those whose family traditions\nhave been ruined dwell necessarily in hell."],
    "44" : ["aho bata mahat papam kartum vyavasita vayam\nyad rajya-sukha-lobhena hantum sva-janam udyatah (1.44)","Alas! We have determined to commit a great sin,\ninasmuch as we are attempting to kill our own kinsmen\nthrough greediness for the pleasures of supremacy."],
    "45" : ["yadi mam apratikaram asastram sastra-panayah\ndhartarastra rane hanyus tan me ksemataram bhavet (1.45)","It would be better for me, if the sons of Dhrtarashtra, weapons in hand,\nwere to slay me in combat, while being unarmed and unable to resist."],
    "46" : ["sanjaya uvaca\nevam uktvarjunah sankhye rathopastha upavisat\nvisrjya sa-saram capam soka-samvigna-manasah (1.46)","Having spoken as such, Arjuna sank down on the seat of his chariot,\ncasting away his bow and arrow, his mind distracted with grief."]
  },
  "2" : {
    "1" : ["sanjaya uvaca\ntarn tatha krpayavistam asru-purnakuleksanam\nvisidantam idam vakyam uvaca madhusudanah (2.1)", "Sanjaya said: To him who was in this way overwhelmed with compassion\nand affliction, whose eyes were distraught and filled with tears,\nMadhava (Krsna, the destroyer of Madhu), spoke these words: "],
    "2" : ["sri-bhagavan uvaca\nkutas tva kasmalam idam visame samupasthitam\nanarya-justam asvargyam akirti-karam Arjuna (2.2)", "The Supreme Lord said: From where has this dejection come into your mind in this perilous hour?\nThis is unknown to an Aryan, not leading to heaven but causing disgrace, O Arjuna."],
    "3" : ["klaibyam ma sma gamah Partha naitat tvayy upapadyate\nksudram hrdaya-daurbalyam tyaktvottistha Parantapa (2.3)", "O Partha (Arjuna), yield not to weakness: it does not befit you.\nCast off this vile faintheartedness and arise, Parantapa (Arjuna - Conqueror of foes)."],
    "4" : ["arjuna uvaca\nkatham bhismam aham sankhye dronam ca madhusudana\nisubhih pratiyotsyami pujarhav ari-sudana (2.4)", "Arjuna said: O Madhava (Krsna), how shall I attack with arrows in combat Bhisma and Drona,\nfor they are worthy of respect, O Arisudana (O slayer of foes, Krsna)!"],
    "5" : ["gurun ahatva hi mahanubhavan sreyo bhoktum bhaiksyam apiha loke\nhatvartha-kamams tu gurun ihaiva bhunjiya bhogan rudhira-pradigdhan (2.5)", "For better were it here in this world to eat a beggar's food rather than\nby killing these teachers of high honour. However, were I to kill them,\nI should only enjoy wealth and worldly pleasures tainted with blood."],
    "6" : ["na caitad vidmah kataran no gariyo yad va jayema yadi va no jayeyuh\nyan eva hatva na jijivisamas te 'vasthitah pramukhe dhartarastrah (2.6)", "We do not know which is the better alternative for us, to conquer them or\nthey conquer us. There facing us stand Dhrtarustra's sons,\nwhom having killed, we should not even care to live."],
    "7" : ["karpanya-dosopahata-svabhavah prcchami tvam dharma-sammudha-\ncetah yac chreyah syan niscitam bruhi tan\nme sisyaste 'ham sadhi mam tvam prapannam (2.7)", "My very being (svathdva) is stained by the harmful taint of feeble pity, and\nmy mind confounded about right and wrong (Dharma, Brahman who supports all).\nI ask you; tell me what is absolutely good. I am Your disciple,\nhaving surrendered myself to You, teach me for all my trust is in You."],
    "8" : ["na hi prapasyami mamapanudyad yac chokam ucchosanam indriyanam\navapya bhumav asapatnam rddham rajyam suranam api cadhipatyam (2.8)", "I see no means to dispel the sorrow which parches my senses,\neven after attaining unrivalled and prosperous kingdom on earth\nor even lordship over the gods themselves."],
    "9" : ["sanjaya uvaca\nevam uktva hrsikesam gudakesah parantapah\nna yotsya iti govindam uktva tusnim babhuva ha (2.9)", "Sanjaya said: Having spoken like this to Hrsikesa (Krsna),\nthe powerful Gudakesa, scorcher of the foe (Arjuna),\nfall silent, saying to Govinda (Krsna): 'I will not fight' and he held his peace."],
    "10" : ["tarn uvaca hrsikesah prahasann iva bharata\nsenayor ubhayor madhye visidantam idam vacah (2.10)", "To him who was grieving, sitting amidst of the two armies, O Bharata (Arjuna),\n Hrsikesa (Krsna) smiling as it were, spoke these words:"],
    "11" : ["sri-bhagavan uvaca\nasocyan anvasocas tvam prajna-vadams ca bhasase\ngatasun agatasums ca nanusocanti panditah (2.11)", "The Supreme Lord said: You mourn for those who deserve no grief, and yet\nyou speak words of wisdom. For the living or the dead wise men know no grief."],
    "12" : ["na tv evaham jatu nasam na tvam neme janadhipah\nna caiva na bhavisyamah sarve vayam atah param (2.12)", "Never did I not exist, nor you, nor these rulers of men;\nnor will there be a time in the future when we shall cease to exist."],
    "13" : ["dehino 'smin yatha dehe kaumaram yauvanam jara\ntatha dehantara-praptir dhiras tatra na muhyati (2.13)", "Just as in this bodily form the Self (Soul) experiences childhood, youth and old age,\nso does it pass into another body (after death). In this, a thoughtful person has no doubts."],
    "14" : ["matra-sparsas tu Kaunteya sitosna-sukha-duhkha-dah\nagamapayino 'nityas tams titiksasva Bharata (2.14)", "The sense-contacts, O son of Kunti (Arjuna), which give rise to heat and cold, pleasure and pain,\ncome and go, they are impermanent. Learn to endure them, O Bharata (Arjuna)."],
    "15" : ["yam hi na vyathayanty ete purusam purusarsabha\nsama-duhkha-sukham dhiram so 'mrtatvaya kalpate (2.15)", ""],
    "16" : ["", ""],
    "17" : ["", ""],
    "18" : ["", ""],
    "19" : ["", ""],
    "20" : ["", ""],
    "21" : ["", ""],
    "22" : ["", ""],
    "23" : ["", ""],
    "24" : ["", ""],
    "25" : ["", ""],
    "26" : ["", ""],
    "27" : ["", ""],
    "28" : ["", ""],
    "29" : ["", ""],
    "30" : ["", ""],
    "31" : ["", ""],
    "32" : ["", ""],
    "33" : ["", ""],
    "34" : ["", ""],
    "35" : ["", ""],
    "36" : ["", ""],
    "37" : ["", ""],
    "38" : ["", ""],
    "39" : ["", ""],
    "40" : ["", ""],
    "41" : ["", ""],
    "42" : ["", ""],
    "43" : ["", ""],
    "44" : ["", ""],
    "45" : ["", ""],
    "46" : ["", ""],
    "47" : ["", ""],
    "48" : ["", ""],
    "49" : ["", ""],
    "50" : ["", ""],
    "51" : ["", ""],
    "52" : ["", ""],
    "53" : ["", ""],
    "54" : ["", ""],
    "55" : ["", ""],
    "56" : ["", ""],
    "57" : ["", ""],
    "58" : ["", ""],
    "59" : ["", ""],
    "60" : ["", ""],
    "61" : ["", ""],
    "62" : ["", ""],
    "63" : ["", ""],
    "64" : ["", ""],
    "65" : ["", ""],
    "66" : ["", ""],
    "67" : ["", ""],
    "68" : ["", ""],
    "69" : ["", ""],
    "70" : ["", ""],
    "71" : ["", ""],
    "72" : ["", ""]
  },
  "3" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : "",
    "36" : "",
    "37" : "",
    "38" : "",
    "39" : "",
    "40" : "",
    "41" : "",
    "42" : "",
    "43" : ""
  },
  "4" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : "",
    "36" : "",
    "37" : "",
    "38" : "",
    "39" : "",
    "40" : "",
    "41" : "",
    "42" : ""
  },
  "5" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : ""
  },
  "6" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : "",
    "36" : "",
    "37" : "",
    "38" : "",
    "39" : "",
    "40" : "",
    "41" : "",
    "42" : "",
    "43" : "",
    "44" : "",
    "45" : "",
    "46" : "",
    "47" : ""
  },
  "7" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : ""
  },
  "8" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : ""
  },
  "9" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : ""
  },
  "10" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : "",
    "36" : "",
    "37" : "",
    "38" : "",
    "39" : "",
    "40" : "",
    "41" : "",
    "42" : ""
  },
  "11" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : "",
    "36" : "",
    "37" : "",
    "38" : "",
    "39" : "",
    "40" : "",
    "41" : "",
    "42" : "",
    "43" : "",
    "44" : "",
    "45" : "",
    "46" : "",
    "47" : "",
    "48" : "",
    "49" : "",
    "50" : "",
    "51" : "",
    "52" : "",
    "53" : "",
    "54" : "",
    "55" : ""
  },
  "12" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : ""
  },
  "13" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : ""
  },
  "14" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : ""
  },
  "15" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : ""
  },
  "16" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : ""
  },
  "17" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : ""
  },
  "18" : {
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
    "5" : "",
    "6" : "",
    "7" : "",
    "8" : "",
    "9" : "",
    "10" : "",
    "11" : "",
    "12" : "",
    "13" : "",
    "14" : "",
    "15" : "",
    "16" : "",
    "17" : "",
    "18" : "",
    "19" : "",
    "20" : "",
    "21" : "",
    "22" : "",
    "23" : "",
    "24" : "",
    "25" : "",
    "26" : "",
    "27" : "",
    "28" : "",
    "29" : "",
    "30" : "",
    "31" : "",
    "32" : "",
    "33" : "",
    "34" : "",
    "35" : "",
    "36" : "",
    "37" : "",
    "38" : "",
    "39" : "",
    "40" : "",
    "41" : "",
    "42" : "",
    "43" : "",
    "44" : "",
    "45" : "",
    "46" : "",
    "47" : "",
    "48" : "",
    "49" : "",
    "50" : "",
    "51" : "",
    "52" : "",
    "53" : "",
    "54" : "",
    "55" : "",
    "56" : "",
    "57" : "",
    "58" : "",
    "59" : "",
    "60" : "",
    "61" : "",
    "62" : "",
    "63" : "",
    "64" : "",
    "65" : "",
    "66" : "",
    "67" : "",
    "68" : "",
    "69" : "",
    "70" : "",
    "71" : "",
    "72" : "",
    "73" : "",
    "74" : "",
    "75" : "",
    "76" : "",
    "77" : "",
    "78" : ""
  },
}
