"2" : {
  "1" : ["sanjaya uvaca\ntarn tatha krpayavistam asru-purnakuleksanam\nvisidantam idam vakyam uvaca madhusudanah (2.1)", "Sanjaya said: To him who was in this way overwhelmed with compassion\nand affliction, whose eyes were distraught and filled with tears,\nMadhava (Krsna, the destroyer of Madhu), spoke these words: "],
  "2" : ["sri-bhagavan uvaca\nkutas tva kasmalam idam visame samupasthitam\nanarya-justam asvargyam akirti-karam Arjuna (2.2)", "The Supreme Lord said: From where has this dejection come into your mind in this perilous hour?\nThis is unknown to an Aryan, not leading to heaven but causing disgrace, O Arjuna."],
  "3" : ["klaibyam ma sma gamah Partha naitat tvayy upapadyate\nksudram hrdaya-daurbalyam tyaktvottistha Parantapa (2.3)", "O Partha (Arjuna), yield not to weakness: it does not befit you.\nCast off this vile faintheartedness and arise, Parantapa (Arjuna - Conqueror of foes)."],
  "4" : ["arjuna uvaca\nkatham bhismam aham sankhye dronam ca madhusudana\nisubhih pratiyotsyami pujarhav ari-sudana (2.4)", "Arjuna said: O Madhava (Krsna), how shall I attack with arrows in combat Bhisma and Drona,\nfor they are worthy of respect, O Arisudana (O slayer of foes, Krsna)!"],
  "5" : ["gurun ahatva hi mahanubhavan sreyo bhoktum bhaiksyam apiha loke\nhatvartha-kamams tu gurun ihaiva bhunjiya bhogan rudhira-pradigdhan (2.5)", "For better were it here in this world to eat a beggar's food rather than\nby killing these teachers of high honour. However, were I to kill them,\nI should only enjoy wealth and worldly pleasures tainted with blood."],
  "6" : ["na caitad vidmah kataran no gariyo yad va jayema yadi va no jayeyuh\nyan eva hatva na jijivisamas te 'vasthitah pramukhe dhartarastrah (2.6)", "We do not know which is the better alternative for us, to conquer them or\nthey conquer us. There facing us stand Dhrtarustra's sons,\nwhom having killed, we should not even care to live."],
  "7" : ["karpanya-dosopahata-svabhavah prcchami tvam dharma-sammudha-\ncetah yac chreyah syan niscitam bruhi tan\nme sisyaste 'ham sadhi mam tvam prapannam (2.7)", "My very being (svathdva) is stained by the harmful taint of feeble pity, and\nmy mind confounded about right and wrong (Dharma, Brahman who supports all).\nI ask you; tell me what is absolutely good. I am Your disciple,\nhaving surrendered myself to You, teach me for all my trust is in You."],
  "8" : ["na hi prapasyami mamapanudyad yac chokam ucchosanam indriyanam\navapya bhumav asapatnam rddham rajyam suranam api cadhipatyam (2.8)", "I see no means to dispel the sorrow which parches my senses,\neven after attaining unrivalled and prosperous kingdom on earth\nor even lordship over the gods themselves."],
  "9" : ["sanjaya uvaca\nevam uktva hrsikesam gudakesah parantapah\nna yotsya iti govindam uktva tusnim babhuva ha (2.9)", "Sanjaya said: Having spoken like this to Hrsikesa (Krsna),\nthe powerful Gudakesa, scorcher of the foe (Arjuna),\nfall silent, saying to Govinda (Krsna): 'I will not fight' and he held his peace."],
  "10" : ["tarn uvaca hrsikesah prahasann iva bharata\nsenayor ubhayor madhye visidantam idam vacah (2.10)", "To him who was grieving, sitting amidst of the two armies, O Bharata (Arjuna),\n Hrsikesa (Krsna) smiling as it were, spoke these words:"],
  "11" : ["sri-bhagavan uvaca\nasocyan anvasocas tvam prajna-vadams ca bhasase\ngatasun agatasums ca nanusocanti panditah (2.11)", "The Supreme Lord said: You mourn for those who deserve no grief, and yet\nyou speak words of wisdom. For the living or the dead wise men know no grief."],
  "12" : ["na tv evaham jatu nasam na tvam neme janadhipah\nna caiva na bhavisyamah sarve vayam atah param (2.12)", "Never did I not exist, nor you, nor these rulers of men;\nnor will there be a time in the future when we shall cease to exist."],
  "13" : ["dehino 'smin yatha dehe kaumaram yauvanam jara\ntatha dehantara-praptir dhiras tatra na muhyati (2.13)", "Just as in this bodily form the Self (Soul) experiences childhood, youth and old age,\nso does it pass into another body (after death). In this, a thoughtful person has no doubts."],
  "14" : ["matra-sparsas tu Kaunteya sitosna-sukha-duhkha-dah\nagamapayino 'nityas tams titiksasva Bharata (2.14)", "The sense-contacts, O son of Kunti (Arjuna), which give rise to heat and cold, pleasure and pain,\ncome and go, they are impermanent. Learn to endure them, O Bharata (Arjuna)."],
  "15" : ["yam hi na vyathayanty ete purusam purusarsabha\nsama-duhkha-sukham dhiram so 'mrtatvaya kalpate (2.15)", ""],
  "16" : ["", ""],
  "17" : ["", ""],
  "18" : ["", ""],
  "19" : ["", ""],
  "20" : ["", ""],
  "21" : ["", ""],
  "22" : ["", ""],
  "23" : ["", ""],
  "24" : ["", ""],
  "25" : ["", ""],
  "26" : ["", ""],
  "27" : ["", ""],
  "28" : ["", ""],
  "29" : ["", ""],
  "30" : ["", ""],
  "31" : ["", ""],
  "32" : ["", ""],
  "33" : ["", ""],
  "34" : ["", ""],
  "35" : ["", ""],
  "36" : ["", ""],
  "37" : ["", ""],
  "38" : ["", ""],
  "39" : ["", ""],
  "40" : ["", ""],
  "41" : ["", ""],
  "42" : ["", ""],
  "43" : ["", ""],
  "44" : ["", ""],
  "45" : ["", ""],
  "46" : ["", ""],
  "47" : ["", ""],
  "48" : ["", ""],
  "49" : ["", ""],
  "50" : ["", ""],
  "51" : ["", ""],
  "52" : ["", ""],
  "53" : ["", ""],
  "54" : ["", ""],
  "55" : ["", ""],
  "56" : ["", ""],
  "57" : ["", ""],
  "58" : ["", ""],
  "59" : ["", ""],
  "60" : ["", ""],
  "61" : ["", ""],
  "62" : ["", ""],
  "63" : ["", ""],
  "64" : ["", ""],
  "65" : ["", ""],
  "66" : ["", ""],
  "67" : ["", ""],
  "68" : ["", ""],
  "69" : ["", ""],
  "70" : ["", ""],
  "71" : ["", ""],
  "72" : ["", ""]
}
