// My Bhagavad Gita
// ch03.js
//
// This file holds the verses and translations of chapter three from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"3" : {
  "1" : ["arjuna uvaca\njyayasi cet karmanas te mata buddhir janardana\ntat kim karmani ghore mam niyojayasi Kesava (3.01)", "Arjuna said: O Janardana (Krsna), if you think that knowledge is superior\nto action, why then, O Kesava (Krsna), do you command me to carry out a\nterrible action?"],
  "2" : ["vyamisreneva vakyena buddhim mohayasiva me\ntad ekam vada niscitya yena sreyo 'ham apnuyam (3.02)", "With these perplexing words, You confuse as it were my mind. Tell me with\ncertainty the one way by which I may attain bliss."],
  "3" : ["sri-bhagavan uvaca\nloke 'smin dvi-vidha nistha pura prokta mayanagha\njnana-yogena sankhyanam karma-yogena yoginam (3.03)", "The Supreme Lord said: O sinless one (Arjuna), as it has been stated by Me\nbefore, in this world there is a twofold path, that of knowledge (Jhana-yoga)\nfor those who contemplate and that of action (Karma-yoga) for those who\nact."],
  "4" : ["na karmanam anarambhan\nnaiskarmyam puruso 'snute\nna ca sannyasanad eva\nsiddhim samadhigacchati (3.04)", "Not by leaving action undone does man win freedom from the bond of\naction, nor by renunciation alone does he attain perfection."],
  "5" : ["na hi kascit ksanam api jatu tisthaty akarma-krt\nkaryate hy avasah karma sarvah prakrti-jair gunaih (3.05)", "Not for a moment can a man remain without acting; for every man is\nhelpless, and forced to work by the impulses born of nature."],
  "6" : ["karmendriyani samyamya ya aste manasa smaran\nindriyarthan vimudhatma mithyacarah sa ucyate (3.06)", "The deluded who controls his limbs through which he acts, but sits thinking\nin his mind about sense-objects, is said to be a hypocrite."],
  "7" : ["yas tv indriyani manasa niyamyarabhate 'rjuna\nkarmendriyaih karma-yogam asaktah sa visisyate (3.07)", "But he who controls his senses with his mind, O Arjuna, using the organs of\naction without attachment, is worthily engaged in Karma-yoga."],
  "8" : ["niyatam kuru karma tvam karma jyayo hy akarmanah\nsarira-yatrapi ca te na prasiddhyed akarmanah (3.08)", "Perform the action that is prescribed for you, for action is superior to\ninaction. And even the maintenance of the body would not be possible for\nyou by inaction."],
  "9" : ["yajnarthat karmano 'nyatra loko 'yam karma-bandhanah\ntad-artham karma Kaunteya mukta-sangah samacara (3.09)", "Except for action performed for the sake of sacrifice (selfless service), all\nothers holds the world action-bound. Therefore, O son of Kunti (Arjuna),\nperform your action free from attachment."],
  "10" : ["saha-yajnah prajah srstva purovaca prajapatih\nanena prasavisyadhvam esa vo 'stv ista-kama-dhuk (3.10)", "Of old, the Lord of Creation (Prajapati) emanating mankind together with\nsacrifice (selfless service), said: By this you shall prolong your lineage; let\nthis be to you the cow that gives the milk of all your desires."],
  "11" : ["devan bhavayatanena te deva bhavayantu vah\nparasparam bhavayantah sreyah param avapsyatha (3.11)", "With this you shall sustain the gods, so that the gods may on their turn\nsustain you. Thus, sustaining one another, you shall attain the highest good."],
  "12" : ["istan bhogan hi vo deva dasyante yajna-bhavitah\ntair dattan apradayaibhyo yo bhunkte stena eva sah (3.12)", "For, so sustained by sacrifice (selfless service), the gods will grant you your\ndesired enjoyments. Whoso enjoys their gift, without offering to Them in\nreturn, is indeed a thief."],
  "13" : ["yajna-sistasinah santo mucyante sarva-kilbisaih\nbhunjate te tv agham papa ye pacanty atma-karanat (3.13)", "The righteous who eat of the leavings of the sacrifice, are freed from all\nsins; but, impious are they, and evil do they eat who cook food for their own\n(selfish) sakes."],
  "14" : ["annad bhavanti bhutani parjanyad anna-sambhavah\nyajnad bhavati parjanyo yajnah karma -samudbhavah (3.14)", "From food creatures are born, and food from rain; and rain comes forth\nfrom sacrifice (selfless service); and sacrifice is born of action."],
  "15" : ["karma brahmodbhavam viddhi brahmaksara-samudbhavam\ntasmat sarva-gatam brahma nityam yajne pratisthitam (3.15)", "Know that action comes from Brahman, and Brahman is from the\nImperishable. Therefore, Brahman, the all-pervading, is ever present in\nsacrifice {selfless service)."],
  "16" : ["evam pravartitam cakram nanuvartayatiha yah\naghayur indriyaramo mogham partha sa jivati (3.16)", "He who on earth does not follow the wheel thus set in motion, who is of\nsinful life, indulging in the senses, O Partha (Arjuna), he lives in vain."],
  "17" : ["yas tv atma-ratir eva syad atma-trptas ca manavah\natmany eva ca santustas tasya karyam na vidyate (3.17)", "However, the man who rejoices in the Self -alone, who is satisfied with the\nSelf-alone, in the Self-alone content, there is nothing he needs to do."],
  "18" : ["naiva tasya krtenartho nakrteneha kascana\nna casya sarva-bhutesu kascid artha-vyapasrayah (3.18)", "For him, there is here no interest in what is done, or what is not done. Nor\ndoes he depend upon any contingent being for attaining any purpose."],
  "19" : ["tasmad asaktah satatam karyam karma samacara\nasakto hy acaran karma param apnoti purusah (3.19)", "Therefore, without attachment perform what you have to do, for\nperforming action without attachment, man really reaches the Supreme."],
  "20" : ["karmanaiva hi samsiddhim asthita janakadayah\nloka-sangraham evapi sampasyan kartum arhasi (3.20)", "It was through action only that Janaka and others tried to attain perfection.\nEven again for the protection of the world you should perform action."],
  "21" : ["yad yad acarati sresthas tat tad evetaro janah\nsa yat pramanam kurute lokas tad anuvartate (3.21)", "For whatever the noblest does, is also done by others; whatever norm he\nsets up, the world will follow."],
  "22" : ["na me parthasti kartavyam trisu lokesu kincana\nnanavaptam avaptavyam varta eva ca karmani (3.22)", "O Partha (Arjuna), in the three worlds there is nothing that I must\naccomplish at all. Nor anything unattained which I have not attained, yet I\nam engaged in action."],
  "23" : ["yadi hy aham na varteyam jatu karmany atandritah\nmama vartmanuvartante manusyah partha sarvasah (3.23)", "For were I not be tirelessly engaged in action, then, would men in all\nmatters follow My path, O Partha (Arjuna)."],
  "24" : ["utsideyur ime loka na kuryam karma ced aham\nsankarasya ca karta syam upahanyam imah prajah (3.24)", "If I were not engaged in action, these worlds would fall to ruin, and I should\nbe the cause of confusion of castes, and destroy these creatures."],
  "25" : ["saktah karmany avidvamso yatha kurvanti bharata\nkuryad vidvams tathasaktas cikirsur loka-sangraham (3.25)", "Therefore, O Bharata (Arjuna), as the ignorant act attached to action, the\nwise man should perform action unattached, longing the welfare of the\nworld."],
  "26" : ["na buddhi-bhedam janayed ajnanam karma-sanginam\njosayet sarva-karmani vidvan yuktah samacaran (3.26)", "Let the wise man not perturb the mind of ignorant people attached to\naction, let him encourage them to do all actions as himself, fulfilling them\nwith devotion (selfless service, in the spirit of yoga)."],
  "27" : ["prakrteh kriyamanani gunaih karmani sarvasah\nahankara- vimudhatma kartaham iti manyate (3.27)", "All actions are done by the constituents of nature (prakrti). He, whose mind\nis fooled by the ego, thinks 'I am the doer'."],
  "28" : ["tattva-vit tu maha-baho guna-karma- vibhagayoh\nguna gunesu vartanta iti matva na sajjate (3.28)", "But he, O mighty-armed (Arjuna), who knows that these constituents and\nactions are distinct from himself, and that only the Constituents on\nconstituents are acting, is not attached."],
  "29" : ["prakrter guna-sammudhah sajjante guna-karmasu\ntan akrtsna-vido Mandan krtsna-vin na vicalayet (3.29)", "Those deluded by the constituents of Nature (prakrti, material nature) are\nattached to the actions of those functions. The wise should not perturb the\nunwise whose knowledge is imperfect."],
  "30" : ["mayi sarvani karmani sannyasyadhyatma-cetasa\nnirasir nirmamo bhutva yudhyasva vigata-jvarah (3.30)", "Cast all your actions on Me, with your mind fixed in the Self, freed from\nhope and selfishness, devoid of mental fever, do fight (engage in battle)."],
  "31" : ["ye me matam idam nityam anutisthanti manavah\nsraddhavanto 'nasuyanto mucyante te 'pi karmabhih (3.31)", "Those who constantly practise this teaching of Mine with faith and without\ncavilling, they too will find release from the bondage of actions."],
  "32" : ["ye tv etad abhyasuyanto nanutisthanti me matam\nsarva-jnana-vimudhams tan viddhi nastan acetasah (3.32)", "But those who, carping at My teaching, and do not practice it, know them\nas deluded in all knowledge, mindless and lost."],
  "33" : ["sadrsam cestate svasyah prakrter jnanavan api\nprakrtim yanti bhutani nigrahah kim karisyati (3.33)", "Even the man of knowledge behaves according to his own nature. All beings\nfollow their nature. So, what can repression do?"],
  "34" : ["Indriyasyendriyasyarthe raga-dvesau vyavasthitau\ntayor na vasam agacchet tau hy asya paripanthinau (3.34)", "In all the senses love and hate (affection and aversion) are turned to their\nproper objects; let no one become victim to their power, for they are\nenemies of the path."],
  "35" : ["sreyan sva-dharmo vigunah para-dharmat sv-anusthitat\nsva-dharme nidhanam sreyah para-dharmo bhayavahah (3.35)", "Better to perform one's own duty (dharma), though deprived of merit, than\nthe duty of another well discharged. Better to die in one's own duty, for it is\nperilous to follow another's duty."],
  "36" : ["arjuna uvaca\natha kena prayukto 'yam papam carati purusah\nanicchann api varsneya balad iva ni yojitah (3.36)", "Arjuna said: O Varsneya (Krsna), by what provocation does a man commit\nsin as though he were constrained by force, unwilling though he be?"],
  "37" : ["sri-bhagavan uvaca\nkama esa krodha esa rajo-guna-samudbhavah\nmahasano maha-papma viddhy enam iha vairinam (3.37)", "The Supreme Lord said: It is desire, it is anger, arising from rajas (passion)\nconstituent, all-devouring and all sinful. Know this to be your enemy on\nearth."],
  "38" : ["dhumenavriyate vahnir yathadarso malena ca\nyatholbenavrto garbhas tatha tenedam avrtam (3.38)", "Just as fire is surrounded by smoke, a mirror by dust, an embryo enclosed\nby the womb, so 'This' (knowledge, Brahma-jndna) is covered by it (rajas,\nlust)."],
  "39" : ["avrtam jnanam etena jnanino nitya-vairina\nkama-rupena Kaunteya duspurenanalena clena ca (3.39)", "Covered, O son of Kunti (Arjuna) is knowledge by this constant enemy of\nthe wise in the form of desire, which is insatiable fire."],
  "40" : ["indriyani mano buddhir asyadhisthanam ucyate\netair vimohayaty esa jnanam avrtya dehinam (3.40)", "The senses, the mind and intellect (reason) are said to be its seat. With their\nsupport, it fences knowledge in, deluding the embodied Self."],
  "41" : ["tasmat tvam indriyany adau niyamya bharatarsabha\npapmanam prajahi hy enam jnana- vijnana-nasanam (3.41)", "Therefore, O best of the Bharatas {Arjuna) restrain the senses first, and\ndestroy this evil thing (sin), which is destructive for knowledge and\nrealisation."],
  "42" : ["indriyani parany ahur indriyebhyah param manah\nmanasas tu para buddhir yo buddheh paratas tu sah (3.42)", "They say that the senses are superior to the body, higher than the senses is\nthe mind, yet higher than the mind is the intellect, but what is greater than\nthe intellect is 'He' (the Supreme)."],
  "43" : ["evam buddheh param buddhva samstabhyatmanam atmana\njahi satrum maha-baho kama-rupam durasadam (3.43)", "Know 'Him' (Atmd, the Self) who is beyond the intellect, subduing the self\n(one's own mind) by the Self. O mighty-armed (Arjuna), destroy the enemy\nswift to change in the form of lust, hard to conquer."]
}
