// My Bhagavad Gita
// ch06.js
//
// This file holds the verses and translations of chapter six from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"6" : {
  "1" : ["sri-bhagavan uvaca\nanasritah karma-phalam karyam karma karoti yah\nsa sannyasi ca yogi ca na niragnir na cakriyah (6.01)", "The Supreme Lord said: He who performs such action as duty, without\ndepending on the fruits of action, he is a sannyasin (ascetic) and a yogi, not\nhe who ceases from sacrificial fire and rites."],
  "2" : ["yam sannyasam iti prahur yogam tam viddhi pandava\nna hy asannyasta-sankalpo yogi bhavati kascana (6.02)", "Know that what is termed renunciation is the practice of Yoga, O Pandava\n(Arjuna), for without renouncing set purpose (sankalpa), no one can become\na yogi."],
  "3" : ["aruruksor muner yogam karma karanam ucyate\nyogarudhasya tasyaiva samah karanam ucyate (6.03)", "For the sage who desires to attain yoga, action is said to be the means. For\nthe same sage, when he has attained yoga, it is said that serenity (samah) is\nthe means."],
  "4" : ["yada hi nendriyarthesu na karmasv anusajjate\nsarva-sankalpa-sannyasi yogarudhas tadocyate (6.04)", "For the one who knows no attachment to objects of sense and actions, when\nhe has renounced all set purpose, then he is said to have attained yoga."],
  "5" : ["uddhared atmanatmanam natmanam avasadayet\natmaiva hy atmano bandhur atmaiva ripur atmanah (6.05)", "Let him raise the self by the Self, and let him not lower himself; for truly\nonly the Self is the friend of the self, and also the Self the self's enemy."],
  "6" : ["bandhur atmatmanas tasya yenatmaivatmana jitah\nanatmanas tu satrutve vartetatmaiva satru-vat (6.06)", "The Self is the friend of the self of him whose self is by the Self conquered;\nbut to the unrestrained self, the Self will definitely act as an enemy."],
  "7" : ["jitatmanah prasantasya paramatma samahitah\nsitosna-sukha-duhkhesu tatha manapamanayoh (6.07)", "The Supreme Self (higher self) of the self-controlled, who knows\ntranquillity, is steadfast in cold and heat, in pleasure and pain, as well as in\nhonour and dishonour."],
  "8" : ["jnana-vijnana-trptatma kuta-stho vijitendriyah\nyukta ity ucyate yogi sama-lostrasma-kancanah (6.08)", "The Yogi whose 'self is satisfied in knowledge learnt, who remains rock-\nseated, with senses subdued, he is said to be an integrated, and for whom a\nlump of earth, a stone and gold are equal.'"],
  "9" : ["suhrn-mitrary-udasina- madhyastha-dvesya-bandhusu\nsadhusv api ca papesu sama-buddhir visisyate (6.09)", "Excellent he whose attitude is the same towards benefactors, friends,\ncompanions, enemies, the indifferent, the neutrals, the hateful, relatives, the\ngood and the evil ones."],
  "10" : ["yogi yunjita satatam atmanam rahasi sthitah\nekaki yata-cittatma nirasir aparigrahah (6.10)", "Let the Yogi constantly concentrate his mind on yoga, remaining alone in a\nsolitary place, with mind and body under full control, free from desires and\nattachment to material possessions."],
  "11" : ["sucau dese pratisthapya sthiram asanam atmanah\nnaty-ucchritam nati-nicam cailajina-kusottaram (6.11)", "Let him for himself set up a firm seat in a clean place, neither too high nor\nyet too low, on the sacred kusa grass, covered with a deer-skin and over it a\ncloth."],
  "12" : ["tatraikagram manah krtva yata-cittendriya-kriyah\nupavisyasane yunjyad yogam atma-visuddhaye (6.12)", "There let him sit, and making the mind one-pointed, with the motions of\nthought and senses restrained, fixed on his seat practise yoga for the\npurification of the Self."],
  "13" : ["samam kaya-siro-grivam dharayann acalam sthirah\nsampreksya nasikagram svam disas canavalokayan (6.13)", "Remaining still, holding the body, head and neck erect, let him fix his gaze\non the tip of his nose, without looking around."],
  "14" : ["prasantatma vigata-bhir brahmacari-vrate sthitah\nmanah samyamya mac-citto yukta asitamat-parah (6.14)", "Serene minded, fearless, firm in the vow of celibacy (of the Brahmachari),\nthe mind controlled, thinking on Me in total concentration, let him sit with\nintent on Me as the supreme goal."],
  "15" : ["yunjann evam sadatmanam yogi niyata-manasah\nsantim nirvana-paramam mat-samstham adhigacchati (6.15)", "So, the Yogi ever integrated in the Self, his mind restrained, attains to the\npeace which has Nirvana (nirvana...) as its end, and which subsists in Me."],
  "16" : ["naty-asnatas tu yogo 'sti na caikantam anasnatah\nna cati-svapna-silasya jagrato naiva carjuna (6.16)", "However, O Arjuna, yoga is not for him, who eats too much, nor for him\nwho does not eat at all; nor for him who sleeps too much, nor yet for him\nwho stays awake too long."],
  "17" : ["yuktahara-viharasya yukta-cestasya karmasu\nyukta-svapnavabodhasya yogo bhavati duhkha-ha (6.17)", "But, yoga is for him who is regulated (yukta) in food and recreation, who is\nregulated in all his deeds and gestures, who is regulated in sleeping as in\nwalking, achieving a yoga which destroys all pain."],
  "18" : ["yada viniyatam cittam atmany evavatisthate\nnisprhah sarva-kamebhyo yukta ity ucyate tada (6.18)", "When the well-controlled mind is established in the Self alone, free from\nlonging after all desirable things, then it is said, that the one is at peace."],
  "19" : ["yatha dipo nivata-stho nengate sopama smrta\nyogino yata-cittasya yunjato yogam atmanah (6.19)", "As a lamp may stand not flickering in a windless place - this has been\nlikened with the disciplined mind of a Yogi, absorbed in the yoga of the Self."],
  "20" : ["yatroparamate cittam niruddham yoga-sevaya\nyatra caivatmanatmanam pasyann atmani tusyati (6.20)", "When the mind is at rest, quieted by the practise of yoga; when seeing the\nSelf by the self, he finds fulfilment in his own Self."],
  "21" : ["sukham atyantikam yat tad buddhi-grahyam atindriyam\nvetti yatra na caivayam sthitas calati tattvatah (6.21)", "When he knows that utmost joy which, transcending the senses, can be\ngrasped by the intellect; when standing still (in the Self), he never departs\nfrom reality."],
  "22" : ["yam labdhva caparam labham manyate nadhikam tatah\nyasmin sthito na duhkhena gurunapi vicalyate (6.22)", "When, having reached it, he thinks that there is no greater acquisition\nbeyond it; therein established, he is not dislodged by any sorrow, even in\nthe greatest suffering:"],
  "23" : ["tarn vidyad duhkha-samyoga- viyogam yoga-samjnitam\nsa niscayena yoktavyo yogo 'nirvinna-cetasa (6.23)", "That state is known by the name of yoga (viyogan), the unlinking from the\nunion with pain. This is the yoga which must be brought about with firm\nresolve and an undismayed mind."],
  "24" : ["sankalpa-prabhavan kamams tyaktva sarvan asesatah\nmanasaivendriya-gramam viniyamya samantatah (6.24)", "Abandoning without remainder all desires which arise from thought,\ncontrolling the senses from every side by the mind;"],
  "25" : ["sanaih sanair uparamed buddhya dhrti-grhita ya\natma-samstham manah krtva na kincid api cintayet (6.25)", "His intellect held fast in steadfastness, let he come little by little to rest,\nhaving made the mind abide in the Self, thinking of nothing else."],
  "26" : ["yato yato niscalati manas cancalam asthiram\ntatas tato niyamyaitad atmany eva vasam nayet (6.26)", "By whatever matter the flickering and unsteady mind wanders away, he\nshould hold it back, and subject it to the Self alone."],
  "27" : ["prasanta-manasam hy enam yoginam sukham uttamam\nupaiti santa-rajasam brahma-bhutam akalmasam (6.27)", "Supreme bliss is for the Yogi whose mind is stilled, whose passion is laid to\nrest, who is sinless, and of the nature of Brahman."],
  "28" : ["yunjann evam sadatmanam yogi vigata-kalmasah\nsukhena brahma-samsparsam atyantam sukham asnute (6.28)", "The Yogi, in this way, always integrating the Self, freed from all sins,\nattains with ease the infinite bliss of Brahman's touch."],
  "29" : ["sarva-bhuta-stham atmanam sarva-bhutani catmani\niksate yoga-yuktatma sarvatra sama-darshanah (6.29)", "He, whose self is integrated in yoga, sees the Self abiding in all beings, and\nall beings in the Self, seeing the same everywhere."],
  "30" : ["yo mam pasyati sarvatra sarvam ca mayi pasyati\ntasyaham na pranasyami sa ca me na pranasyati (6.30)", "He, who sees Me everywhere, and sees everything in Me, for him I am not\nlost, nor is he lost for Me."],
  "31" : ["sarva-bhuta-sthitam yo mam bhajaty ekatvam asthitah\nsarvatha vartamano 'pi sa yogi mayi vartate (6.31)", "He, who embraces unity, worships Me as abiding in all beings, that Yogi\nlives in Me, whatever his mode of life."],
  "32" : ["atmaupamyena sarvatra samam pasyati yo 'rjuna\nsukham va yadi va duhkham sa yogi paramo matah (6.32)", "O Arjuna, he who, in comparison with himself, sees the same everywhere in\npleasure as in pain, he is considered to be the perfect Yogi."],
  "33" : ["arjuna uvaca\nyo 'yam yogas tvaya proktah samyena madhusudana\netasyaham na pasyami cancalatvat sthitim sthiram (6.33)", "Arjuna said: O destroyer of Madhu (Madhusudana/Krsna), the yoga of\nequanimity that you have preached, I see not a firm foundation for it, owing\nto the wavering of the mind."],
  "34" : ["cancalam hi manah Krsna pramathi balavad drdham\ntasyaham nigraham manye vayor iva su-duskaram (6.34)", "For the mind, O Krsna, is truly unsteady, turbulent, strong and difficult to\ncurb, I think it as hard to hold as the wind."],
  "35" : ["sri-bhagavan uvaca\nasamsayam maha-baho mano durnigraham calam\nabhyasena tu Kaunteya vairagyena ca grhyate (6.35)", "The Supreme Lord said: herein, there is no doubt, O mighty -armed\n(Arjuna), the mind is hard to curb and fickle; but it may be curbed by\nuntiring practice and detachment."],
  "36" : ["asamyatatmana yogo dusprapa iti me matih\nvasyatmana tu yatata sakyo 'vaptum upayatah (6.36)", "I hold that yoga is hard to achieve for someone whose self is unsubdued; but\nhe who strives, self-controlled, it can be won by the appropriate means."],
  "37" : ["arjuna uvaca\nayatih sraddhayopeto yogac calita-manasah\naprapya yoga-samsiddhim kam gatim krsna gacchati (6.37)", "Arjuna said: He who is lacking self-control, even though his faith, his mind\nwandering away from Yoga, failing to attain perfection in yoga, what is his\nend, O Krsna?"],
  "38" : ["kaccin nobhaya-vibhrastas chinnabhram iva nasyati\napratistho maha-baho vimudho brahmanah pathi (6.38)", "Both objects unachieved, does he not perish like a split cloud, his firm\nfoundation gone, O mighty-armed (Krsna), confused on Brahman's path?"],
  "39" : ["etan me samsayam Krsna chettum arhasy asesatah\ntvad-anyah samsayasyasya chetta na hy upapadyate (6.39)", "Consent, O Krsna, to dispel completely this doubt of mine; for none is to be\nfound except Yourself able to destroy this doubt."],
  "40" : ["sri-bhagavan uvaca\npartha naiveha namutra vinasas tasya vidyate\nna hi kalyana-krt kascid durgatim tata gacchati (6.40)", "The Supreme Lord said: O Partha (Arjuna), neither in this world nor in the\nlife to come is there destruction for him; for, no doer of righteousness, O\nbeloved, treads the path of grief."],
  "41" : ["prapya punya-krtam lokan usitva sasvatih samah\nsucinam srimatam gehe yoga-bhrasto 'bhijayate (6.41)", "Having reached the worlds of the righteous and lived there endless years, he\nwho fell from yoga is reborn in the house of the pious and prosperous."],
  "42" : ["atha va yoginam eva kule bhavati dhimatam\netad dhi durlabhataram- loke janma yad idrsam (6.42)", "Or, else he may be born in a family of wise yogis only; but the kind of birth\nis harder to obtain in this world."],
  "43" : ["tatra tarn buddhi-samyogam labhate paurva-dehikam\nyatate ca tato bhuyah samsiddhau kuru-nandana (6.43)", "There he regains the knowledge belonging to his former body, and strives\nmore than before for perfection, O son of the Kurus (Arjuna)."],
  "44" : ["purvabhyasena tenaiva hriyate hy avaso 'pi sah\njijnasur api yogasya sabda-brahmativartate (6.44)", "By that former practice he is irresistibly motivated in spite of himself. Even\nhe who inquires after the practice of yoga rises beyond the Brahmic word\n(the Vedas)."],
  "45" : ["prayatnad yatamanas tu yogi samsuddha-kilbisah\naneka-janma-samsiddhas tato yati param gatim (6.45)", "But the yogi, striving with utmost zeal, cleansed from sin, fully perfected\nthrough many births, then reaches the Supreme goal."],
  "46" : ["tapasvibhyo 'dhiko yogi jnanibhyo 'pi mato 'dhikah\nkarmibhyas cadhiko yogi tasmad yogi bhavarjuna (6.46)", "The yogi is thought superior to the ascetics; he is even considered superior\nto men of knowledge; he is also superior to men of action, therefore become\na yogi, O Arjuna."],
  "47" : ["yoginam api sarvesam mad-gatenantar-atmana\nsraddhavan bhajate yo mam sa me yuktatamo matah (6.47)", "And, among all yogis, he who full of faith worships Me with his inner Self\nabsorbed in Me, he is thought by Me as the most fully integrated."]
}
