// My Bhagavad Gita
// ch07.js
//
// This file holds the verses and translations of chapter seven from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author Vivek Mallampati
// @author
// If you edit this file, add yourself as an author!

"7" : {
  "1" : ["sri-bhagavan uvaca\nmayy asakta-manah Partha yogam yunjan mad-asrayah\nasamsayam samagram mam- yatha jnasyasi tac chrnu (7.01)", "The Supreme Lord said: With the mind attached to Me, O Partha, engaged\nin yogic practices, taking refuge in Me, hear now how you shall know Me\nfully and without doubt."],
  "2" : ["jnanam te \'ham sa-vijnanam idam vaksyamy asesatah\nyaj jnatva neha bhuyo \nyaj jnatavyam avasisyate (7.02)", "I shall completely teach you this knowledge combined with experience,\nleaving nothing unsaid. This knowing, there remains nothing left to be\nknown."],
  "3" : ["manusyanam sahasresu kascid yatati siddhaye\nyatatam api siddhanam kascin mam vetti tattvatah (7.03)", "Among thousands of men, one maybe will strive for perfection; and even\namong those who strive having won perfection, only one, maybe, know Me\nas I really am."],
  "4" : ["bhumir apo \'nalo vayuh kham mano buddhir eva ca\nahankara itiyam me bhinna prakrtir astadha (7.04)", "Earth, water, fire, air, ether, mind, intellect (Buddhi) and ego (Ahamkara,\nsense of self), these are the eightfold divisions of My nature (Prakriti)."],
  "5" : ["apareyam itas tv anyam prakrtim viddhi me param\njiva-bhutam maha-baho yayedam dharyate jagat (7.05)", "This is the lower (Prakriti)( Apard-sakti), but know My other nature the\nhigher (Prakriti) (Para-sakti), the life-element, O mighty-armed (Arjuna), by\nwhich this universe (jagat) is kept maintained."],
  "6" : ["etad-yonini bhutani sarvanity upadharaya\naham krtsnas ya jagatah prabhavah pralayas tatha (7.06)", "Know that from these (two Natures) all beings take their birth. Therefore, I\nam the origin of the whole universe and also its end."],
  "7" : ["mattah parataram nanyat kincid asti dhananjaya\nmayi sarvam idam protam sutre mani-gana iva (7.07)", "There is nothing whatsoever higher than I, O Dhananjaya (Arjuna), in Me\nthe universe (sarvan) is strung, like clustered pearls upon a thread."],
  "8" : ["raso \'ham apsu Kaunteya prabhasmi sasi-suryayoh\npranavah sarva-vedesu sabdah khe paurusam nrsu (7.08)", "I am the flavour in water, O son of Kunti (Arjuna), I am the radiance in\nmoon and sun; in all the Vedas the OM syllable, sound in ether, and\nmanhood in all men."],
  "9" : ["punyo gandhah prthivyam ca tejas casmi vibhavasau\njivanam sarva-bhutesu tapas casmi tapasvisu (7.09)", "I am the pure fragrance in the earth, the flame\'s onset in fire; I am the life\nin all beings, and I am the fierce austerity in ascetics."],
  "10" : ["bijam mam sarva-bhutanam viddhi partha sanatanam\nbuddhir buddhimatam asmi tejas tejasvinam aham (7.10)", "O Partha (Arjuna), know Me as the eternal seed of all beings. I am the\nintelligence of the intelligent, and the glory of the glorious."],
  "11" : ["balam balavatam caham kama-raga-vivarjitam\ndharmaviruddho bhutesu kamo \'smi bharatarsabha (7.11)", "And I am the power of the powerful, knowing no passion nor attachment;\nand in contingent beings I am the desire unopposed to duty (Dharma), O\nlord of the Bharatas (Arjuna)." ],
  "12" : ["ye caiva sattvika bhava rajasas tamasas ca ye\nmatta eveti tan viddhi na tv aham tesu te mayi (7.12)", "Know too that all the objects of goodness (Sattva), passion (Rajas), or\nignorance (Tamas) proceed from Me, but I am not in them, they are in Me."],
  "13" : ["tribhir guna-mayair bhavair ebhih sarvam idam jagat\nmohitam nabhijanati mam ebhyah param avyayam (7.13)", "By these three states of being composed of gunas, this entire world is led\nastray, and do not know that I am far beyond them and immutable."],
  "14" : ["daivi hy esa guna-mayi mama maya duratyaya\nmam eva ye prapadyante may am etam taranti te (7.14)", "For all this My divine Maya (power), caused by the gunas (the three modes),\nis hard to transcend. Therefore, whoever shall put his trust in Me alone,\npass beyond this uncanny Maya."],
  "15" : ["na mam duskrtino mudhah prapadyante naradhamah\nmayayapahrta-jnana asuram bhavam asritah (7.15)", "The doers of evil, the deluded, the base, put not their trust in Me; their\nmind seduced by this uncanny Maya (power), they have embraced a devilish\nform of life (bhava)."],
  "16" : ["catur-vidha bhajante mam janah sukrtino \'rjuna\narto jijnasur artharthi jnani ca bharatarsabha (7.16)", "Fourfold are the virtuous people who worship Me, O Arjuna, the afflicted,\nthe ones who look for knowledge, the ones who strive for gain (self-\ninterested), and the men of knowledge (the learned, the wise), O best of the\nBharatas (Arjuna)."],
  "17" : ["tesam jnani nitya-yukta eka-bhaktir visisyate\npriyo hi jnanino \'tyartham aham sa ca mama priyah (7.17)", "Of these, is the man of knowledge, ever integrated, worshipping the One, is\nthe best: to such a man I am exceedingly dear, and he is dear to Me."],
  "18" : ["udarah sarva evaite jnani tv atmaiva me matam\nasthitah sa hi yuktatma mam evanuttamam gatim (7.18)", "Noble and exalted are all these, but the man of knowledge, do I regard as\nMy very Self; for his self integrated, is fixed on Me, the highest goal."],
  "19" : ["bahunam janmanam ante jnanavan mam prapadyate\nvasudevah sarvam iti sa mahatma su-durlabhah (7.19)", "At the close of many births, the man of knowledge takes refuge in Me,\nconcluding that Vasudeva\'s son (Krsna) is all. Such a noble soul (Mahatma)\nis very rare."],
  "20" : ["kamais tais tair hrta-jnanah prapadyante \'nya-devatah\ntarn tam niyamam asthaya prakrtya niyatah svaya (7.20)", "Those whose knowledge has been swept away by various desires, resort to\nother deities (Devas), engaged with various rules and precepts, constrained\nby their own nature."],
  "21" : ["yo yo yam yam tanum bhaktah sraddhayarcitum icchati\ntasya tasyacalam sraddham tam eva vidadhamy aham (7.21)", "Whatever form (whatever deity) a devotee with faith desires to worship, that\nvery faith I confirm in him, making it steadfast."],
  "22" : ["sa taya sraddhaya yuktas tasyaradhanam ihate\nlabhate ca tatah Kaman mayaiva vihitan hi tan (7.22)", "Firmly established (yukta) in that faith, he engages in the worship of that\nform; from which he obtains his desires, though I am the true dispenser."],
  "23" : ["antavat tu phalam tesam tad bhavaty alpa-medhasam\ndevan deva-yajo yanti mad-bhakta yanti mam api (7.23)", "However, finite is the reward of such a man of little intelligence. To the\ndeities go the worshippers of the deities, but My devotees come to Me."],
  "24" : ["avyaktam vyaktim apannam manyante mam abuddhayah\nparam bhavam ajananto mamavyayam anuttamam (7.24)", "The foolish ones think I am the Unmanifested, as having manifestation,\nknowing not My supreme nature, immutable and superior."],
  "25" : ["naham prakasah sarvasya yoga-maya-samavrtah\nmudho \'yam nabhijanati loko mam ajam avyayam (7.25)", "I am not revealed to all, because concealed (as I am) by Yoga-Maya (the\ncreative power of yoga, all things being the thought-forms of the One). This\ndeceived world knows Me not, the Unborn and Changeless."],
  "26" : ["vedaham samatitani vartamanani carjuna\nbhavisyani ca bhutani mam tu veda na kascana (7.26)", "I know, O Arjuna, all beings past, present and yet to come, but no one\nknows Me."],
  "27" : ["iccha-dvesa-samutthena dvandva-mohena bharata\nsarva-bhutani sammoham sarge yanti parantapa (7.27)", "Due to the delusion of the pairs of opposites (or, the dualities, dvandva),\narising from like and dislike (attraction and repulsion), O Bharata (Arjuna),\nall contingent beings are subject to illusion at birth, O Parantapa (O harasser of foes, Arjuna)."],
  "28" : ["yesam tv anta-gatam papam jananam punya-karmanam\nte dvandva-moha-nirmukta bhajante mam drdha-vratah (7.28)", "But those men of pure deeds whose sins have come to an end, released from\nthe delusive pairs of opposites (the dualities), steadfast in their vows, they\nworship Me."],
  "29" : ["jara-marana-moksaya mam asritya yatanti ye\nte brahma tad viduh krtsnam adhyatmam karma cakhilam (7.29)", "They who, putting their trust in Me, striving for liberation (Moksa) from\ndecay and death, they realise in full the Brahman, the Self and all action(karma)."],
  "30" : ["sadhibhutadhidaivam mam sadhiyajnam ca ye viduh\nprayana-kale \'pi ca mam te vidur yukta-cetasah (7.30)", "Those who realise Me in Adhibhuta (physical region), in the Adhidaiva (the\nspiritual or divine region), and in that of Adhiyajna (region of sacrifice),\nsteadfastly realise Me, even at the time of death."]
}
