// My Bhagavad Gita
// ch08.js
//
// This file holds the verses and translations of chapter eight from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author Vivek
// If you edit this file, add yourself as an author!

"8" : {
  "1" : ["arjuna uvaca\nkim tad brahma kim adhyatmam kim karma purusottama\nadhibhutam ca kim proktam adhidaivam kim ucyate (8.01)", "Arjuna said: What is That (tad) Brahman? What is Adhyatma (spiritual\nlight, self-knowledge), and what is action (Karma), O Purushottama (O\nKrsna). And, what is Adhibhuta (contingent beings, the physical region)?\nAlso, what is called Adhidaiva (the spiritual or divine region)?"],
  "2" : ["adhiyajnah katham ko \'tra dehe \'smin madhusudana\nprayana-kale ca katham jneyo \'si niyatatmabhih (8.02)", "What is the meaning of Adhiyajna (the Lord of sacrifice), and who is in this\nbody, O Madhusudana (Krsna)? Also, how at the time of death, are you to\nbe known by the self -controlled?"],
  "3" : ["sri-bhagavan uvaca\naksaram brahma paramam svabhavo \'dhyatmam ucyate\nbhuta-bhavodbhava-karo visargah karma-samjnitah (8.03)", "The Supreme Lord said: The Imperishable (Akshara) is Brahman, the\nSupreme Being (Cosmic Intelligence); His essential nature (svabhdva) is\ncalled Adhyatma (Self-knowledge); the creative force (visarga) is known as\n\'action\' (karma)."],
  "4" : ["adhibhutam ksaro bhavah purusas cadhidaivatam\nadhiyajno \'ham evatra dehe deha-bhrtam vara (8.04)", "Knowledge of Adhibhuta (of contingent beings) is My perishable existence,\nand Purusha (god-man, living entity, living soul) is the divine (spiritual) \nregion (Adhidaivata). The Adhiyajna (the Lord of sacrifice, Entity of sacrifice) \ntells of Me here in this body, O best of the embodied (Arjuna)."],
  "5" : ["anta-kale ca mam eva smaran muktva kalevaram\nyah prayati sa mad-bhavam yati nasty atra samsayah (8.05)", "The one, who, at the time of death, leaving the body goes forth thinking of\nMe alone, accedes to My divinity (mad-bhdva), there is no doubt about this."],
  "6" : ["yam yam vapi smaran bhavam tyajaty ante kalevaram\ntarn tarn evaiti Kaunteya sada tad-bhava-bhavitah (8.06)", "On whatever form (bhava) a man thinks about at the time of passing, that\nalone does he accede, O son of Kunti (Arjuna), because he has ever been\nengaged in the thought thereof."],
  "7" : ["tasmat sarvesu kalesu mam anusmara yudhya ca\nmayy arpita-mano-buddhir mam evaishyasy asamsayah (8.07)", "Therefore, at all times only remember Me and fight. With mind and\nintellect fixed on Me, you will without doubt come to Me."],
  "8" : ["abhyasa-yoga-yuktena cetasa nanya-gamina\nparamam purusam divyam yati parthanucintayan (8.08)", "Let one\'s thoughts be integrated in the yoga of constant practice, not going\nover to anything else; so, by constantly meditating, O Partha (Arjuna) , one\nreaches the Supreme, Resplendent Purusha (the All-Highest)."],
  "9" : ["kavim puranam anusasitaram anor aniyamsam anusmared yah\nsarvasya dhataram acintya-rupam aditya- varnam tamasah parastat (8.09)", "One who meditates on the Omniscient, the Ancient Seer, the Ruler of all\nthings, smaller than the atom, the Dispenser of all, whose form is\ninconceivable, who is as radiant as the sun beyond the darkness;"],
  "10" : ["prayana-kale manasacalena bhaktya yuktoyoga-balena caiva\nbhruvor madhye pranam avesya samyak sa tarn param purusam upaiti\ndivyam (8.10)", "And who, at the time of death, with a steady (yukta) mind sustained by\ndevotion, and the power of yoga properly fixing the vital breath (prdna) \nright between the eyebrows, he reaches the Supreme, Resplendent Purusha."],
  "11" : ["yad aksaram veda-vido vadanti visanti yad yatayo vita-ragah\nyad icchanto brahmacaryam caranti tat te padam sangrahena pravaksye (8.11)", "The imperishable goal called aksara (Brahman, Aksara Brahman) of which\nthe Vedic scholars declare, into which the controlled and passion-free\nSanyasins (ascetics) enter, desiring that which the Brahmacharya (the vow\nof continence) prescribes, that path will I declare to you in brief."],
  "12" : ["sarva-dvarani samyamya mano hrdi nirudhya ca\nmurdhny adhayatmanah pranam asthito yoga-dharanam (8.12)", "All the gates of the body closed up, the mind confined within the heart,\nfixing one\'s life-breath in the head, engaged in firm yogic practices,\npronouncing the \"OM\", the one-syllabled Brahman, thinking on Me, he\nwho goes forth, leaving the body, treads the highest path (goes to the high\ngoal or refuge)."],
  "13" : ["om ity ekaksaram brahma vyaharan mam anusmaran\nyah prayati tyajan deham sa yati paramam gatim (8.13)", "All the gates of the body closed up, the mind confined within the heart,\nfixing one\'s life-breath in the head, engaged in firm yogic practices,\npronouncing the \"OM\", the one-syllabled Brahman, thinking on Me, he\nwho goes forth, leaving the body, treads the highest path (goes to the high\ngoal or refuge)."],
  "14" : ["ananya-cetah satatam yo mam smarati nityasah\ntasyaham sulabhah Partha nitya-yuktasya yoginah (8.14)", "Who bears Me in mind unceasingly, thinking of nothing else at all, to him I\nam easily attainable, O Partha (Arjuna), of this ever integrated yogi."],
  "15" : ["mam upetya punar janma duhkhalayam asasvatam\nnapnuvanti mahatmanah samsiddhim paramam gatah (8.15)", "Having come to Me, these noble souls are no longer subject to rebirth, that\ntransitory abode of pain, not unending, for they have reached the highest\nperfection (sansiddhi, the supreme prize)."],
  "16" : ["a-brahma-bhuvanal lokah punar avartino \'rjuna\nmam upetya tu Kaunteya punar janma na vidyate (8.16)", "The worlds (spheres), beginning with the world (sphere) of Brahman,\ndissolve and evolve, but he who comes to Me, O son of Kunti (Arjuna), there\nis no rebirth."],
  "17" : ["sahasra-yuga-paryantam ahar yad brahmano viduh\nratrim yuga-sahasrantam te \'ho-ratra-vido janah (8.17)", "Those who know that a thousand yugas (ages) lasts one day of Brahma (the\nCreator), and for a thousand yugas (ages) one such night. This knowing,\nthey know day and night."],
  "18" : ["avyaktad vyaktayah sarvah prabhavanty ahar-agame\nratry-agame praliyante tatraivavyakta-samjnake (8.18)", "From the Unmanifested all things manifest proceed at the coming of the\nday; and then at the coming of the night they merge again, even in \"That\"called the Unmanifested."],
  "19" : ["bhuta-gramah sa evayam bhutva bhutva praliyate\nratry-agame \'vasah Partha prabhavaty ahar-agame (8.19)", "This whole host of beings, coming into being repeatedly, is helplessly\ndissolved at the coming of the night, O Partha {Arjuna), and at dawn of day,\nit rises up again."],
  "20" : ["paras tasmat tu bhavo \'nyo \'vyakto \'vyaktat sanatanah\nyah sa sarvesu bhutesu nasyatsu na vinasyati (8.20)", "However, beyond this unmanifested there is yet another which is\nUnmanifested and Eternal, which does not perish when all contingent\nbeings perish."],
  "21" : ["avyakto \'ksara ity uktas tarn ahuh paramam gatim\nyam prapya na nivartante tad dhama paramam mama (8.21)", "That Unmanifested, said to be \"the Indestructible\", \"That\" (tad), they say is\nthe supreme goal (refuge). They who reach it return not. That is My\nsupreme abode."],
  "22" : ["purusah sa parah Partha bhaktya labhyas tv ananyaya\nyasyantah-sthani bhutani yena sarvam idam tatam (8.22)", "That Supreme Purusha (highest Spirit), O Partha (Arjuna), within Whom all\ncreation dwell, and by Whom all this universe was spun (pervaded), is\nattainable by love and worship (bhakti), and nothing else."],
  "23" : ["yatra kale tv anavrttim avrttim caiva yoginah\nprayata yanti tam kalam vaksyami bharatarsabha (8.23)", "Now, I shall declare, O best of the Bharatas (Arjuna), the time in which the\nyogis set forth never to return, and also the time they set forth to return."],
  "24" : ["agnir jyotir ahah suklah san masa uttarayanam\ntatra prayata gacchanti brahma brahma-vido janah (8.24)", "Fire, light, day, the moon\'s light fortnight, the six months of sun\'s northern\npath, then departing, the knowers of Brahman, go the Brahman."],
  "25" : ["dhumo ratris tatha krsnah san-masa daksinayanam\ntatra candramasam jyotir yogi prapya nivartate (8.25)", "Smoke, night, the moon\'s dark fortnight, the six months of sun\'s southern\ncourse, the yogi (dying) during these, reaches the light of the moon, and\nback he comes again (reincarnates)."],
  "26" : ["sukla-krsne gati hy ete jagatah sasvate mate\nekaya yaty anavrttim anyayavartate punah (8.26)", "These courses of light and dark are thought to be the eternal paths of the\nworld; by the one man goes to no return, and by the other one returns again\n(rebirth, reincarnation)."],
  "27" : ["naite srti partha janan yogi muhyati kascana\ntasmat sarvesu kalesu yoga-yukto bhavarjuna (8.27)", "O Partha (Arjuna), knowing these paths the yogi is not deluded; therefore,\nat all times be ever in yoga integrated, O Arjuna."],
  "28" : ["vedesu yajnesu tapahsu caiva danesu yat punya-phalam pradistam\natyeti tat sarvam idam viditva yogi param sthanam upaiti cadyam (8.28)", "Knowing this, the yogi rises above the fruits of meritorious deeds attached\nto the study of the Vedas, the sacrifices, austerities, and the almsgiving,\nreaching the Supreme primeval State (sthdna)."]
}
