// My Bhagavad Gita
// ch09.js
//
// This file holds the verses and translations of chapter nine from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author Vivek Mallampati
// @author
// If you edit this file, add yourself as an author!

"9" : {
  "1" : ["sri-bhagavan uvaca\nidam tu te guhyatamam pravaksyamy anasuyave\njnanam vijnana-sahitam yaj jnatva moksyase \'subhat(9.01)", "The Supreme Lord said: Since you are not disapproving, I shall now\ndeclare to you this greatest mystery of knowledge (jndna) compatible with\nexperience (vyndna), and as by knowing it, you will be delivered from evil."],
  "2" : ["raja-vidya raja-guhyam pavitram idam uttamam\npratyaksavagamam dharmyam su-sukham kartum avyayam(9.02)", "This is kingly science, kingly secret, the supreme sanctifier, immediately\nrealisable, unopposed to Dharma (conformed to righteousness), very easy to\ncarry out, and abiding forever."],
  "3" : ["asraddadhanah Purusa dharmasyasya parantapa\naprapya mam nivartante mrtyu-samsara-vartmani(9.03)", "O Parantapa (O vanquisher of foes, Arjuna), men who have no faith in this\nDharma (law of righteousness), fail to reach Me, but return to the path of\nthe mortal world."],
  "4" : ["maya tatam idam sarvam jagad avyakta-murtina\nmat-sthani sarva-bhutani na caham tesv avasthitah(9.04)", "In My Unmanifested form, this entire universe is pervaded: in Me subsist\nall beings, but I do not abide in them."],
  "5" : ["na ca mat-sthani bhutani pasya me yogam aisvaram\nbhuta-bhrn na ca bhuta-stho mamatma bhuta-bhavanah(9.05)", "However, contingent beings do not subsist in Me; consider My sovereign\nyoga (power)\\ I sustain all beings, though not dwelling in them; My Self is\ncausing them to be."],
  "6" : ["yathakasa-sthito nit yam vayuh sarvatra-go mahan\ntatha sarvani bhutani mat-sthan ity upadhara ya(9.06)", "As in space (akasa) subsists the mighty wind moving everywhere, so too do\nall contingent beings subsist in Me. Know this."],
  "7" : ["sarva-bhutani Kaunteya prakrtim yanti mamikam\nkalpa-ksaye punas tani kalpadau visrjamy aham(9.07)", "O son of Kunti (O Kaunteya, Arjuna), all contingent beings enter My lower\nNature (prakrti) at the end of a Kalpa (aeon); and, again when another\nKalpa starts, I emanate them forth again."],
  "8" : ["prakrtim svam avastabhya visrjami punah punah\nbhuta-gramam imam krtsnam avasam prakrter vasat(9.08)", "Firmly fixed in My material Nature (prakrti), ever again I emanate all this\nmultitude of beings, powerless themselves, under the control of the material\nNature (prakrti)."],
  "9" : ["na ca mam tani karmani nibadhnanti dhananjaya\nudasina-vad asinam asaktam tesu karmasu(9.09)", "O Dhananjaya (Arjuna), these acts of Mine bind Me not, nor limit Me:\nremaining like one indifferent, unattached to those actions."],
  "10" : ["ma yadh yaksena prakrtih su yate sa-caracaram\nhetunanena kaunte ya jagad viparivartate(9.10)", "Because of My Nearness, the material Nature (prakrti) produces all this, the\nmoving and unmoving, because of that, O son of Kunti (Arjuna), the world\nkeeps rotating."],
  "11" : ["avajananti mam mudha manusim tanum asritam\nparam bhavam ajananto mama bhuta-mahesvaram(9.11)", "Fools scorn Me, for having assumed a human form, not knowing My\nsupreme Nature (bhdva), the great Lord of contingent beings."],
  "12" : ["moghasa mogha-karmano mogha-jnana vicetasah\nraksasim asurim caiva prakrtim mohinim sritah(9.12)", "Vain their hopes and vain their deeds, empty of knowledge, devoid of\ndiscrimination, they embrace a monstrous devilish nature, leading them\nastray."],
  "13" : ["mahatmanas tu mam Partha daivim prakrtim asritah\nbhajanty ananya-manaso jnatva bhutadim avyayam(9.13)", "But the Mahatmas (Mighty Souls), O Partha (Arjuna), taking up their stand\nin My divine Nature (prakrti), worship with minds intent on\nnaught but Me, as the imperishable source of all beings."],
  "14" : ["satatam kirtayanto mam yatantas ca drdha-vratah\nnamasyantas ca mam bhaktya nit ya-yukta upasate(9.14)", "Always do they glorify Me, strenuous, firm in vows, bowing down to Me,\ndevoted in their love (bhakti) ever integrated, they worship Me."],
  "15" : ["jnana-yajnena capy an ye yajanto mam upasate\nekatvena prthaktvena bahudha visvato-mukham(9.15)", "Others again sacrificing with the sacrifice of knowledge, worship Me as One\nand yet as Manifold, with face turned in various ways and guise."],
  "16" : ["aham kratur aham yajnah svadhaham aham ausadham\nmantro \'ham aham evajyam aham agnir aham hutam(9.16)", "I am the rite, I am the sacrifice, I am the food offered to ancestors, I am the\nhealing herb, I am the mantra, I am the sacred butter (clarified butter, Ghi),\nI am the fire, and I the oblation (offered in the fire)."],
  "17" : ["pitaham asya jagato mata dhata pitamahah\nvedyam pavitram omkara rk sama yajur eva ca(9.17)", "I am the Father of this world, the Mother, the Supporter (Creator or\nSustainer), the Grandsire, I am the Knowable, I am the Sacred Syllable\n\"OM\" (the vessel of purity, omkara), and also the Rg, Sama and Yajur (the\nthree Vedas)."],
  "18" : ["gatir bharta prabhuh sakai nivasah saranam suhrt\nprabhavah pralayah sthanam nidhanam bijam avyayam(9.18)", "I am the Goal, the Sustainer, the Lord, the Witness, the Abode, the Shelter,\nthe Friend, the Origin, the Dissolution, the Foundation, the Treasure house,\nand the Imperishable Seed. "],
  "19" : ["tapamy aham aham varsam nigrhnamy utsrjami ca\namrtam caiva mrtyus ca sad asac caham Arjuna(9.19)", "I give heat, I hold back and release the rain, I am immortality as well as\ndeath, the existence and the non-existence too, O Arjuna."],
  "20" : ["trai-vidya mam soma-pah puta-papa yajnair istva svar-gatim prarthayante\nte punyam asadya surendra-lokam asnanti divyan divi deva-bhogan(9.20)", "The knowers of the three Vedas, the Soma -drinkers, the purified from sin,\nworshipping Me with sacrifice, seeking from Me the way of heaven; they,\nascending to the holy world of the Lord of the Devas, taste in heaven the\ngod\'s celestial joys."],
  "21" : ["te tarn bhuktva svarga-lokam visalam ksine punye martya-lokam visanti\nevam trayi-dharmam anuprapanna gatagatam kama-kama labhante(9.21)", "They, once having enjoyed the spacious expanse of heaven-world (svarga),\ntheir merit (punya) exhausted, come back to the world of the mortals. And\nso, it is that those adhering to the three Vedas only, desiring (objects of...)\ndesires, they attain that which comes and goes (the transitory)."],
  "22" : ["anan yas cintayanto mam ye janah paryupasate\ntesam nit yabhi yuktanam yoga-ksemam vahamy aham(9.22)", "To those who meditate on Me alone, thinking of no other, worshipping Me,\never perseveringly, I provide gain and security."],
  "23" : ["ye \'py anya-devata-bhakta yajante sraddhayanvitah\nte \'pi mam eva Kaunteya yajanty avidhi-purvakam(9.23)", "Even those who worship other deities full of faith, they also worship Me, O\nson of Kunti (Arjuna), though contrary to ancient norms (or in ignorance)."],
  "24" : ["aham hi sarva-yajnanam bhokta ca prabhur eva ca\nna tu mam abhijananti tattvenatas cyavanti te(9.24)", "Because it is I who of all acts of sacrifice am the Beneficiary and Lord, but\nthey do not know Me in Essence, and so they fail."],
  "25" : ["yanti deva-vrata devan pitrn yanti pitr-vratah\nbhutani yanti bhuteiya yanti mad-yajino \'pi mam(9.25)", "Those who worship the deities go to the deities, to the ancestors their\nvotaries, to the disembodied spirits the worshippers of these, but My\nworshippers come to Me."],
  "26" : ["patram puspam phalam to yam yo me bhaktya prayacchati\ntad aham bhakty-upahrtam asnami prayatatmanah(9.26)", "Whoever with devotion (bhakti) gives Me a leaf, a flower, a fruit, water, that\ndo I accept, from the self-conquered, for it was devotion that made the\noffering."],
  "27" : ["yat karosi yad asnasi yaj juhosi dadasi yat\nyat tapas yasi Kaunteya tat kurusva mad-arpanam(9.27)", "Whatever you do, whatever you eat, whatever you offer up in sacrifice or\ngive away in alms, whatever austerity you may perform, O son of Kunti\n(Arjuna), do it as an offering to Me."],
  "28" : ["subhasubha-phalair evam moks yase karma-bandhanaih\nsannyasa-yoga-yuktatma vimukto mam upaisyasi(9.28)", "In this way, you will be free from the bonds of action, whose fruits are good\nand evil; by this attitude you will be yourself integrated by the yoga of\nrenunciation, and liberated you will draw nigh to Me."],
  "29" : ["samo ham sarva-bhutesu na me dvesyo \'sti na priyah\nye bhajanti tu mam bhakt ya mayi te tesu capy aham(9.29)", "The same am I to all contingent beings, none do I hate and none do I fondly\nlove (priya). However, those who worship Me with devotion, abide in Me,\nand I in them."],
  "30" : ["api cet su-duracaro bhajate mam ananya-bhak\nsadhur eva sa mantavyah samyag vyavasito hi sah(9.30)", "Even if the most sinful worships Me with dedicated loving devotion, he\nmust be regarded as a righteous, for his resolve is right."],
  "31" : ["ksipram bhavati dharmatma sasvac-chantim nigacchati\nkaunteya pratijanihi na me bhaktah pranasyati(9.31)", "Quite soon will his self be imbued with Dharma (dharmatma, righteousness),\nand obtain eternal rest. O son of Kunti (Arjuna), of this be certain: My\ndevotee perishes never."],
  "32" : ["mam hi partha vyapasrit ya ye \'pi syuh papa-yonayah\nstriyo vaishyas tatha sudras te \'pi yanti param gatim(9.32)", "Because those who find refuge in Me, O Partha (Arjuna), base-born though\nthey may be, women, Vaishyas (the merchant caste), even Shudras (the\nmanual labouring class), even they attain the Supreme Goal."],
  "33" : ["kim punar brahmanah punya bhakta rajarsayas tatha\nanityam asukham lokam imam prapya bhajasva mam(9.33)", "How much more, then, the Holy Brahmanas, and devoted royal seers!\nHaving come to this fleeting joyless world, do commune with Me in love (bhaj)."],
  "34" : ["man-mana bhava mad-bhakto mad-yaji mam namaskuru\nmam evaishyasi yuktvaivam atmamam mat-parayanah(9.34)", "On Me fix your mind; be devoted to Me; sacrifice to Me; prostrate to Me.\nHaving made yourself integrated in Me, taking Me as the Supreme Goal,\nyou shall certainly come to Me."]
}
