// My Bhagavad Gita
// ch10.js
//
// This file holds the verses and translations of chapter ten from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"10" : {
  "1" : ["sri-bhagavan uvaca\nbhuya eva maha-baho srnu me paramam vacah\nyat te \'ham priyamanaya vaks yami hita-kamyaya (10.01)", "The Supreme Lord said: O mighty-armed {Arjuna), once again listen to My\nsupreme word which I will declare to you, for therein is your satisfaction\n(for you are beloved of Me), , and your welfare is My wish."],
  "2" : ["na me viduh sura-ganah prabhavam na maharsayah\naham adir hi devanam maharsinam ca sarvasah (10.02)", "None knows My origin (prabhava: Great Lordly Power), nor the hosts of\nGods, nor the Great Rishis (a rishi is someone who has completed his human\nevolution, but remaining in the super-physical regions in touch with planet\nEarth. Also, a name used for great teachers): for I am the off -spring (source)\nof the Gods themselves and the Great Rishis."],
  "3" : ["yo mam ajam anadim ca vetti loka-mahesvaram\nasammudhah sa martyesu sarva-papaih pramucyate (10.03)", "He who knows Me as Unborn, and Beginningless, Supreme Lord of the\nworlds (the universe or cosmos), he, among mortals is not deceived, and\nfreed from all sins."],
  "4" : ["buddhir jnanam asammohah ksama satyam damah samah\nsukham duhkham bhavo \'bhavo bhayam cabhayam eva ca (10.04)", "Intellect (buddhi), knowledge, freedom from fallacy, patience, truth,\nrestraint, calmness, pleasure, pain, birth (existence), death (non-existence),\nfear and fearlessness as well."],
  "5" : ["ahimsa samata tustis tapo danam yaso \'yasah\nbhavanti bhava bhutanam matta eva prthag-vidhah (10.05)", "None-violence, equanimity (samata), content, austerity, almsgiving, fame\nand infamy, these are the dispositions (bhava) of contingent beings, and\nfrom Me they arise in all their diversity."],
  "6" : ["maharsayah sapta purve catvaro manavas tatha\nmad-bhava manasajata yesam loka imah prajah (10.06)", "The seven Great Rishis, as well as the ancient Four, and also the Manus\n(progenitors of mankind) originating in Me were born of My mind; from\nthem arose all living beings in the world."],
  "7" : ["etam vibhutim yogam ca mama yo vetti tattvatah\nso vikalpena yogena yujyate natra samsayah (10.07)", "He who knows in truth that sovereignty and yoga of Mine, is endowed with\nfirm yoga. Herein there is no doubt."],
  "8" : ["aham sarvasya prabhava mattah sarvam pravartate\niti matva bhajante mam budha bhava-samanvitah (10.08)", "I am the origin of all; all things evolve from Me: this knowing, the wise\ncommune perseveringly with (bha-j) Me."],
  "9" : ["mac-citta mad-gata-prana bodhayantah parasparam\nkathayantas ca mam nityam tusyanti ca ramanti ca (10.09)", "With their minds fixed on Me, with their life hidden in Me, enlightening one\nanother, ever conversing about Me, they are happy and joyful."],
  "10" : ["tesam satata-yuktanam bhajatam priti-purvakam\ndadami buddhi-yogam tarn yena mam upayanti te (10.10)", "And since they are ever integrated and commune with (bhaj-) Me in love\n(priti), I give them the yoga of discrimination (buddhi-yoga, the discipline of\nmind), by which they draw near to Me."],
  "11" : ["tesam evanukampartham aham ajnana-jam tamah\nnasayamy atma-bhava-stho jnana-dipena bhasvata (10.11)", "Out of pure loving concern for them, within their Self, I dispel the darkness\nborn of ignorance by the shining lamp of knowledge."],
  "12" : ["arjuna uvaca\nparam brahma param dhama pavitram paramam bhavan\npurusam sasvatam divyam adi-devam ajam vibhum (10.12)", "Arjuna said: You are the Supreme Brahman, the Supreme Abode (home,\ndhama), the Supreme Vessel of Purity, the Permanent, the Divine Being,\nPrimeval among the Gods, the Unborn, the Omnipresent."],
  "13" : ["ahus tvam rsayah sarve devarsir naradas tatha\nasito devalo vyasah svayam caiva bravisi me (10.13)", "This is highly praised about You by all the Rishis, as also by the divine\nRishi Narada, and by Asita, Devela, Vyasa, and now You Yourself tell it to\nme."],
  "14" : ["sarvam etad rtam manye yan mam vadasi kesava\nna hi te bhagavan vyaktim vidur deva na danavah (10.14)", "All this I hold as true what you are saying to me, O Kesava {Krsna). Neither\nthe Gods {Devas) nor demons {Davanas, Asuras), O Lord, understand Your\norigin."],
  "15" : ["svayam evatmanatmanam vettha tvam purusottama\nbhuta-bhavana bhutesa deva-deva jagat-pate (10.15)", "You, Yourself, know Yourself as Your \"Self, O Supreme Purushottama,\nSource of contingent beings, Lord of contingent beings, O God of gods, and\nLord of the universe {cosmos)."],
  "16" : ["vaktum arhasy asesena divya hy atma-vibhutayah\nyabhir vibhutibhir lokan imams tvam vyapya tisthasi (10.16)", "Describe to me, I pray, in every single detail of Your divine manifestations\nby which glory You remain pervading all these worlds (planets, spheres\nwithin the Cosmos)."],
  "17" : ["katham vidyam aham yogims tvam sada paricintayan\nkesu kesu ca bhavesu cintyo \'si bhagavan maya (10.17)", "How am I to know You, O Supreme Yogi, by constant meditation? And, in\nwhat various forms are You, O Supreme Lord, to be thought of by me?"],
  "18" : ["vistarenatmano yogam vibhutim ca janardana\nbhuyah kathaya trptir hi srnvato nasti me \'mrtam (10.18)", "Tell me again in detail, Your yogic power (creative power) and Your\nmanifestations, O Janardana (Krsna): For as I listen to Your life-infusing\nwords, I cannot have enough."],
  "19" : ["sri-bhagavan uvaca\nhanta te kathayisyami divya hy atma-vibhutayah\npradhanyatah kuru-srestha nasty anto vistarasya me (10.19)", "The Supreme Lord said: See, I shall now explain to you My divine\nmanifestations in their prominences, O best of the Kurus (Arjuna), for of the\nreach there is no end."],
  "20" : ["aham atma Gudakesa sarva-bhutasaya-sthitah\naham adis ca madhyam ca bhutanam anta eva ca (10.20)", "O Gudakesa {Arjuna), I am the Self established in the hearts of all\ncontingent beings; I am the beginning, the middle, and also the end of all\ncontingent beings too."],
  "21" : ["adityanam aham visnur jyotisam ravir amsuman\nmaricir marutam asmi naksatranam aham sasi (10.21)", "Among the Adityas I am Vishnu; among the radiances, the resplendent\nSun; I am Marichi of the Maruts; the moon among the other stars."],
  "22" : ["vedanam sama-vedo \'smi devanam asmi vasavah\nindriyanam manas casmi bhutanam asmi cetana (10.22)", "Of the Vedas I am the Sama-Veda; I am Vasava among the Gods (Devas);\namong the senses I am the mind, among contingent beings I am\nconsciousness."],
  "23" : ["rudranam sankaras casmi vitteso yaksa-raksasam\nvasunam pavakas casmi meruh sikharinam aham (10.23)", "I am Siva among the Rudras {Celestial Beings, eleven in number); I am\nKubera (the Lord of Wealth) among sprites and monsters; I am fire among\nthe Vasus (Celestial Beings, eight in number); and, I am Meru among the\nmountains."],
  "24" : ["purodhasam ca mukhyam mam viddhi partha brhaspatim\nsenaninam aham skandah sarasam asmi sagarah (10.24)", "And of the priesthood (household of priests) observe Me, O Partha (Arjuna),\nas the chief Brhaspati; among the army generals I am Skanda (God of War);\namong lakes I am the Ocean."],
  "25" : ["maharsinam bhrgur aham giram asmy ekam aksaram\nyajnanam japa-yajno \'smi sthavaranam himalayah (10.25)", "Among the great Rishis I am Bhrgu; of words I am the one syllable \'OM\';\nof sacrifices I am the offering of silent repetitions (Japa) (the japa-yajha\namong the yajnas); of the immovables I am the Himalaya."],
  "26" : ["asvatthah sarva-vrksanam devarsinam ca naradah\ngandharvanam citrarathah siddhanam kapilo munih (10.26)", "Among all trees (\/ am) the Asvattha (fig tree); Narada among the divine\nRishis; Citraratha among the Gandharvas (celestial singers); among\nperfected beings Kapila, the silent Muni."],
  "27" : ["uccaihsravasam asvanam viddhi mam amrtodbhavam\nairavatam gajendranam naranam ca naradhipam (10.27)", "Among horses know that I am Uccaihsravas (name of kingly horse), from\nnectar born (Amrita, the nectar of immortality); among princely elephants\nAiravata; and, among men I am the Monarch."],
  "28" : ["ayudhanam aham vajram dhenunam asmi kamadhuk\nprajanas casmi kandarpah sarpanam asmi vasukih (10.28)", "Of weapons I am the thunderbolt; the Kamadhenu (milk cow of desires)\namong cows; I am Kandarpa (god of love) for the creators of progeny;\namong serpents, I am Vasuki (the serpent king)."],
  "29" : ["anantas casmi naganam varuno yadasam aham\npitrnam aryama casmi yamah samyamatam aham (10.29)", "Among the Nagas I am Ananta; Varuna among water-dwellers; of the\nancestors I am Aryaman; among those who control I am Yama (the god of\ndeath)."],
  "30" : ["prahladas casmi daityanam kalah kalayatam aham\nmrganam ca mrgendro \'ham vainateyas ca paksinam (10.30)", "Among the Diti\'s (semi-human beings) I am Prahlada; Time among those\nwho calculate it; among beasts I am (the lion), the king of beasts; and,\namong birds Garuda ( Visnu \'s bird)."],
  "31" : ["pavanah pavatam asmi ramah sastra-bhrtam aham\njhasanam makaras casmi srotasam asmi jahnavi (10.31)", "Among purifiers I am the wind; Rama among those wielding weapons\n(warriors); I am the crocodile among fishes, and the Jahnavi (Ganges)\namong rivers."],
  "32" : ["sarganam adir antas ca madhyam caivaham arjuna\nadhyatma-vidya vidyanam vadah pravadatam aham (10.32)", "In all creation I am the beginning, the end and the middle too, O Arjuna.\nAmong sciences, I am the science concerning the Self. Of those who debate I\nam the Speech."],
  "33" : ["aksaranam a-karo \'smi dvandvah samasikasya ca\naham evaksayah kalo dhataham visvato-mukhah (10.33)", "I am the first vowel-sound \"A\" among the alphabet; among the\ngrammatical compounds the duality (dvandva); I am also the imperishable\nTime (Aksaya Kdla), the Creator who faces all directions."],
  "34" : ["mrtyuh sarva-haras caham udbhavas ca bhavisyatam\nkirtih srir vak ca narinam smrtir medha dhrtih ksama (10.34)", "I am the all-devouring death, and the origin of all creatures yet to come.\nAmong the feminine (female qualities) I am fame, prosperity, speech,\nmemory, intelligence, constancy, and forgiveness."],
  "35" : ["brhat-sama tatha samnam gayatri chandasam aham\nmasanam marga-sirso \'ham rtunam kusumakarah (10.35)", "Among the Saman hymns I am the Brihat-Saman; among metres the\nGayatri; among months I am Margasirsa (November-December), and\namong seasons the flower-bearing (spring)."],
  "36" : ["dyutam chalayatam asmi teias teiasvinam aham\njayo \'smi vyavasayo \'smi sattvam sattvavatam aham (10.36)", "I am the gambling of the tricksters; I am the splendour of the splendid; I\nam victory, I am effort, and the courage of the brave."],
  "37" : ["vrsninam vasudevo \'smi panda vanam dhananjayah\nmuninam apy aham vyasah kavinam usana kavih (10.37)", "Among the Vrsnis I am (Krsna), Vasudeva\'s son; Dhananjaya (Arjuna)\namong the Pandavas; among the Sages (Munis) I am Vyasa, and among the\npoets the poet Usana."],
  "38" : ["dando damayatam asmi nitir asmi jigisatam\nmaunam caivasmi guhyanam jnanam jnanavatam aham (10.38)", "Among those who discipline I am the rod of chastisement; among those\nwishing victory I am statesmanship; the silence of what is secret; and, the\nknowledge of those who know."],
  "39" : ["yac capi sarva-bhutanam bijam tad aham arjuna\nna tad asti vina yat syan maya bhutam caracaram (10.39)", "What is the seed of all contingent beings, that too I am, O Arjuna. There is\nno being, whether moving or unmoving, that exist without Me."],
  "40" : ["nanto \'sti mama divyanam vibhutinam parantapa\nesa tuddesatah prokto vibhuter vistaro maya (10.40)", "There is no end of My divine manifestations, O Parantapa (O vanquisher of\nfoes, Arjuna). What I have stated is only a brief exposition of the extent of\nMy glories."],
  "41" : ["yad yad vibhutimat sattvam srimad urjitam eva va\ntat tad evavagaccha tvam mama tejo-\'msa-sambhavam (10.41)", "Whatever being is endowed with glory, prosperity or strength, be certain\nthat it derives from a fragment of My splendour."],
  "42" : ["atha va bahunaitena kim jnatena tavarjuna\nvistabhyaham idam krtsnam ekamsena sthito jagat (10.42)", "But what need is there for this detailed knowledge, O Arjuna? I stand\nsupporting the entire universe (cosmos) by a small fragment of Myself."]
}
