// My Bhagavad Gita
// ch11.js
//
// This file holds the verses and translations of chapter eleven from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author Tiger Sun
// @author Sankhya Amaravadi
// If you edit this file, add yourself as an author!

"11" : {
  "1" : ["arjuna uvaca\nmad-anugrahaya paramam guhyam adhyatma-samjnitam\nyat tvayoktam vacas tena moho 'yam vigato mama (11.01)", "Arjuna said: Out of compassion, you have taught me the supreme mystery\nof the Self (Adhyatma, the distinction between the Self and the non-Self, or the\nSelf and the self); by this my delusion has been dispelled."],
  "2" : ["bhavapyayau hi bhutanam srutau vistaraso maya\ntvattah kamala-patraksa mahatmyam api cavyayam (11.02)", "For I have heard of the origin and the dissolution of contingent beings in\ndetail from You, O Lotus-eyed (Krsna), and also Your inexhaustible\ngreatness."],
  "3" : ["evam etad yathattha tvam atmanam paramesvara\ndrastum icchami te rupam aisvaram Purusottama (11.03)", "O Supreme Lord, as You have declared Yourself to be, so it is. However, I\ndesire to see Your Isvara form (Creator and Ruler of the Cosmos), O\nPurushottama (Krsna)."],
  "4" : ["manyase yadi tac chakyam maya drastum iti prabho\nyogesvara tato me tvam- darsayatmanam avyayam (11.04)", "If, O Lord, You think that It can be seen by me, do You, then, O Lord of\nYoga, show me Your imperishable Self."],
  "5" : ["sri-bhagavan uvaca\npasya me partha rupani sataso 'tha sahasrasah\nnana-vidhani divyani nana-varnakrtini ca (11.05)", "The Supreme Lord said: See, O Partha (Arjuna), My forms in their\nhundreds and their thousands; various as they are, divine, numerous in\ncolours and shapes."],
  "6" : ["pasyadityan vasun rudran asvinau marutas tatha\nbahuny adrsta-purvani pasyascaryani Bharata (11.06)", "See the Adityas, the Vasus, the Rudras, the Asvins twain, and the Maruts\ntoo. See, O Bharata (Arjuna), abundant wonders, never seen before."],
  "7" : ["ihaika-stham jagat krtsnam pasyadya sa-caracaram\nmama dehe Gudakesa yac canyad drastum icchasi (11.07)", "Here, today, see the whole universe centred in One, with all that it contains\nof moving and unmoving things (seeing it) in My body, O Gudakesa\n(Arjuna), and whatever else you want to see."],
  "8" : ["na tu mam sakyase drastum anenaiva sva-caksusa\ndivyam dadami te caksuh pasya me yogam aisvaram (11.08)", "However, you are not able to see Me with these eyes of yours, I give you the\ndivine eye to see My Supreme Yoga."],
  "9" : ["sanjaya uvaca\nevam uktva tato rajan maha-yogesvaro harih\ndarsayam asa parthaya paramam rupam aisvaram (11.09)", "Sanjaya said: So saying, O King, the great Lord of Yoga, Hari ( a name of\nVishnu-Krsna), revealed to Partha (Arjuna) His supreme Form as Isvara (the\nSupreme, Sovereign Form)."],
  "10" : ["aneka-vaktra-nayanamanekadbhuta-darshanam\naneka-divyabharanam divyanekodyatayudham (11.10)", "With many mouths and eyes, as well as countless marvellous sights; with\nmany divine ornaments, and many celestial weapons raised on high,"],
  "11" : ["divya-malyambara-dharam divya-gandhanulepanam\nsarvascarya-mayam devam anantam visvato-mukham (11.11)", "Wearing celestial garlands and robes, anointed with divine fragrances, the\nGod all-wonderful, resplendent, boundless, facing on all sides."],
  "12" : ["divi surya-sahasrasya bhaved yugapad utthita\nyadi bhah sadrsi sa syad bhasas tasya mahatmanah (11.12)", "If the splendour of thousands of suns were to blaze out together in the sky,\nthat would be like the brilliance of that Mahatman (of that God so great of\nSelf)."],
  "13" : ["tatraika-stham jagat krtsnam pravibhaktam anekadha\napasyad deva-devasya sarire pandavas tada (11.13)", "There Pandava (Arjuna) saw the entire universe in One converged, yet\ndivided out in multiplicity, in the body of the God of gods."],
  "14" : ["tatah sa vismayavisto hrsta-roma dhananjayah\npranamya sirasa devam krtanjalir abhasata (11.14)", "Then he, Dhananjaya (Arjuna), filled with astonishment, his hair on end,\nbowed down with his head, to the Lord in adoration, speaking with joined\npalms."],
  "15" : ["arjuna uvaca\npasyami devams tava deva dehe sarvams tatha bhuta-visesa-sanghan\nbrahmanam isam kamalasana-stham rsims ca sarvan uragams ca divyan\n(11.15)", "Arjuna said: Within Your Form, O God, I see all the gods, as also the\nvaried multitudes of beings; Brahma, the Lord throned on the lotus-seat,\nand all the Rishis (Sages), and celestial serpents."],
  "16" : ["aneka-bahudara-vaktra-netram pasyami tvam sarvato 'nanta-rupam\nnantam na madhyam na punas tavadim pasyami visvesvara visva-rupa\n(11.16)", "With countless arms, stomachs, mouths and eyes, I see You infinite in forms\non all sides. End, middle or beginning I cannot see in You, O Lord of the\nCosmos, O Cosmic Form."],
  "17" : ["kiritinam gadinam cakrinam ca tejo-rasim sarvato diptimantam\npasyami tvam durniriksyam samantad diptanalarka-dyutim aprameyam\n(11.17)", "Your crown, mace, discus; a mass of magnificence shining everywhere, I do\nsee, hard to look at, blazing as fire, as sun dazzling the gaze, immeasurably\non all sides."],
  "18" : ["tvam aksaram paramam veditavyam tvam asya visvasya param nidhanam\ntvam avyayah sasvata-dharma-gopta sanatanas tvam puruso mato me\n(11.18)", "You are the Imperishable, the Supreme among what can be known. You are\nthe Ultimate Abode of the Universe, the Changeless, and Guardian of the\nEternal Dharma (law of righteousness). In my opinion, You are the\nimmemorial Purusha."],
  "19" : ["anadi-madhyantam ananta-viryam ananta-bahum sasi-surya-netram\npasyami tvam dipta-hutasa-vaktram sva-tejasa visvam idam tapantam\n(11.19)", "I see You as having no beginning, middle or end, infinite in power, of\nnumberless arms, yours eyes the sun and moon; a flaming fire Your mouth,\nburning up this whole universe with Your self-engendered splendour."],
  "20" : ["dyav a-prthivyor idam antaram hi vyaptam tvayaikena disas ca sarvah\ndrstvadbhutam rupam ugram tavedam loka-trayam pravyathitam\nmahatman (11.20)", "O All-highest Self (Mahatman, Krsna), by You alone are filled the earth, the\nheavens, and all the regions that are stretched between. Gazing on this,\nYour marvellous and terrible Form, the three worlds (lokas) tremble."],
  "21" : ["ami hi tvam sura-sangha visanti kecid bhitah pranjalayo grnanti\nsvastity uktva maharsi-siddha-sanghah stuvanti tvam stutibhih\npuskalabhih (11.21)", "See, into You the hosts of Suras (supernatural beings) are entering, some\nterror-struck with joined palms are invoking You. A multitude of great\nRishis and Siddhas cry out, 'AH Hail', and praise You with sublime hymns."],
  "22" : ["rudraditya vasavo ye ca sadhya visve 'svinau marutas cosmapas ca\ngandharva-yaksasura-siddha-sangha viksante tvam vismitas caiva sarve (11.22)", "Rudras, Adityas, Vasus, Sadhyas, Visvadevas, Asvins, Maruts, Csmapas,\nGandharvas, Yaksas, Asuras, and Siddhas, in amazement, are gazing at\nYou."],
  "23" : ["rupam mahat te bahu-vaktra-netram maha-baho bahu-bahuru-padam\nbahudaram bahu-damstra-karalam drstva lokah pravyathitas tathaham (11.23)", "Seeing Your mighty Form, with its countless mouths, eyes, arms, thighs,\nfeet, bellies, and sharp, gruesome tusks, the worlds quake, and I also, O\nmighty-armed (Krsna)."],
  "24" : ["nabhah-sprsam diptam aneka-varnam vyattananam dipta-visala-netram\ndrstva hi tvam pravyathitantar-atma dhrtim na vindami samam ca visno (11.24)", "I see You ablaze with many colours touching the sky, your mouths wide\nopen, and large shining eyes, my inmost self is shaken. I find neither peace\nnor courage, O Vishnu (Krsna)."],
  "25" : ["damstra-karalani ca te mukhani drstvaiva kalanala-sannibhani\ndiso najane na labhe ca sarma prasida devesa jagan-nivasa (11.25)", "I see Your mouths, terrible with tusks, resembling Time's destroying\nflames: I cannot find my bearings, I see no shelter. Have mercy, O God of\ngods, and refuge of the universe."],
  "26" : ["ami ca tvam dhrtarastrasya putrah sarve sahaivavani pala-sanghaih\nbhismo dronah suta-putras tathasau sahasmadiyair api yodha-mukhyaih (11.26)", "All the sons of Dhrtarastra along with a host of kings, Bhlsma, Drona,\nSuta's royal son (Kama), and all the foremost warriors on our side,"],
  "27" : ["vaktrani te tvaramana visanti damstra-karalani bhayanakani\nkecid vilagna dasanantaresu sandrsyante curnitair uttamangaih (11.27)", "Rush into Your frightening mouths with their horrid tusks striking (them)\nwith terror. The heads of some, being caught between your teeth, are being\ncrushed to powder."],
  "28" : ["yatha nadinam bahavo 'mbu-vegah samudram evabhimnukha dravanti\ntatha tavami nara-loka-vira visanti vaktrany abhivijvalanti (11.28)", "As many river floods rush headlong towards the sea, so do these heroes of\nthe world of men enter into Your blazing mouths."],
  "29" : ["yatha pradiptam jvalanam patanga visanti nasaya samrddha-vegah\ntathaiva nasaya visanti lokas tavapi vaktrani samrddha-vegah (11.29)", "As moths hurriedly rush into the lighted blaze for their destruction, so do\nthese creatures pour in a bursting, hurtling haste their own undoing into\nYour mouths."],
  "30" : ["lelihyase grasamanah samantal lokan samagran vadanair j valadbhih\ntejobhir apuryajagat samagram bhasas tavograh pratapanti visno (11.30)", "You are licking up, devouring, worlds, universes, everything with Your\nblazing mouths. The fiery rays of light fill the whole universe with burning\nradiance, O Vishnu (Krsna)."],
  "31" : ["akhyahi me ko bhavan ugra-rupo namo 'stu te deva-vara prasida\nvijnatum icchami bhavantam adyam na hi prajanami tava pravrttim (11.31)", "Tell me who You are, so awful in Form. I bow before You, O best of gods,\nbe merciful. I wish to know You as You are, the Original Being, for I do not\nknow Your works (pravrtti)"],
  "32" : ["sri-bhagavan uvaca\nkalo 'smi loka-ksaya-krt pravrddho lokan samahartum iha pravrttah\nrte 'pi tvam na bhavisyanti sarve ye 'vasthitah pratyanikesu yodhah (11.32)", "The Supreme Lord said: Time am I, now engaged in laying desolate the\nworlds, here ready to consume the people. Even without your involvement,\nnone of all the warriors arrayed there in opposite armies will escape death."],
  "33" : ["tasmat tvam uttistha yaso labhasva jitva satrun bhunksva rajyam\nsamrddham\nmayaivaite nihatah purvam eva nimitta-matram bhava savya-sacin (11.33)", "Therefore, stand up, be triumphant, conquer your enemies and enjoy a\nmagnificent kingdom! For these are all slain by Me already. Be a mere\ninstrument (nimittamdtram\ O Savyasacin (Arjuna, able to shoot arrows with\nthe left hand)."],
  "34" : ["dronam ca bhismam cajayadratham ca karnam tathanyan api yodha-viran\nmaya hatams tvam jahi ma vyathistha yudhyasva jetasi rane sapatnan (11.34)", "Bllsnia, Drona, Jayadratha, Kama, and all the other brave warriors here\nare already slain by Me. Kill them then fearlessly. Fight! You will conquer\nyour rivals in the battle."],
  "35" : ["sanjaya uvaca\netac chrutva vacanam kesavasya krtanjalir vepamanah kiriti\nnamaskrtva bhuya evaha krsnam sa-gadgadam bhita-bhitah pranamya (11.35)", "Sanjaya said: having heard these words of Kesava (Krsna), he (Arjuna),\nwearer of the crown, with joined palms in veneration, trembling,\nprostrating himself to Krsna, spoke again, with stammering voice, and as\nterrified he did obeisance."],
  "36" : ["arjuna uvaca\nsthane hrsikesa tava prakirtya jagat prahrsyaty anurajyate ca\nraksamsi bhitani diso dravanti sarve namasyanti ca siddha-sanghah (11.36)", "Arjuna said: O Hrsikesa (Krsna), the world finds its pleasure and its joy in\npraising You. The Rakshasas, fearing, (monsters, terrifying demons) scatter\nin all directions, and all the hosts of Siddhas (perfected ones) bow down to\nYou."],
  "37" : ["kasmac ca te na nameran mahatman gariyase brahmano 'py adi-kartre\nananta devesa jagan-nivasa tvam aksaram sad-asat tat param yat (11.37)", "And why should they not bow down to You, O Noble Soul (Krsna), who are\neven superior to Brahma (or, 'Brahman '. The whole phrase could mean 'Most\nreverend creator of Brahma or Brahman), You the First cause, Infinite, Go\nof gods, the world's abiding home, Unperishing Sat (Being), Asat (Non-\nBeing), and that which surpasses both (the Supreme)."],
  "38" : ["tvam adi-devah purusah puranas tvam asya visvasya param nidhanam\nvettasi vedyam ca param ca dhama tvaya tatam visvam ananta-rupa (11.38)", "You are the Primal God, Primeval Person, the Supreme receptacle of all\nthat lives, You the knower and what is to be known, the dwelling place\nabove (home: dhama). This entire universe is encompassed by You, Who are\nInfinite in Form."],
  "39" : ["vayur yamo 'gnir varunah sasankah prajapatis tvam prapitamahas ca\nnamo namas te 'stu sahasra-krtvah punas ca bhuyo 'pi namo namas te (11.39)", "You are Vayu (the wind-god) , Yama (the god of death), Agni (the god of fire),\nthe moon, Varuna (water), You are Prajapati (the progenitor of beings), and\nthe primordial Ancestor. All hail, all hail to You, a thousandfold, again and\nagain all hail."],
  "40" : ["namah purastad atha prsthatas te namo 'stu te sarvata eva sarva\nananta-viryamita-vikramas tvam sarvam samapnosi tato 'si sarvah (11.40)", "All hail to You when I stand before You, and when I stand behind You, all\nhail to You wherever I may be, O All. How infinite Your strength, how\nlimitless Your competency! You hold everything, and are therefore All in\nAll."],
  "41" : ["sakheti matva prasabham yad uktam he krsna he yadava he sakheti\najanata mahimanam tavedam maya pramadat pranayena vapi (11.41)", "How thoughtlessly have I called You friend, for so I thought of You,\nunmindful of Your majesty, I addressed you as O Krsna, O Yadava, O\nFriend, carelessly in the fondness of my love."],
  "42" : ["yac cavahasartham asat-krto 'si vihara-sayyasana-bhojanesu\neko 'tha vapy acyuta tat-samaksam tat ksamaye tvam aham aprameyam (11.42)", "Sometimes joking I showed disrespect to You, when we played, rested, sat\nin an assembly or at meals, sometimes together (both alone), or at sight of\nothers, O Achyuta (Krsna), the Immeasurable, I beg Your forgiveness."],
  "43" : ["pitasi lokasya caracarasya tvam asya pujyas ca gurur gariyan\nna tvat-samo 'sty abhyadhikah kuto 'nyo loka-traye 'py apratima-\nprabhava (11.43)", "You are the Father of the moving and unmoving world, You are worthy of\nall honour, the greatest guru of the world. There is none like You, how\ncould there be a greater? Most excellent Your power in the three worlds."],
  "44" : ["tasmat pranamya pranidhaya kayam prasadaye tvam aham isam idyam\npiteva putrasya sakheva sakhyuh priyah priyayarhasi deva sodhum (11.44)", "Therefore, bowing down to You, prostrating my body, longing grace of\nYou, O Adorable Lord; bear with me, I pray you, as father with son, or\nfriend with friend, or lover with the one he loves."],
  "45" : ["adrsta-purvam hrsito 'smi drstva bhayena ca pravyathitam mano me\ntad eva me darsaya deva rupam prasida devesa jagan-nivasa (11.45)", "I have seen that which no one has seen before, and ecstatic is my joy; yet my\nmind is possessed by fear and trembling. Show me, O God, Your other form\nagain, forgive me, O God of gods, Home of the universe!"],
  "46" : ["kiritinam gadinam cakra-hastam icchami tvam drastum aham tathaiva\ntenaiva rupena catur-bhujena sahasra-baho bhava visva-murte (11.46)", "Crowned, with the mace and discus in Your hand, I wish to see You as\nbefore; take up again Four-armed form, O Thousand-armed, to whom\nevery form belongs"],
  "47" : ["sri-bhagavan uvaca\nmaya prasannena tavarjunedam rupam param darsitam atma-yogat\ntejo-mayam visvam anantam adyam yan me tvad anyena na drsta-purvam (11.47)", "The Supreme Lord said: I desired to show you favour, Arjuna,\ndemonstrating to you My Self s mysterious power (dtmayoga) in its All-\nhighest Form, glorious, all-embracing, infinite, primeval, which none has\nseen before except you."],
  "48" : ["na veda-yajnadhyayanair na danair na ca kriyabhir na tapobhir ugraih\nevam-rupah sakya aham nr-loke drastum tvad anyena kuru-pravira (11.48)", "Not by the Vedas, not by sacrifice, not by deep study or the giving of alms,\nnot by rituals or sharp austerity, can I be seen in such a form in the world\nof men: to you alone I have revealed it, O hero of the Kurus (Arjuna)."],
  "49" : ["ma te vyatha ma ca vimudha-bhavo drstva rupam ghoram idrn mameda\nvyapeta-bhih prita-manah punas tvam tad eva me rupam idam prapasya (11.49)", "Do not tremble nor be perplexed, because you have seen this awful Form of\nMine. Banish all fear, and let your heart rejoice: see again that same\nfamiliar form of Mine."],
  "50" : ["sanjaya uvaca\nity arjunam vasudevas tathoktva svakam rupam darsayam asa bhuyah\nasvasayam asa ca bhitam enam bhutva punah saumya-vapur mahatma (11.50)", "Sanjaya said: having so spoken, the son of Vasudeva (Krsna) showed\nArjuna His own form again; and the Noble Soul (Mahatman, the great-souled\none, Krsna) assumed the body of a friend, and consoled him who was\nterrified."],
  "51" : ["arjuna uvaca\ndrstvedam manusam rupam tava saumyam janardana\nidanim asmi samvrttah sa-cetah prakrtim gatah (11.51)", "Arjuna said: Now that I see Your gentle human form again, O Janardana\n(Krsna), I have returned to my senses, and to my normal state."],
  "52" : ["sri-bhagavan uvaca\nsu-durdarsam idam rupam drstavan asi yan mama\ndeva apy asya rupasya nityam darshana-kanksinah (11.52)", "The Supreme Lord said: This, My Form which you have seen is very hard\nto see. Truly, this is the form the gods (devas) themselves are perpetually\nlonging to see."],
  "53" : ["naham vedair na tapasa na danena na cejyaya\nsakya evam-vidho drastum drstavan asi mam yatha (11.53)", "Not by the Vedas or austerity, not by the giving of alms or the performance\nof rituals can I be seen in the way you just saw Me."],
  "54" : ["bhaktya tv ananyaya sakya aham evam-vidho 'rjuna\njnatum drastum ca tattvena pravestum ca Parantapa (11.54)", "But, by devotion to Me alone can I be known and seen in such a Form and\nas I really am, then so enter into Me, O Parantapa (Arjuna, O vanquisher of\nfoes)."],
  "55" : ["mat-karma-krn mat-paramo mad-bhaktah sanga-varjitah\nnirvairah sarva-bhutesu yah sa mam eti Pandava (11.55)", "Perform actions for Me, and make Me your highest goal, be loyal in love\n(bhakta) to me, be unattached, have no hatred for any being at all: for all\nwho do so come to Me, O Pandava (Arjuna)."]
}
