// My Bhagavad Gita
// ch11.js
//
// This file holds the verses and translations of chapter eleven from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author Tiger Sun
// If you edit this file, add yourself as an author!

"11" : {
  "1" : ["arjuna uvaca\nmad-anugrahaya paramam guhyam adhyatma-samjnitam\nyat tvayoktam vacas tena moho 'yam vigato mama (11.01)", "Arjuna said: Out of compassion, you have taught me the supreme mystery\nof the Self (Adhyatma, the distinction between the Self and the non-Self, or the\nSelf and the self); by this my delusion has been dispelled."],
  "2" : ["bhavapyayau hi bhutanam srutau vistaraso maya\ntvattah kamala-patraksa mahatmyam api cavyayam (11.02)", "For I have heard of the origin and the dissolution of contingent beings in\ndetail from You, O Lotus-eyed (Krsna), and also Your inexhaustible\ngreatness."],
  "3" : ["evam etad yathattha tvam atmanam paramesvara\ndrastum icchami te rupam aisvaram Purusottama (11.03)", "O Supreme Lord, as You have declared Yourself to be, so it is. However, I\ndesire to see Your Isvara form (Creator and Ruler of the Cosmos), O\nPurushottama (Krsna)."],
  "4" : ["manyase yadi tac chakyam maya drastum iti prabho\nyogesvara tato me tvam- darsayatmanam avyayam (11.04)", "If, O Lord, You think that It can be seen by me, do You, then, O Lord of\nYoga, show me Your imperishable Self."],
  "5" : ["sri-bhagavan uvaca\npasya me partha rupani sataso 'tha sahasrasah\nnana-vidhani divyani nana-varnakrtini ca (11.05)", "The Supreme Lord said: See, O Partha (Arjuna), My forms in their\nhundreds and their thousands; various as they are, divine, numerous in\ncolours and shapes."],
  "6" : ["pasyadityan vasun rudran asvinau marutas tatha\nbahuny adrsta-purvani pasyascaryani Bharata (11.06)", "See the Adityas, the Vasus, the Rudras, the Asvins twain, and the Maruts\ntoo. See, O Bharata (Arjuna), abundant wonders, never seen before."],
  "7" : ["ihaika-stham jagat krtsnam pasyadya sa-caracaram\nmama dehe Gudakesa yac canyad drastum icchasi (11.07)", "Here, today, see the whole universe centred in One, with all that it contains\nof moving and unmoving things (seeing it) in My body, O Gudakesa\n(Arjuna), and whatever else you want to see."],
  "8" : ["divyam dadami te caksuh pasya me yogam aisvaram (11.08)", "However, you are not able to see Me with these eyes of yours, I give you the\ndivine eye to see My Supreme Yoga."],
  "9" : ["sanjaya uvaca\nevam uktva tato rajan maha-yogesvaro harih\ndarsayam asa parthaya paramam rupam aisvaram (11.09)", "Sanjaya said: So saying, O King, the great Lord of Yoga, Hari ( a name of\nVishnu-Krsna), revealed to Partha (Arjuna) His supreme Form as Isvara (the\nSupreme, Sovereign Form)."],
  "10" : ["aneka-vaktra-nayanamanekadbhuta-darshanam\naneka-divyabharanam divyanekodyatayudham (11.10)", "With many mouths and eyes, as well as countless marvellous sights; with\nmany divine ornaments, and many celestial weapons raised on high,"],
  "11" : ["divya-malyambara-dharam divya-gandhanulepanam\nsarvascarya-mayam devam anantam visvato-mukham (11.11)", "Wearing celestial garlands and robes, anointed with divine fragrances, the\nGod all-wonderful, resplendent, boundless, facing on all sides."],
  "12" : ["divi surya-sahasrasya bhaved yugapad utthita\nyadi bhah sadrsi sa syad bhasas tasya mahatmanah (11.12)", "If the splendour of thousands of suns were to blaze out together in the sky,\nthat would be like the brilliance of that Mahatman {of that God so great of\nSelf)."],
  "13" : ["tatraika-stham jagat krtsnam pravibhaktam anekadha\napasyad deva-devasya sarire pandavas tada (11.13)", "There Pandava (Arjuna) saw the entire universe in One converged, yet\ndivided out in multiplicity, in the body of the God of gods."],
  "14" : ["tatah sa vismayavisto hrsta-roma dhananjayah\npranamya sirasa devam krtanjalir abhasata (11.14)", "Then he, Dhananjaya (Arjuna), filled with astonishment, his hair on end,\nbowed down with his head, to the Lord in adoration, speaking with joined\npalms."],
  "15" : ["arjuna uvaca\npasyami devams tava deva dehe sarvams tatha bhuta-visesa-sanghan\nbrahmanam isam kamalasana-stham rsims ca sarvan uragams ca divyan\n(11.15)", "Arjuna said: Within Your Form, O God, I see all the gods, as also the\nvaried multitudes of beings; Brahma, the Lord throned on the lotus-seat,\nand all the Rishis (Sages), and celestial serpents."],
  "16" : ["aneka-bahudara-vaktra-netram pasyami tvam sarvato 'nanta-rupam\nnantam na madhyam na punas tavadim pasyami visvesvara visva-rupa\n(11.16)", "With countless arms, stomachs, mouths and eyes, I see You infinite in forms\non all sides. End, middle or beginning I cannot see in You, O Lord of the\nCosmos, O Cosmic Form."],
  "17" : ["kiritinam gadinam cakrinam ca tejo-rasim sarvato diptimantam\npasyami tvam durniriksyam samantad diptanalarka-dyutim aprameyam\n(11.17)", "Your crown, mace, discus; a mass of magnificence shining everywhere, I do\nsee, hard to look at, blazing as fire, as sun dazzling the gaze, immeasurably\non all sides."],
  "18" : ["tvam aksaram paramam veditavyam tvam asya visvasya param nidhanam\ntvam avyayah sasvata-dharma-gopta sanatanas tvam puruso mato me\n(11.18)", "You are the Imperishable, the Supreme among what can be known. You are\nthe Ultimate Abode of the Universe, the Changeless, and Guardian of the\nEternal Dharma (law of righteousness). In my opinion, You are the\nimmemorial Purusha."],
  "19" : ["anadi-madhyantam ananta-viryam ananta-bahum sasi-surya-netram\npasyami tvam dipta-hutasa-vaktram sva-tejasa visvam idam tapantam\n(11.19)", "I see You as having no beginning, middle or end, infinite in power, of\nnumberless arms, yours eyes the sun and moon; a flaming fire Your mouth,\nburning up this whole universe with Your self-engendered splendour."],
  "20" : ["dyav a-prthivyor idam antaram hi vyaptam tvayaikena disas ca sarvah\ndrstvadbhutam rupam ugram tavedam loka-trayam pravyathitam\nmahatman (11.20)", "O All-highest Self (Mahatman, Krsna), by You alone are filled the earth, the\nheavens, and all the regions that are stretched between. Gazing on this,\nYour marvellous and terrible Form, the three worlds (lokas) tremble."],
  "21" : ["", ""],
  "22" : ["", ""],
  "23" : ["", ""],
  "24" : ["", ""],
  "25" : ["", ""],
  "26" : ["", ""],
  "27" : ["", ""],
  "28" : ["", ""],
  "29" : ["", ""],
  "30" : ["", ""],
  "31" : ["", ""],
  "32" : ["", ""],
  "33" : ["", ""],
  "34" : ["", ""],
  "35" : ["", ""],
  "36" : ["", ""],
  "37" : ["", ""],
  "38" : ["", ""],
  "39" : ["", ""],
  "40" : ["", ""],
  "41" : ["", ""],
  "42" : ["", ""],
  "43" : ["", ""],
  "44" : ["", ""],
  "45" : ["", ""],
  "46" : ["", ""],
  "47" : ["", ""],
  "48" : ["", ""],
  "49" : ["", ""],
  "50" : ["", ""],
  "51" : ["", ""],
  "52" : ["", ""],
  "53" : ["", ""],
  "54" : ["", ""],
  "55" : ["", ""]
}
