// My Bhagavad Gita
// ch.13js
//
// This file holds the verses and translations of chapter thirteen from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"13" : {
  "1" : ["arjuna uvaca\nprakrtim purusam caiva ksetram ksetra-jnam eva ca\netad veditum icchami jnanam jneyam ca Kesava (13.01)", "Arjuna said: What is Prakriti and Purusha (Matter and Spirit)! What is the\n'Field' and what is the \"Knower of the Field\"? Also, what is knowledge and\nthat which ought to be known? These, Kesava (Krsna), I would like to know."],
  "2" : ["sri-bhagavan uvaca\nidam sariram Kaunteya ksetram ity abhidhiyate\netad yo vetti tarn prahuh ksetra-jna iti tad-vidah (13.02)", "The Supreme Lord said: This body, O son of Kunti (Arjuna), is called the\n'Field' (ksetra), and he who knows it, is the 'Knower of the Field'\n(ksetrajha), by the Sages who understand these things."],
  "3" : ["ksetra-jnam capi mam viddhi sarva-ksetresu bharata\nksetra-ksetrajnayor jnanam yat taj jnanam matam mama (13.03)", "Recognise Me as the Knower of the Field in all Fields (ksetras), O Bharata\n(Arjuna). Knowledge of the Field and the Knower of the Field is in My\nopinion true knowledge."],
  "4" : ["tat ksetram yac ca yadrk ca yad-vikari yatas ca yat\nsa ca yo yat-prabhavas ca tat samasena me srnu (13.04)", "What the Field (ksetra) is and what it is like, what its modifications\nare and which derives from which,\nand who He is (ksetrajna, the Knower of the Field), and what his powers\n(var: nature) are, hear now briefly from Me."],
  "5" : ["rsibhir bahudha gitam chandobhir vividhaih prthak\nbrahma-sutra-padais caiva hetumadbhir viniscitaih (13.05)", "In different ways has it been sung by Rishis, in various distinctive hymns,\nand in suggestive verses about Brahman (Brahma-sutra short terse sayings\nconcerning the Supreme Being), full of reasoning and persuasiveness."],
  "6" : ["maha-bhutany ahankaro buddhir avyaktam eva ca\nindriyani dasaikam ca panca cendriya-gocarah (13.06)", "The great elements, the ego (ahamkara), intellect (buddhi), the\nUnmanifested, the ten senses and the one, and the five sense-objects of the\nsenses (the five organs of knowledge, or senses, the five organs of action, the\nmind, and the objects cognised by each of the five senses);"],
  "7" : ["iccha dvesah sukham duhkham sanghatas cetana dhrtih\netat ksetram samasena sa-vikaram udahrtam (13.07)", "Desire, hate, pleasure, pain, combination (the body), intelligence, and\nconstancy - these, briefly, are called the 'field' together with its associations\n(modifications, transformations)."],
  "8" : ["amanitvam adambhitvam ahimsa ksantir arjavam\nacaryopasanam saucam sthairyam atma-vinigrahah (13.08)", "Humility, modesty, non-violence, forgiveness, uprightness (morality), service\nof the teacher, purity, resoluteness, self-control,"],
  "9" : ["indriyarthesu vairagyam anahankara eva ca\njanma-mrtyu-jara-vyadhi- duhkha-dosanudarshanam (13.09)", "Dispassion towards the things of sense, and also absence of egoism, insight\nof evil into birth, death, old age, disease and pain;"],
  "10" : ["asaktir anabhisvangah putra-dara-grhadisu\nnityam ca sama-cittatvam istanistopapattisu (13.10)", "Detachment, absence of identification of self with son, wife, home and such\nthings, and a constant equal-mindedness in whatever happens, pleasing and\nunpleasing;"],
  "11" : ["mayi cananya-yogena bhaktir avyabhicarini\nvivikta-desa-sevitvam aratir jana-samsadi (13.11)", "Unswerving, concentrated, disciplined devotion to Me in yoga of union,\ndwelling apart in solitary places, taking no pleasure in the company of\nworldly people;"],
  "12" : ["adhyatma-jnana-nityatvam tattva-jnanartha-darshanam\netajjnanam iti proktam ajnanam yad ato 'nyatha (13.12)", "Permanence in the knowledge of the Self (adhyatma),\nperception of the goal of true knowledge, all this is declared to be\nknowledge, all else is ignorance."],
  "13" : ["jneyam yat tat pravaksyami yaj jnatvamrtam asnute\nanadi mat-param brahma na sat tan nasad ucyate (13.13)", "What is to be known I will describe to you, by knowing which one attains\nimmortality: the beginningless Supreme Being {Para-Brahma), which is\nneither 'sat' (being) nor 'asat' (non-being) (lies beyond the cause and effect)',"],
  "14" : ["sarvatah pani-padam tat sarvato 'ksi-siro-mukham\nsarvatah srutimal loke sarvam avrtya tisthati (13.14)", "With hands and feet on every side, with eyes, heads, mouths and ears on\nevery side, He (That) abides in the world, enveloping all."],
  "15" : ["sarvendriya-gunabhasam sarvendriya-vivarjitam\nasaktam sarva-bhrc caiva nirgunam guna-bhoktr ca (13.15)", "Devoid of all the senses, He, yet, sheds light on all their constituents (Gunas,\nthe three modes of Matter or Nature)', unattached, and yet supporting\neverything; free from constituents (Gunas, the three modes of Matter or\nNature), yet, experiencing them."],
  "16" : ["bahir antas ca bhutanam acaram caram eva ca\nsuksmatvat tad avijneyam dura-stham cantike ca tat (13.16)", "Within all beings, and yet outside them; immovable and also movable; by\nreason of His subtlety, He (That, tat) is incapable of being known; far away\nHe (That, tat) stands near."],
  "17" : ["avibhaktam ca bhutesu vibhaktam iva ca sthitam\nbhuta-bhartr ca tajjneyam grasisnu prabhavisnu ca (13.17)", "Undivided, in beings He (That, tat) abides seeming divided: This is 'That'\n(tat) which should be known as the One who upholds, devours and\ngenerates all beings."],
  "18" : ["jyotisam api tajjyotis tamasah param ucyate\njnanam jneyam jnana-gamyam hrdi sarvasya visthitam (13.18)", "That (tat), the Light of all lights is said to be 'Beyond darkness';\nKnowledge, the object of knowledge, and that which can be known only\nthrough knowledge, seated in the hearts of all."],
  "19" : ["iti ksetram tatha jnanam jneyam coktam samasatah\nmad-bhakta etad vijnaya mad-bhavayopapdyate (13.19)", "So, the 'Field' (ksetra, the body), 'Knowledge' and the 'Object of\nKnowledge', have been briefly explained. My devotee, knowing this, enters\ninto My Being."],
  "20" : ["prakrtim purusam caiva viddhy anadi ubhav api\nvikarams ca gunams caiva viddhi prakrti-sambhavan (13.20)", "Know that Prakriti (matter, nature) and Purusha (Self, Atma, Spirit) are both\nwithout commencement; and know also that changes (modifications,\nassociations, transformations) and constituents (Gunas, the three modes of\nMatter or Nature) arise from Prakriti (matter, nature)."],
  "21" : ["karya-karana-kartrtve hetuh prakrtir ucyate\npurusah sukha-duhkhanam bhoktrtve hetur ucyate (13.21)", "Prakriti (matter, nature) is said to be the source cause, of the production of\nthe body and the senses {effect and instruments). Purusha {Self, Atmd, Spirit)\nis said to be the cause, in the experience of pleasures and pains."],
  "22" : ["purusah prakrti-stho hi bhunkte prakrti-jan gunan\nkaranam guna-sango 'sya sad-asad-yoni-janmasu (13.22)", "For this Purusha (Self, Atmd, Spirit) is positioned in Prakriti (matter, nature),\nexperiencing its 'constituents' born of Prakriti. Attachment to the\nconstituents (Gunas, the three modes of Matter or Nature) is instrumental in\ntaking birth in good and bad wombs."],
  "23" : ["upadrastanumanta ca bharta bhokta mahesvarah\nparamatmeti capy ukto dehe 'smin purusah parah (13.23)", "The Supreme Purusha (Transcendental Enjoyer), here in the body, is also\ncalled the Surveyor, the Approver, the Supporter, the One who experiences,\nthe Great Lord and the Supreme Self."],
  "24" : ["ya evam vetti purusam prakrtim ca gunaih saha\nsarvatha vartamano 'pi na sa bhuyo 'bhijayate (13.24)", "He who in this way knows the Purusha (Self, Atma, Spirit) and Prakriti\n(matter, nature) with its constituents (Gunas, the three modes of Matter or\nNature), in whatever condition he may be, does not enter into rebirth."],
  "25" : ["dhyanenatmani pasyanti kecid atmanam atmana\nanye sankhyena yogena karma-yogena capare (13.25)", "Through meditation some see the Self in the self by the Self; others by\nSankhya Yoga (yoga of knowledge), and still others by Karma- Yoga (actions\nwithout fruitive desires)."],
  "26" : ["anye tv evam ajanantah srutvanyebhya upasate\nte 'pi catitaranty eva mrtyum sruti-parayanah (13.26)", "In addition, others, not conversant in these (spiritual or yoga of knowledge),\nworship as they have heard from others; and even them taking their stand\non what they have heard (taking their stand on Scriptures), pass also beyond\ndeath."],
  "27" : ["yavat sanjayate kincit sattvam sthavara-jangamam\nksetra-ksetrajna-samyogat tad viddhi bharatarsabha (13.27)", "Whatever being comes to be, moving or unmoving, O best of the Bharata\n(Arjuna), know this, derives its being from the union of the 'Field' (ksetra)\nand the 'Knower of the Field' (ksetrajna)."],
  "28" : ["samam sarvesu bhutesu tisthantam paramesvaram\nvinasyatsv avinasyantam yah pasyati sa pasyati (13.28)", "He who sees the Supreme Lord abiding ever the same in all contingent\nbeings, immortal in the mortal, he indeed sees."],
  "29" : ["samam pasyan hi sarvatra samavasthitam isvaram\nna hinasty atmanatmanam tato yati param gatim (13.29)", "Perceiving, indeed, the same Lord as equally established everywhere, he\ndoes not destroy the Self (true Self, Higher Self) by the self (self-sense), and in\nthis way, he treads the highest Path (Goal)."],
  "30" : ["prakrtyaiva ca karmani kriyamanani sarvasah\nyah pasyati tathatmanam akartaram sa pasyati (13.30)", "He who perceives that Prakriti (matter, nature) performs all actions, and\nthat the Self (Atmd) engages not in actions, he sees indeed."],
  "31" : ["yada bhuta-prthag-bhavam eka-stham anupasyati\ntata eva ca vistaram brahma sampadyate tada (13.31)", "When one perceives that, the diversity of contingent beings abides in One,\nand from \"That\" (tat) only they radiate, then he reaches the Brahman."],
  "32" : ["anaditvan nirgunatvat paramatmayam avyayah\nsarira-stho 'pi Kaunteya na karoti na lipyate (13.32)", "Because this Supreme Self, imperishable, knows no beginning, no\nconstituent of Matter (of Nature; Gunas, the three modes of matter), though\nseated in the body, O son of Kunti (Arjuna), neither acts, nor is affected in\nany way."],
  "33" : ["yatha sarva-gatam sauksmyad akasam nopalipyate\nsarvatravasthito dehe tathatma nopalipyate (13.33)", "Just as the ether (akasa), pervading everything, knows no defilement on\naccount of its subtlety, so does the Self, though everywhere abiding and\nembodied, know no defilement."],
  "34" : ["yatha prakasayaty ekah krtsnam lokam imam ravih\nksetram ksetri tatha krtsnam prakasayati Bharata (13.34)", "Just as the one Sun lights up this entire universe, so does the 'Knower of the\nField' (ksetrajna) illumine this entire 'Field' (ksetra), O Bharata (Arjuna)."],
  "35" : ["ksetra-ksetrajnayor evam antaram jnana-caksusa\nbhuta-prakrti-moksam ca ye vidur yanti te param (13.35)", "They who by the eyes of knowledge discern the difference between the\n'Field' (ksetra) and the 'Knower of the Field' (ksetrajna), and the\ndeliverance of beings from Prakriti (Matter, the material form), they attain\nthe Supreme."]
}
