// My Bhagavad Gita
// ch14.js
//
// This file holds the verses and translations of chapter fourteen from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"14" : {
  "1" : ["sri-bhagavan uvaca\nparam bhuyah pravaksyami jnananam jnanam uttamam\nyaj jnatva munayah sarve param siddhimn ito gatah (14.01)", "The Supreme Lord said: Once again I will proclaim the supreme\nknowledge, the best of all knowledges (jnana, doctrine, metaphysical or\nspiritual knowledge), on knowing this, all Sages (Munis) have from this world\ngone to the supreme Perfection."],
  "2" : ["idam jnanam upasritya mama sadharmyam agatah\nsarge 'pi nopajayante pralaye na vyathanti ca (14.02)", "With this knowledge as their refuge, they reached an order of existence\nequivalent to (sddharmya) My own nature, and are not reborn at the time of\ncreation, nor do they fail at the time of dissolution."],
  "3" : ["mama yonir mahad brahma tasmin garbham dadhamy aham\nsam bhavah sarva-bhutanam tato bhavati bharata (14.03)", "My womb is the Great Brahman (Mahat Brahma), O Bharata (Arjuna), in it\nI plant the seed: from this derives the origin of all contingent beings."],
  "4" : ["sarva-yonisu Kaunteya murtayah sambhavanti yah\ntasam brahma mahad yonir aham bija-pradah pita (14.04)", "In whatever wombs beings take form, O son of Kunti (Arjuna), the Great\nBrahman (Mahat Brahma) is their womb, and I the Father, giver of the seed\n(or, life-giving)."],
  "5" : ["sattvam rajas tama iti gunah prakrti-sambhavah\nnibadhnanti maha-baho dehe dehinam avyayam (14.05)", "Sattva (goodness), Rajas (passion, activity), Tamas (ignorance, darkness,\ninertia)', these are the 'constituents' (Gunas of Nature) Matter-born (born of\nPrakriti). They bind the embodied soul, O mighty-armed (Arjuna), though\nthe indestructible sojourner (the soul) in the body."],
  "6" : ["tatra sattvam nirmalatvat prakasakam anamayam\nsukha-sangena badhnati jnana-sangena canagha (14.06)", "Of these, Sattva (goodness), being stainless, knowing no sickness, dispensing\nlight, O sinless one (Arjuna), binds by attachment to happiness (sukha, joy,\nbliss) and by attachment to knowledge."],
  "7" : ["rajo ragatmakam viddhi trsna-sanga-samudbhavam\ntan nibadhnati Kaunteya karma-sangena dehinam (14.07)", "Know, O son of Kunti (Arjuna), that Rajas (passion) is instinct with desire,\nwelling up through longing and attachment, binding the embodied soul by\nthe attachment to action."],
  "8" : ["tamas tv ajnana-jam viddhi mohanam sarva-dehinam\npramadalasya-nidrabhis tan nibadhnati bharata (14.08)", "Tamas (ignorance, darkness, inertia) is born of ignorance: know this well. It\nleads astray all embodied souls, O Bharata (Arjuna), binding fast by\nheedlessness, indolence, and sleep."],
  "9" : ["sattvam sukhe sanjayati rajah karmani bharata\njnanam avrtya tu tamah pramade sanjayaty uta (14.09)", "Sattva (goodness) causes one to cling to happiness, Rajas (passion) to action,\nO Bharata (Arjuna), but Tamas (ignorance, inertia, darkness) stifling\nknowledge, binds one to heedlessness."],
  "10" : ["rajas tamas cabhibhuya sattvam bhavati bharata\nrajah sattvam tamas caiva tamah sattvam rajas tatha (14.10)", "Sattva (goodness) prevails, having dominated Rajas (passion) and Tamas\n(ignorance, inertia, darkness), O Bharata (Arjuna), and Rajas (passion) over\nSattva (goodness) and Tamas (ignorance, inertia, darkness); and Tamas\n(ignorance, inertia, darkness) over Sattva (goodness) and Rajas (passion)."],
  "11" : ["sarva-dvaresu dehe 'smin prakasa upajayate\njnanam yada tada vidyad vivrddham sattvam ity uta (14.11)", "When through all the gates (senses) of the body, knowledge's light arises,\nthen you must know that Sattva (goodness) is predominant."],
  "12" : ["lobhah pravrttir arambhah karmanam asamah sprha\nrajasy etanijayante vivrddhe bharatarsabha (14.12)", "When Rajas (passion) is waxing strong, arise greed (avarice), the urge for\naction, commitment of oneself to action, disquiet and ambition, O best of\nthe Bharatas (Arjuna)"],
  "13" : ["aprakaso 'pravrttis ca pramado moha eva ca\ntamasy etanijayante vivrddhe kuru-nandana (14.13)", "Tamas (ignorance, inertia, darkness) constituent is predominant, when\ndarkness, inertia, heedlessness, and delusion arise, O descendent of the\nKurus (Arjuna)."],
  "14" : ["yada sattve pravrddhe tu pralayam yati deha-bhrt\ntadottama-vidam lokan amalan pratipadyate (14.14)", "However, when the embodied soul comes to face the body's dissolution\n(death), while Sattva (goodness) is predominant, then he reaches the spotless\nworlds of those who know the Highest."],
  "15" : ["rajasi pralayam gatva karma-sangisu jayate\ntatha pralinas tamasi mudha-yonisu jayate (14.15)", "Coming to dissolution (to die) when Rajas (passion) predominates, he will be\nborn among those attached to action; if dissolved (if dying) in Tamas\n(ignorance, inertia, darkness), he will be born in the womb of the ignorant\nspecies (the senseless, the foolish)."],
  "16" : ["karmanah sukrtasyahuh sattvikam nirmalam phalam\nrajasas tu phalam duhkham ajnanam tamasah phalam (14.16)", "It is said that the fruit of good actions is Sattvika (good, beneficial, pious)\nand spotless; while the fruit of Rajas (passion) is pain; and, foolishness is the\nfruit of Tamas (ignorance, inertia, darkness)."],
  "17" : ["sattvat sanjayate jnanam rajaso lobha eva ca\npramada-mohau tamaso bhavato 'jnanam eva ca (14.17)", "From Sattva (goodness) comes knowledge, from Rajas (passion) greed; and\nfrom Tamas (ignorance, inertia, darkness) error and also ignorance."],
  "18" : ["urdhvam gacchanti sattva-stha madhye tisthanti rajasah\njaghanya-guna-vrtti stha adho gacchanti tamasah (14.18)", "The higher spheres are for those who abide in Sattva (goodness), in the\nmiddle stand the Rajasic (the passionate)', stuck in the modes of the lower\nspheres, the Tamasic (the ignorant)."],
  "19" : ["nanyam gunebhyah kartaram yada drastanupasyati\ngunebhyas ca param vetti mad-bhavam so 'dhigacchati (14.19)", "When the seer perceives that there is no agent other than the constituents\n(Gunas) and knows Him, the Supreme, who is beyond them (the Gunas), he\nenters into My Nature."],
  "20" : ["gunan etan atitya trin dehi deha-samudbhavan\njanma-mrtyu jara-duhkhair vimukto 'mrtam asnute (14.20)", "Transcending these three constituents (Gunas), arising from the body's\nexistence; the embodied soul is liberated from birth, death, old age, and\npain, and attains immortality."],
  "21" : ["arjuna uvaca\nkair lingais trin gunan etan atito bhavati prabho\nkim acarah katham caitams trin gunan ativartate (14.21)", "Arjuna said: What are the marks of him who has transcended the three\nconstituents (Gunas), O Lord? How does he behave? And, how does he step\nout beyond these three constituents?"],
  "22" : ["sri-bhagavan uvaca\nprakasam ca pravrttim ca moham eva ca pandava\nna dvesti sampravrttani na nivrttani kanksati (14.22)", "The Supreme Lord said: He, O Pandava (Arjuna), who hates not radiance,\nnor activity, nor even delusion when they arise, nor longs after them when\nabsent;"],
  "23" : ["udasina-vad asino gunair yo na vicalyate\nguna vartanta ity evam yo 'vatisthati nengate (14.23)", "He who sits indifferent, unruffled by the constituents (Gunas); who,\nthinking that the constituents (Gunas) are busy, is firm-based and\nunwavering;"],
  "24" : ["sama-duhkha-sukhah sva-sthah sama-lostasma-kancanah\ntulya-priyapriyo dhiras tulya-nindatma-samstutih (14.24)", "Balanced in pleasure as in pain, who dwells in the Self, to whom a lump of\nearth, a stone or gold are alike; the same to loved and unloved ones,\nconstant, the same in blame and in praise;"],
  "25" : ["manapamanayos tulyas tulyo mitrari-paksayoh\nsarvarambha-parityagi gunatitah sa ucyate (14.25)", "The same in honour and dishonour, the same to friend and enemy,\nrelinquishing all initiative for action - he is said to have transcended the\nconstituents (Gunas)."],
  "26" : ["mam ca yo 'vyabhicarena bhakti-yogena sevate\nsa gunan samatityaitan brahma-bhuyaya kalpate (14.26)", "And, as to him who do Me honour with unswerving Yoga of devotion,\npasses beyond the constituents (Gunas), fit for becoming Brahman."],
  "27" : ["brahmano hi pratisthaham amrtasyavyayasya ca\nsasvatasya ca dharmasya sukhasyaikantikasya ca (14.27)", "For I am the final seat of Brahman, the Immortal and the Immutable, the\nEternal Dharma (the eternal law of righteousness), and the absolute\nbeatitude (sukha)."]
}
