// My Bhagavad Gita
// ch15.js
//
// This file holds the verses and translations of chapter fifteen from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author Hidayat Shah
// If you edit this file, add yourself as an author!

"15" : {
  "1" : ["sri-bhagavan uvaca/nurdhva-mulam adhah-sakham asvattham prahur avyaya/nchandamsi yasya parnani yas tarn veda sa veda-vit (15.01)","The Supreme Lord said: With roots above and branches beneath, the/nAsvattha (fig tree, banyan tree) is said to be imperishable; its leaves are the/nVedic hymns; he who knows it, knows the Vedas."],
  "2" : ["adhas cordhvam prasrtas tasya sakha guna-pravrddha visaya-pravalah/nadhas ca mulany anusantatani karmanubandhini manusya-loke (15.02)","Below and above are spread its branches, nourished by the constituents/n(Gunas of nature, Qualities); sense-objects are its buds, and below its roots/nproliferate inseparably linked with actions in the world of men."],
  "3" : ["na rupam asyeha tathopalabhyate nanto na cadir na ca sampratistha/nasvattham enam su-virudha-mulam asanga-sastrena drdhena chittva (15.03)","No form of it can here be perceived, nor its end, nor its origin, nor its/nexistence. This strongly-rooted Asvattha (fig tree, banyan tree) having been/ncut down by an unswerving sword of non-attachment;"],
  "4" : ["tatah padam tat parimargitavyam yasmin gata na nivartanti bhuyah/ntarn eva cadyam purusam prapadye yatah pravrttih prasrta purani (15.04)","Then, 'That' (tat) Goal should be sought, to which, when having tread on,/nthere is no return (saying): I take refuge in that Primeval Purusha (Person,/nMan, Principle) from whom flowed forth this ancient cosmic process"],
  "5" : ["nirmana-mohajita-sanga-dosa adhyatma-nitya vinivrtta-kamah/ndvandvair vimuktah sukha-duhkha-samjnair gacchanty amudhah padam/navyayam tat (15.05)","Free from pride and ignorance, victorious over the vice of attachment, ever/nabiding in what concerns the Self, desire suppressed, released from the/npairs of opposites (all dualities) made known in pleasure as in pain, they/ntread, undeluded, that Eternal Goal."],
  "6" : ["na tad bhasayate suryo na sasanko na pavakah/nyad gatva na nivartante tad dhama paramam mama (15.06)","Nor does the sun lights there, nor moon, nor fire. That is My supreme/n  abode (dhama, home) from where, having reached it, no one returns."],
  "7" : ["mamaivamso jiva-loke jiva-bhutah sanatanah/nmanah-sasthanindriyani prakrti sthani karsati (15.07)","A portion (a minute particle, a ray) of Mine own Self, which becomes life in/nthe living world (the living world of Jivas) into an immortal Jiva (Jivatma,/nSoul; a life, individualised from the Supreme (Eternal) Being), drawing to itself/nthe senses, with the mind as the sixth, abiding in Prakriti (matter)."],
  "8" : ["sariram yad avapnoti yac capy utkramatisvarah/ngrh itvaitani sam yati vayur gandhan ivasayat (15.08)","When the Lord assumes a body, and when He abandons it, He takes them/n(the senses and the mind), moving on with them, just as the wind wafts away/nthe scents from their sources."],
  "9" : ["srotram caksuh sparsanam ca rasanam ghranam eva ca/nadhisthaya manas cayam visayan upasevate (15.09)","through the ear, the eye, the touch, the taste, and the smell, and likewise/nthe mind, he moves among the things of sense."],
  "10" : ["utkramantam sthitam vapi bhunjanam va gunanvitam/nvimudha nanupasyanti pasyantijnana-caksusah (15.10)","The deluded do not perceive whether he (Jiva) departs (from the body) or/nremains therein, or whether, through contact with the constituents, he/ntastes experience. But those who possess the eye of knowledge see."],
  "11" : ["yatanto yoginas caiman pasyanty atmany avasthitam/nyatanto 'py akrtatmano nainam pasyanty acetasah (15.11)","The Yogis also, striving, see Him established in the Self; though striving, the/nuncontrolled, without knowledge, see Him not."],
  "12" : ["yad aditya-gatam tejo jagad bhasayate 'khilam/nyac candramsi yac cagnau tat tejo viddhi mamakam (15.12)","The splendour centred in the sun which enlightens the whole world, that/nwhich is in the moon and in the fire, know that it (all) comes from Me."],
  "13" : ["gam avisya ca bhutani dharayamy aham ojasa/npusnami causadhih sarvah somo bhutva rasatmakah (15.13)","Likewise, I penetrate the earth, and support all begins by My vital energy;/nbecoming the Soma ( 'having become the sapid (watery) moon ' is the accepted/ntranslation. Soma is a liquid drawn from the Soma-plant, or the moon plant in/nother words), the very sap )of life), I cause all the herbs to grow."],
  "14" : ["aham vaisvanaro bhutva praninam deham asritah/npranapana-samayuktah pacamy annam catur-vidham (15.14"),"I, having become Vaisvanara (the Fire of life), take possession of the bodies/nof all that breathes, conjoined with the life -breathes (Prana and Apana, the/ninward and outward breaths), I digest the fourfold food."],
  "15" : ["sarvasya caham hrdi sannivisto mattah smrtirjnanam apohanam ca/nvedais ca sarvair aham eva vedyo vedanta-krd veda-vid eva caham (15.15)","I make My dwellin gin the hearts of all: from Me are memory and/nknowledge, as well as their non-attendance. It is I who am to be known by/nmeans of all the Vedas. I am the maker of the Vedanta, and also the knower/nof the Vedas."],
  "16" : ["dvav imau purusau loke ksaras caksara eva ca/nksarah sarvani bhutani kuta-stho 'ksara ucyate (15.16)","There are two Purushas (energies) in the cosmos, the perishable (ksara) and/nthe Imperishable (askara): the perishable is all contingent beings, the/nImperishable that which stands firm (kutastha)."],
  "17" : ["uttamah purusas tv anyah paramatmety udahrtah/nyo loka-trayam avisya bibharty avyaya isvarah (15.17)","There is antoher Supreme Purusha (Energy, Person, and Supreme/nPersonality), called the Supreme Self, Indestructible Lord, pervading the/nthree worlds, and sustaining them."],
  "18" : ["yasmat ksaram atito 'ham aksarad api cottahamah/nato 'mi loke vede ca prathitah purusottamah (15.18)","Since I go beyond the perishable, and am more exalted than the/nImperishable Itself, in the world as well as in the Veda (Veddnta) I am/nextolled as the Supreme Being."],
  "19" : ["yo mam evam asammudho janati purusottamam/nsa sarva-vid bhajati mam sarva-bhavena Bharata (15.19)","He who knows Me, free from delusion, as the Supreme Self (Purushottama,/nthe Highest Purusha), he, knowing all, worships Me with all his being/n(bhdva), O Bharata (Arjuna)."],
  "20" : ["iti guhyatamam sastram idam uktam mayanagha/netad buddva buddhimnan syat krta-krtyas ca Bharata (15.20)","And so, this most secret teaching has been revealed by me, O sinless one./nThis known, let a man become enlightened, and all his duties are accomplished, O Bharata (Arjuna)."]
}
