// My Bhagavad Gita
// ch16.js
//
// This file holds the verses and translations of chapter sixteen from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"16" : {
  "1" : ["sri-bhagavan uvaca\nabhayam sattva-samsuddhir jnana-yoga-vyavasthitih\ndanam damas ca yajnas ca svadhyayas tapa arjavam (16.01)", "The Supreme Lord said: Fearlessness and purity of heart, steadfastness in\nthe yoga of knowledge, open-handed and sense-restraint, performing of\nsacrifice (Yajna), intent on the study of scriptures, austerity and integrity."],
  "2" : ["ahimsa satyam akrodhas tyagah santir apaisunam\ndaya bhutesv aloluptvam mardavam hrir acapalam (16.02)", "Non-violence, truthfulness, absence of anger, renunciation, peacefulness,\naverse to calumny, compassion to living beings, freedom from greed,\nmildness, modesty, absence of fickleness."],
  "3" : ["tejah ksama dhrtih saucam adroho nati-manita\nbhavanti sampadam daivim abhijatasya bharata (16.03)", "Vigour, mercy, fortitude, purity, absence of hatred and arrogance - these\nare his who is born to the godlike portion, O Bharata (Arjuna)."],
  "4" : ["dambho darpo 'bhimanas ca krodhah parusyam eva ca\najnanam cabhijatasya partha sampadam asurim (16.04)", "Hypocrisy, arrogance, excessive pride, anger and also cruelty and ignorance\nare his who is born to the demoniac portion (Asuric; the Asuras were the\nenemies of the Suras or Deities), O Partha {Arjuna)"],
  "5" : ["daivi sampad vimoksaya nibandhayasuri mata\nma sucah sampadam daivim abhijato 'si Pandava (16.05)", "The godlike portion is deemed for deliverance, and the demoniac for\nbondage. But grieve not, O Pandava (Arjuna)\ You are born to a godlike\ndestiny."],
  "6" : ["dvau bhuta-sargau loke 'smin daiva asura eva ca\ndaivo vistarasah prokta asuram partha me srnu (16.06)", "Basically, there are two orders of contingent beings in this world, the godly\nand the demoniac. Of the godly I have discoursed at length, now hear from\nMe, O Partha {Arjuna), about the demoniac."],
  "7" : ["pravrttim ca nivrttim ca jana na vidur asurah\nna saucam napi cacaro na satyam tesu vidyate (16.07)", "Those of demoniac nature know not of creative action (pravrtti) or of right\nabstinence (cessation, nivritti); nor purity, nor good conduct, nor truth are\nfound in them."],
  "8" : ["asatyam apratistham te jagad ahur anisvaram\naparaspara-sambhutam kim anyat kama-haitukam (16.08)", "The world, they say, is without truth, without firm foundation, without a\nGod, not ruled by mutual law, driven only by lust (desire), and nothing else."],
  "9" : ["etam drstim avastabhya nastatmano 'lpa-buddhayah\nprabhavanty ugra-karmanah ksayaya jagato 'hitah (16.09)", "Holding fast to these views, these lost souls (atman) with small intellects they\nembark on cruel and violent deeds, come forth as enemies for the\ndestruction of the world."],
  "10" : ["kamam asritya duspuram dambha-mana-madanvitah\nmohad grhitvasad-grahan pravartante 'suci-vratah (16.10)", "Surrendering themselves in insatiable sensual desire, full of hypocrisy,\npride and arrogance, holding evil thoughts through delusion, they act with\nimpure resolves."],
  "11" : ["cintam aparimeyam ca pralayantam upasritah\nkamopabhoga-parama etavad iti niscitah (16.11)", "Preoccupied with limitless imaginings right up to the time of death, they\nyield themselves at nothing but to satisfy their lusts, convinced that this is\nall."],
  "12" : ["asa-pasa-satair baddhah kama-krodha-parayanah\nihante kama-bhogartham anyayenartha-sancayan (16.12)", "Bound by a hundred ties of hope, obsessed by anger and desire, they aspire\nunjustly to accumulate hoards of wealth, to satisfy their sensual\nenjoyments."],
  "13" : ["idam adya maya labdham imam prapsye manoratham\nidam astidam api me bhavisyati punar dhanam (16.13)", "'This I have gained today; this desire I shall gratify; this wealth is mine,\nand much more too will be mine as time goes on.'"],
  "14" : ["asau maya hatah satrur hanisye caparan api\nisvaro 'ham aham bhogi siddho 'ham balavan sukhi (16.14)", "'I have killed this enemy and many another too I will kill. I am a lord, I\ntake my pleasure; I am powerful, happy and successful.'"],
  "15" : ["adhyo 'bhijanavan asmi ko 'nyo 'ti sadrso maya\nyaksye dasyami modisya ity ajnana-vimohitah (16.15)", "'I am rich and of a good family. Who else can equal himself with me? I will\nsacrifice, I will give alms, I will rejoice.' So speaks the deluded in his\nignorance."],
  "16" : ["aneka-citta-vibhranta moha-jala-samavrtah\nprasaktah kama-bhogesu patanti narake 'sucau (16.16)", "Bewildered by all kinds of thoughts, caught up in delusion's web, obsessed\nin satisfying sensual enjoyment, they fall into the foul hell."],
  "17" : ["atma-sambhavitah stabdha dhana-mana-madanvitah\nyajante nama-yajnais te dambhenavidhi-purvakam (16.17)", "Puffed up with self-conceit, stubborn, maddened by their pride of wealth\n(or, filled with madness and intoxication of wealth), they make a show of\nperforming, lip -sacrifices only for pretension, and not in the prescribed\nway."],
  "18" : ["ahankaram balam darpam kamam krodham ca samsritah\nmam atma-para-dehesu pradvisanto 'bhyasuyakah (16.18)", "Given over to selfishness, force and pride, lust and anger, these malicious\nones hate Me who dwell in their bodies as I dwell in all."],
  "19" : ["tan aham dvisatah kruran samsaresu naradhaman\nksioamy ajashram asubhan asurisv eva yonisu (16.19)", "These barbarous haters, cruel, evil, the vilest among men in the world, I\never cast them down into demoniac wombs."],
  "20" : ["asurim yonim apanna mudha janmani janmani\nmam aprapyaiva Kaunteya tato yanty adhamam gatim (16.20)", "Caught up in demoniac wombs, birth after birth deluded, they never reach\nMe, O son of Kunti {Kaunteya, Arjuna), and so they tread the lowest path."],
  "21" : ["tri-vidham narakasyedam dvaram nasanam atmanah\nkamah krodhas tatha lobhas tasmad etat trayam tyajet (16.21)", "Triple is the gate of this hell, destructive of the self: lust, anger, and greed.\nTherefore, avoid these three."],
  "22" : ["etair vimuktah Kaunteya tamo-dvarais tribhir narah\nacaraty atmanah sreyas tato yati param gatim (16.22)", "Once a man is freed from these three gates of darkness, O son of Kunti\n(Kaunteya, Arjuna), then can he work for self s salvation (sreyas), and\nthereby treading the Supreme Goal."],
  "23" : ["yah sastra-vidhim utsrjya vartate kama-karatah\nna sa siddhim avapnoti na sukham na param gatim (16.23)", "He, who forsakes the ordinances of scripture, and lives in the promptings of\nhis own desires, attains not perfection, finding no comfort (sukha), nor the\nSupreme Goal."],
  "24" : ["tasmac chastram pramanam te karyakarya-vyavasthitau\njnatva sastra-vidhanoktam karma kartum iharhasi (16.24)", "Therefore, let the scripture be your authority, determining what is right\nand wrong. Once you know what the ordinance of scripture bids you to do,\nyou should act accordingly in this world."]
}
