// My Bhagavad Gita
// ch17.js
//
// This file holds the verses and translations of chapter seventeen from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"17" : {
  "1" : ["arjuna uvaca\nye sastra-vidhim utsrjya yajante sraddhayanvitah\ntesam nistha tu ka Krsna sattvam aho rajas tamah (17.01)", "Arjuna said: Those who forsake the ordinances of the Sastras (scriptures),\nand offer sacrifices full of faith (Sraddha), where do they stand, O Krsna? Is\nit one of goodness (Sattva, Sdttvika), passion (Rajas, Rdjasika), ignorance\n(Tamas, Tdmasika, darkness)? (The three qualities or attributes, Sattva,\nRajas, Tamas are used here in their moral correspondences.)"],
  "2" : ["sri-bhagavan uvaca\ntri-vidha bhavati Sraddha dehinam sa svabhava-ja\nsattviki rajasi caiva tamasi ceti tarn srnu (17.02)", "The Supreme Lord said: Threefold is the faith (Sraddha) of embodied souls,\nalong one's own inner character, either of goodness (Sdttvic), of passion\n(Rdjasic), and of ignorance (Tdmasic). Hear now to this."],
  "3" : ["sattvanurupa sarvasya sraddha bhavati bharata\nsraddha-mayo 'yam puruso yo yac-chraddhah sa eva sah (17.03)", "(Arjuna). Man is instinct with faith (Sraddha) (that is, the man 's faith shows\nwhat his character is): as his faith is, so is he."],
  "4" : ["yajante sattvika devan yaksa-raksamsi rajasah\npretan bhuta-ganams canye yajante tamasa janah (17.04)", "The Sattvika ones (those of goodness) offer sacrifice (worship) to the Gods;\nthe Rajasika (those of passion) to the gnomes and giants (the Yakshas and the\nRakshasas, the minor gods and demons)', while the others, the Tamasika ones\n(the ignorant, or those of darkness) sacrifice to the ghosts (Pretas) and the\nassembled spirits of the dead (Bhutas). (Pretas, ghosts, are departed beings,\nwhile Bhutas, nature -spirits)"],
  "5" : ["asastra-vihitam ghoram tapyante ye tapo janah\ndambhahankara-samyuktah kama-raga-balanvitah (17.05)", "They who perform fierce austerities without regard to scripture's words,\ngiven to hypocrisy and egotism, yielding to the violence of their passion and\ndesire."],
  "6" : ["karsayantah sarira-stham bhuta-gramam acetasah\nmam caivantah sarira-stham tan viddhy asura-niscayan (17.06)", "Foolishly tormenting their bodily organs, and Me also, who dwell within the\nbody, know these to be of demoniac resolve."],
  "7" : ["aharas tv api sarvasya tri-vidho bhavati priyah\nyajnas tapas tatha danam tesam bhedam imam srnu (17.07)", "The food also which is dear to all is threefold, as also Yajna (sacrifice),\npenance (ascetic practice, austerities) and the gift of alms. Listen to the\ndifference between them."],
  "8" : ["ayuh-sattva-balarogya- sukha-priti vivardhanah\nrasyah snigdhah sthira hrdya aharah sattvika-priyah (17.08)", "The foods that augment a fuller life, strength, health, vitality (Sattva),\npleasure and good feeling, foods that are savoury, mild, strengthening,\nvigorous, are dear to the Sattivika (those in the mode of goodness)."],
  "9" : ["katv-amla-lavanaty-usna- tiksna-ruksa-vidahinah\nahara rajasasyesta duhkha-sokamaya-pradah (17.09)", "The food that are bitter, sour, salty, over-hot, pungent, dry and burning,\nare the victuals dear to the Rajasika {those in the mode of passion), and bring\npain, sorrow and sickness."],
  "10" : ["yata-yamam gata-rasam puti paryusitam ca yat\nucchistam api camedhyam bhojanam tamasa-priyam (17.10)", "Whatever foods are stale and tasteless, rotten and decayed, things that are\nleavings and unclean are the choice of the Tamasika {those in the mode of\nignorance, darkness)."],
  "11" : ["aphalakanksibhir yajno vidhi-disto ya ijyate\nyastavyam eveti manah samadhaya sa sattvikah (17.11)", "The Yajna (sacrifice, service, seva, meritorious deeds, a Vedic rite) approved\nby holy ordinance, and offered by those who would not taste its fruits, who\nconcentrate their minds on the next alone: the firm belief that Yajna\n(sacrifice, etc..) is duty, that is Sattvic (in the mode of goodness). "],
  "12" : ["abhisandhaya tu phalam dambhartham api caiva yat\nijyate bharata-srestha tarn yajnam viddhi rajas am (17.12)", "The sacrifice that is offered up by those who bear its fruits in mind, and for\nmere pretension, O best of the Bharatas (Arjuna), know them to be the\nRajasic (in the mode of passion)."],
  "13" : ["vidhi-hinam asrstannam mantra-hinam adaksinam\nsraddha-virahitam yajnam tamasam paricaksate (17.13)", "Yajna (sacrifice, etc..) contrary to proper ritual ordinances, in which no\nfood is distributed (prasadam), no sacred words recited (mantras chanted or\nrecited), no Brahman's fees paid up (covering gifts to the officiating priests),\nno faith (Sraddha) enshrined, is said to be Tamasic (in the mode of ignorance,\ndarkness). "],
  "14" : ["deva-dvija-guru-prajna- pujanam saucam ariavam\nbrahmacaryam ahimsa ca sariram tapa ucyate (17.14)", "Worship given to the Gods, to the twice-born, gurus (spiritual teachers), and\nthe wise (the learned), purity, integrity, continence (celibacy even in\nmarriage, chastity), non-violence (harmlessness), are described as bodily\npenance."],
  "15" : ["anudvega-karam vakyam satyam priya-hitam ca yat\nsvadhyayabhyasanam caiva van-mayam tapa ucyate (17.15)", "Words that do not cause offence, that are truthful, pleasant and beneficial,\nand also the practice of sacred recitation, are termed the penance of the\ntongue (or, the word)."],
  "16" : ["manah-prasadah saumyatvam maunam atma-vinigrahah\nbhava-samsuddhir ity etat tapo manasam ucyate (17.16)", "Serenity of mind and friendliness, silence and self-control, and purity of\nfeelings (bldva), this is called the penance of the mind."],
  "17" : ["sraddhaya paraya taptam tapas tat tri-vidham naraih\naphalakanksibhir yuktaih sattvikam paricaksate (17.17)", "These threefold forms of penance, practised by men with utmost faith\n(Sraddha), desiring no fruit, with a mind in total control, are described as\nSattvika (in the mode of goodness)."],
  "18" : ["satkara-mana-pujartham tapo dambhena caiva yat\nkriyate tad iha proktam rajasam calam adhruvam (17.18)", "These penances which is practised with the view of obtaining respect,\nhonour and reverence, or from sheer hypocrisy, are here said to be Rajasic\n(in the mode of passion), unstable and transient."],
  "19" : ["mudha-grahenatmano yat pidaya kriyate tapah\nparasyotsadanartham va tat tamasam udahrtam (17.19)", "These penances performed out of perverted theories, through self-torture,\nor with the object of hurting others, is declared to be Tamasic (in the mode\nof ignorance)."],
  "20" : ["data vy am iti yad danam diyate 'nupakarine\ndese kale ca patre ca tad danam sattvikam smrtam (17.20)", "Alms given to one from whom no favour is expected in return, in the belief\nthat it is one's sacred duty to give, at the right place and time, to a worthy\nperson, is called alms given in a Sattvic way (in the mode of goodness)."],
  "21" : ["yat tu Pratyupakarartham phalam uddisya va punah\ndiyate ca pariklistam tad danam rajasam smrtam (17.21)", "But alms given in expectation of receiving favours in return, or for the sake\nof reaping some fruit afterwards, or again reluctantly, that giving is held to\nbe Rajasic (in the mode of passion)."],
  "22" : ["adesa-kale yad danam apatrebhyas ca diyate\nasat-krtam avajnatam- tat tamasam udahrtam (17.22)", "Alms given at the wrong place and time, to unworthy persons, without\nrespect or with insult that is declared to be Tamasic (in the mode of\nignorance)."],
  "23" : ["om tat sad iti nirdeso brahmanas tri-vidhah smrtah\nbrahmanas tena vedas ca yajnas ca vihitah pura (17.23)", "'Om, Tat, Sat': This has been considered as a threefold pointer to\nBrahman {Eternal Being). Through this, were created, in the beginning, the\nBrahmanas {the knowers of Brahman, or the priests, or intellectual class of\nIndia), and Vedas and Yajnas {sacrificial rites) ordained."],
  "24" : ["tasmad om ity udahrtya yajna-dana-tapah-kriyah\npravartante vidhanoktah satatam brahma-vadinam (17.24)", "Therefore, by uttering 'Om', are the acts of sacrifice, the giving of alms\nand penance accomplished, in conformity to ordinances {Vedic scriptures),\never again enacted by Brahman's devotees."],
  "25" : ["tad ity anabhisandhaya phalam yajna-tapah-kriyah\ndana-kriyas ca vividhah kriyante moksa-kanksibhih (17.25)", "With the utterance of 'Tat' (That), do those who seek liberation (Moksa,\nNirvana, Mukti), perform the various acts of sacrifice, penance and the gift\nof alms, having no thought for the fruits they produce."],
  "26" : ["sad-bhave sadhu-bhave ca sad ity etat prayujyate\nprasaste karmani tatha sac-chabdah partha yujyate (17.26)", "'Sat' (It Is) is used to indicate the Real and the Good; the word 'Sat' is\nlikewise used, O Partha (Arjuna), for works that call forth praise."],
  "27" : ["yajne tapasi dane ca sthitih sad iti co' cyate\nkarma caiva tad-arthiyam sad ity evabhidhiyate (17.27)", "Steadfastness in sacrifice, penance, the giving of alms, is also called 'Sat',\nand any action for the sake of the Supreme (Tat) is equally known as 'Sat'."],
  "28" : ["asraddhaya hutam dattam tapas taptam krtam ca yat\nasad ity ucyate Partha na ca tat pretya no iha (17.28)", "Whatever is sacrificed, any giving, any penance, or any other deed,\npractised without faith (Sraddhd), it is called 'Asat', O Partha (Arjuna); of\nno benefit in this world and the next (both in this life and the next)."]
}
