// My Bhagavad Gita
// ch18.js
//
// This file holds the verses and translations of chapter eighteen from the Bhagavad Gita
//
// @author Vivek Bhookya
// @author
// If you edit this file, add yourself as an author!

"18" : {
  "1" : ["arjuna uvaca\nsannyasasya maha-baho tattvam icchami veditum\ntyagasya ca hrsikesa prthak kesi-nisudana (18.01)", "Arjuna said: O Mighty-armed, O Hrsikesa (Krsna), I desire to know from\nYou the truth concerning renunciation (sannydsa) as well as of\nabandonment (tyaga), with their difference, O Kesinisudana (O Slayer of\nKesin, Krsna)."],
  "2" : ["sri-bhagavan uvaca\nkamyanam karmanam nyasam sannyasam kavayo viduh\nsarva-karma-phala-tyagam prahus tyagam vicaksanah (18.02)", "The Supreme Lord said: To give up works dictated by desire, Sages know\nthis to be renunciation (sannydsa); the abandonment of the fruit of all\nworks, say the learned, is tyaga (renunciation, abandonment)."],
  "3" : ["tyajyam dosa-vad ity eke karma prahur manisinah\nyajna-dana-tapah-karma na tyajyam iti capare (18.03)", "Some learned men say that actions, tainted with defect, should be given up;\nbut, others say that actions of sacrifice, the gift of alms and deeds of\npenance should not be abandoned."],
  "4" : ["niscayam srnu me tatra tyage bharata-sattama\ntyago hi purusa-vyaghra tri-vidhah samprakirtitah (18.04)", "Hear then My own conclusions as to abandonment (tydga), O best of the\nBharatas (Arjuna). Indeed, O best of men (O tiger of men, Arjuna),\nabandonment (tydga) is regarded as being threefold."],
  "5" : ["yajna-dana-tapah-karma na tyajyam karyam eva tat\nyajno danam tapas caiva pavanani manisinam (18.05)", "Acts of sacrifice, the gift of alms and deeds of penance are not to be\nabandoned, but should most certainly be done, because sacrifice,\nalms-giving and penance (ascetic practise) are purifiers of the intelligent."],
  "6" : ["etany api tu karmani sangam tyaktva phalani ca\nkartavyaniti me Partha niscitam matam uttamam (18.06)", "But even these actions should be done, detachedly and abandoning the fruit,\nO Partha (Arjuna), this is My certain and supreme belief."],
  "7" : ["niyatasya tu sannyasah karmano nopapadyate\nmohat tasya parityagas tamasah parikirtitah (18.07)", "For to renounce actions (duties) that are prescribed (by scripture) is\ninappropriate; delusively to give it up is Tamasic (in the mode of ignorance,\ndarkness). This (also) has been declared."],
  "8" : ["duhkham ity eva yat karma kaya-klesa-bhayat tyajyt\nsa krtva rajasam tyagam naiva tyaga-phalam labhet (18.08)", "The one who gives up an action simply because it causes pain, or because he\nshrinks from bodily distress, commits an act of abandonment that accords\nwith Rajasika (in the mode of passion); for sure the person will not reap the\nfruit of abandonment (tyaga)."],
  "9" : ["karyam ity eva yat karma niyatam kriyate 'rjuna\nsangam tyaktva phalam caiva sa tyagah sattviko matah (18.09)", "Whatever obligatory action is achieved, saying, \"it should be done\", O\nArjuna, abandoning attachment and also the fruit, that abandonment is\nheld to be Sattvika (in the mode of goodness)."],
  "10" : ["na dvesty akusalam karma kusale nanusajjate\ntyagi sattva-samavisto medhavi chinna-samsayah (18.10)", "The renouncer suffused with goodness (sattva), with a calm understanding,\nfree from doubts, hates not his disagreeable work nor cleaves to the\nagreeable one."],
  "11" : ["na hi deha-bhrta sakyam tyaktum karmany asesatah\nyas tu karma-phala-tyagi sa tyagity abhidhiyate (18.11)", "For an embodied being it is not possible to abandon actions completely;\nrather it is he who abandons the fruits of actions who deserves the name of\na renouncer."],
  "12" : ["anistam istam misram ca tri-vidham karmanah phalam\nbhavaty atyaginam pretya na tu sannyasinam kvacit (18.12)", "Threefold is the fruit of action, unwanted, wanted and mixed, which the one\nwho has not renounced, experiences after death, but not those who have\nrenounced."],
  "13" : ["pancaitani maha-baho karanani nibodha me\nsankhye krtante proktani siddhaye sarva-karmanam (18.13)", "Learn from Me, O mighty-armed (Arjuna), these five factors as laid down in\nthe philosophy of the Sankhya, for the accomplishment of all actions:"],
  "14" : ["adhisthanam tatha karta karanam ca prthag-vidham\nvividhas ca prthak cesta daivam caivatra pancamam (18.14)", "They are: The physical body, the doer, the various kinds of organs, the\ndifferent impulses, and the fifth, the presiding deities."],
  "15" : ["sarira-van-manobhir yat karma prarabhate narah\nnyayyam va viparitam va pancaite tasya hetavah (18.15)", "Whatever action a man may undertake, by his body, speech or mind, no\nmatter whether right or wrong, these are its five causes."],
  "16" : ["tatraivam sati kartaram atmanam kevalam tu yah\npasyaty akrta-buddhitvan na sa pasyati durmatih (18.16)", "That being so, the man who sees himself alone, as the agent, does not see at\nall. Untrained is his intelligence, and perverted are his thoughts."],
  "17" : ["yasya nahankrto bhavo buddhir yasya na lipyate\nhatvapi sa imal lokan na hanti na nibadhyate (18.17)", "He whose nature is not egoistic, whose intellect is not stained, even though\nhe slays the whole world, slays nothing, and is not subject to bondage."],
  "18" : ["jnanam jneyam parijnata tri-vidha karma-codana\nkaranam karma karteti tri-vidhah karma-sangrahah (18.18)", "Knowledge, the knowable, and the knower, these constitute the threefold\ninstrumental cause of action (karma). The instrument (or, organ), the action,\nand the agent (the doer) form the threefold basis of action."],
  "19" : ["jnanam karma ca karta ca tridhaiva guna-bhedatah\nprocyate guna-sankhyane yathavac chrnu tany api (18.19)", "Knowledge, action and agent (the doer), these too are three in kind,\ndistinguished by the three constituents (Gunas), enunciated in the Sankhya\nphilosophy, according to the distinction of the constituents. Listen correctly\nabout these also."],
  "20" : ["sarva-bhutesu yenaikam bhavam avyayam iksate\navibhaktam vibhaktesu taj jnanam viddhi sattvikam (18.20)", "That knowledge by which one sees the Imperishable Being changeless,\nundivided in all contingent beings divided, know that knowledge as Sattvika\n(in the mode of goodness)."],
  "21" : ["prthaktvena tu yaj jnanam nana-bhavan prthag-vidhan\nvetti sarvesu bhutesu taj jnanam viddhi rajas am (18.21)", "But the knowledge by which one sees in all contingent beings, manifold\nentities of different kinds, distinct from one another, know that knowledge\nto be Rajasic (in the mode of passion)."],
  "22" : ["yat tu krtsna-vad ekasmin karye saktam ahaitukam\natattvartha-vad alpam ca tat tamasam udahrtam (18.22)", "And that knowledge which concentrates on a single effect as if it were the\nwhole, irrational, not grasping the Truth as the object of all -knowledge,\ntrivial and easy, that is declared to be Tamasic (in the mode of ignorance)."],
  "23" : ["niyatam sanga-rahitam araga-dvesatah krtam\naphala-prepsuna karma yat tat sattvikamn ucyate (18.23)", "A prescribed action (Karma), free from all attachment, performed without\npassion, without hate, by one not desirous of the fruit, that action is called\nto be Sattvic (in the mode of goodness)."],
  "24" : ["yat tu kamepsuna karma sahankarena va punah\nkriyate bahulayasam tad rajasam udahrtam (18.24)", "But that action which is done by longing for desires, or again with egoism,\nor in expanding much effort, that is declared to be Rajasic (in the mode of\npassion)."],
  "25" : ["anubandham ksayam himsam anapeksya ca paurusam\nmohad arabhyate karma yat tat tamasam ucyate (18.25)", "The action which is undertaken by a deluded man, who has no thought of\nconsequence, loss and injury to others, or for the human part he plays\nhimself, is called Tamasic (in the mode of ignorance)."],
  "26" : ["mukta-sango 'naham-vadi dhrty-utsaha-samanvitah\nsiddhy-asiddhyor nirvikarah. karta sattvika ucyate (18.26)", "The agent who is free from attachment, not egoistic, steadfast and resolute,\nunaffected by success or failure, is said to be Sattvic (good)."],
  "27" : ["ragi karma-phala-prepsur lubdho himsatmako 'sucih\nharsa-sokanvitah karta rajasah parikirtitah (18.27)", "The agent who is passionate, desiring to pursue the fruits of action, greedy,\nintent on doing harm, impure, a prey to joy and to sorrow, is widely known\nto follow the Rajasic way (the passion's way)."],
  "28" : ["ayuktah prakrtah stabdhah satho naiskrtiko 'lasah\nvisadi dirgha-sutri ca karta tamasa ucyate (18.28)", "The agent, unsteady (ayukta), brutish, self-important, malicious, unfair,\nlazy, who is subject to depression, who procrastinates, is called Tamasic\n(ignorant, to be of darkness)."],
  "29" : ["buddher bhedam dhrtes caiva gunatas tri-vidham srnu\nprocyamanam asesena prthaktvena Dhananjaya (18.29)", "Listen to the threefold division of the intellect as well as constancy arising\nout of the constituents, which I will set forth in all its many forms, omitting\nnothing, O Dhananjaya (O conqueror of wealth, Arjuna)."],
  "30" : ["pravrttim ca nivrttim ca karyakarye bhayabhaye\nbandham moksam ca ya vetti buddhih sa partha sattvika (18.30)", "The intellect that distinguishes between action and its cessation, between\nwhat should be done and what not, between fear and fearlessness, bondage\nand release, that intellect is Sattvic (in the mode of goodness), O Partha (Arjuna)."],
  "31" : ["", ""],
  "32" : ["", ""],
  "33" : ["", ""],
  "34" : ["", ""],
  "35" : ["", ""],
  "36" : ["", ""],
  "37" : ["", ""],
  "38" : ["", ""],
  "39" : ["", ""],
  "40" : ["", ""],
  "41" : ["", ""],
  "42" : ["", ""],
  "43" : ["", ""],
  "44" : ["", ""],
  "45" : ["", ""],
  "46" : ["", ""],
  "47" : ["", ""],
  "48" : ["", ""],
  "49" : ["", ""],
  "50" : ["", ""],
  "51" : ["", ""],
  "52" : ["", ""],
  "53" : ["", ""],
  "54" : ["", ""],
  "55" : ["", ""],
  "56" : ["", ""],
  "57" : ["", ""],
  "58" : ["", ""],
  "59" : ["", ""],
  "60" : ["", ""],
  "61" : ["", ""],
  "62" : ["", ""],
  "63" : ["", ""],
  "64" : ["", ""],
  "65" : ["", ""],
  "66" : ["", ""],
  "67" : ["", ""],
  "68" : ["", ""],
  "69" : ["", ""],
  "70" : ["", ""],
  "71" : ["", ""],
  "72" : ["", ""],
  "73" : ["", ""],
  "74" : ["", ""],
  "75" : ["", ""],
  "76" : ["", ""],
  "77" : ["", ""],
  "78" : ["", ""]
}
